#pragma once

// Generated by tools/generate_actor_admission_reference.py; native 797B/79BB and script admission
// Physics, firing and HUD work intercepted by the native Frame harness.
#include <array>

namespace darker::test_reference {

inline constexpr std::array<std::array<unsigned int,4>,4> actor_admission_samples{{
  {0,0,0,1},
  {0,1,1,1},
  {1,0,0,1},
  {1,1,0,1},
}};

} // namespace darker::test_reference
