#pragma once

// Generated by tools/generate_city_frame_reference.py; original city setup and drawing, identity shade table
// Image SHA-256: 7599201a01aa24b7e6ad1ae4295d493821cde7c3a43b247c464522626c0380a4

#include <array>
#include <cstdint>

namespace darker::test_reference {

struct city_frame_sample { unsigned int slot, column, row, altitude, heading, pitch, clock, count; std::uint64_t map, frame; };
inline constexpr std::array<city_frame_sample, 12> city_frame_samples{{
  {30, 14976, 18816, 2048, 0, 61440, 0, 30, 0x7b914d632178286a, 0xb46469053c76e682},
  {30, 12672, 28416, 512, 32768, 0, 341, 26, 0x7b914d632178286a, 0x32e1ea68a1704627},
  {30, 13888, 18496, 700, 8192, 0, 682, 22, 0x7b914d632178286a, 0x6fc93626dc364cb4},
  {30, 16512, 16512, 2048, 0, 61440, 1023, 17, 0x7b914d632178286a, 0x8070e274076f7e4a},
  {30, 256, 256, 1024, 32768, 4096, 1364, 10, 0x7b914d632178286a, 0x80a69197c1fb9325},
  {30, 32512, 32512, 1024, 0, 61440, 1705, 1, 0x7b914d632178286a, 0x933036bd5a9e5a9c},
  {31, 14976, 18816, 2048, 0, 61440, 0, 8, 0x33266d9639407fd5, 0xaddef80533cd3ddd},
  {31, 12672, 28416, 512, 32768, 0, 341, 1, 0x33266d9639407fd5, 0x80a69197c1fb9325},
  {31, 13888, 18496, 700, 8192, 0, 682, 12, 0x33266d9639407fd5, 0xb4c6f92d50fceed4},
  {31, 16512, 16512, 2048, 0, 61440, 1023, 7, 0x33266d9639407fd5, 0x431d23bf1e073ffd},
  {31, 256, 256, 1024, 32768, 4096, 1364, 0, 0x33266d9639407fd5, 0x80a69197c1fb9325},
  {31, 32512, 32512, 1024, 0, 61440, 1705, 0, 0x33266d9639407fd5, 0x80a69197c1fb9325},
}};

} // namespace darker::test_reference
