#pragma once

// Generated by tools/generate_city_frame_reference.py; original city setup and drawing, identity shade table
// Image SHA-256: 7599201a01aa24b7e6ad1ae4295d493821cde7c3a43b247c464522626c0380a4

#include <array>
#include <cstdint>

namespace darker::test_reference {

struct city_frame_sample { unsigned int slot, column, row, altitude, heading, pitch, clock, count; std::uint64_t map, frame; };
inline constexpr std::array<city_frame_sample, 12> city_frame_samples{{
  {30, 14976, 18816, 2048, 0, 61440, 0, 106, 0x7b914d632178286a, 0x9c302cfbd71ff003},
  {30, 12672, 28416, 512, 32768, 0, 341, 95, 0x7b914d632178286a, 0x22d7c862a2d6a50d},
  {30, 13888, 18496, 700, 8192, 0, 682, 80, 0x7b914d632178286a, 0xe8d18d3ae48298a6},
  {30, 16512, 16512, 2048, 0, 61440, 1023, 79, 0x7b914d632178286a, 0x0bcd52363eae14de},
  {30, 256, 256, 1024, 32768, 4096, 1364, 56, 0x7b914d632178286a, 0x3cb03fa04c983645},
  {30, 32512, 32512, 1024, 0, 61440, 1705, 4, 0x7b914d632178286a, 0x933036bd5a9e5a9c},
  {31, 14976, 18816, 2048, 0, 61440, 0, 50, 0x33266d9639407fd5, 0xa65646b9b1356732},
  {31, 12672, 28416, 512, 32768, 0, 341, 1, 0x33266d9639407fd5, 0x80a69197c1fb9325},
  {31, 13888, 18496, 700, 8192, 0, 682, 80, 0x33266d9639407fd5, 0x48c3cf3f09319fe3},
  {31, 16512, 16512, 2048, 0, 61440, 1023, 50, 0x33266d9639407fd5, 0xfb8ae52e1453a114},
  {31, 256, 256, 1024, 32768, 4096, 1364, 0, 0x33266d9639407fd5, 0x80a69197c1fb9325},
  {31, 32512, 32512, 1024, 0, 61440, 1705, 0, 0x33266d9639407fd5, 0x80a69197c1fb9325},
}};

} // namespace darker::test_reference
