#pragma once

// Generated by tools/generate_font_reference.py; native E29C/E1FE coverage and plane patterns
// Image SHA-256: 7599201a01aa24b7e6ad1ae4295d493821cde7c3a43b247c464522626c0380a4

#include <array>
#include <cstdint>

namespace darker::test_reference {

struct font_sample { unsigned int face, phase, count; std::uint64_t fingerprint; };
inline constexpr std::array<font_sample, 12> font_samples{{
  {0, 0, 107, 0x9cf03f8a20018127},
  {0, 1, 107, 0x2aec33e507720743},
  {0, 2, 107, 0x5e947b23508ce417},
  {0, 3, 107, 0x90c8971df1d903a8},
  {1, 0, 97, 0xf919d65a4dbfe2d2},
  {1, 1, 97, 0xcf649287388960f7},
  {1, 2, 97, 0xcc73717c428d1db0},
  {1, 3, 97, 0x73260e073a713735},
  {2, 0, 96, 0x898e8628cbc8c1b0},
  {2, 1, 96, 0x20b7bb45f682c743},
  {2, 2, 96, 0x02333de08670c13e},
  {2, 3, 96, 0x804f191d16d4e711},
}};

} // namespace darker::test_reference
