#pragma once

// Generated by tools/generate_geometry_bank_reference.py; native 2DE1 with original bank data
// Image SHA-256: 7599201a01aa24b7e6ad1ae4295d493821cde7c3a43b247c464522626c0380a4

#include <array>
#include <cstdint>

namespace darker::test_reference {

struct geometry_bank_sample { unsigned int slot, types, specials, pool_size, tail_size, mask; std::uint64_t fingerprint; };
inline constexpr std::array<geometry_bank_sample, 3> geometry_bank_samples{{
  {30, 137, 33, 61289, 1777, 32, 0xe012287d139b02a5},
  {31, 80, 33, 25483, 898, 96, 0x722b7cd12c8a2a25},
  {32, 174, 33, 54148, 5789, 96, 0x5c53dbab983900a5},
}};

} // namespace darker::test_reference
