#pragma once

// Generated by tools/generate_mission_exchange_reference.py; original C2E4/C77E
// Image SHA-256: 7599201a01aa24b7e6ad1ae4295d493821cde7c3a43b247c464522626c0380a4

#include <array>

namespace darker::test_reference {

inline constexpr std::array<std::array<int, 6>, 12> mission_owner_samples{{
  {0, 0, 55686, 0, 0, 1},
  {0, 55798, 55686, 55798, 0, 1},
  {0, 55910, 55686, 55910, 0, 1},
  {1000, 0, 55686, 0, 1000, 1},
  {1000, 55798, 55686, 55798, 1000, 1},
  {1000, 55910, 55686, 55910, 1000, 1},
  {32768, 0, 55686, 0, 32768, 1},
  {32768, 55798, 55686, 55798, 32768, 1},
  {32768, 55910, 55686, 55910, 32768, 1},
  {65535, 0, 55686, 0, 65535, 1},
  {65535, 55798, 55686, 55798, 65535, 1},
  {65535, 55910, 55686, 55910, 65535, 1},
}};

inline constexpr std::array<std::array<int, 9>, 4> mission_exchange_samples{{
  {0, 0, 0, 5, 4, 0, 1, 2, 50},
  {1000, 1000, 0, 5, 4, 0, 1, 2, 1050},
  {32768, 32768, 0, 5, 4, 0, 1, 2, 32818},
  {65535, 65535, 0, 5, 4, 0, 1, 2, 49},
}};

} // namespace darker::test_reference
