#pragma once
#include <array>
#include <cstdint>

// Generated by tools/generate_presentation_reference.py after DF36 pixel comparisons.
namespace darker::test_reference {
struct presentation_sample { unsigned int slot, frame, pixels; uint64_t fingerprint; };
inline constexpr auto presentation_samples = std::to_array<presentation_sample>({
  {1, 0, 949, 0x541440cc397469f9ULL},
  {1, 1, 1188, 0xb9b7af24e2a7acadULL},
  {1, 2, 1568, 0x7dc075648e8a888bULL},
  {1, 3, 1954, 0xa8cd57f4984d3a68ULL},
  {1, 4, 2042, 0xa78659b15a7df3cbULL},
  {1, 5, 2023, 0x8f03f005c71e2fffULL},
  {1, 6, 2020, 0x5af97bf0bcb7461cULL},
  {1, 7, 2014, 0xe76b565f6fb86e3fULL},
  {1, 8, 2013, 0xdfd5de76ae44fd12ULL},
  {1, 9, 1998, 0xf69c1ef237af27f0ULL},
  {1, 10, 1971, 0x87ded9699415533bULL},
  {1, 11, 1910, 0x25d24d92b7d079caULL},
  {1, 12, 1965, 0x8624baf071ddc0bdULL},
  {1, 13, 1900, 0x7f4124512407116eULL},
  {1, 14, 1881, 0xf4d127ffcb9ec283ULL},
  {1, 15, 1752, 0x47ebca5baad16ab9ULL},
  {1, 16, 1542, 0x942aa8191d8d3562ULL},
  {1, 17, 1448, 0x9a70929bca25141fULL},
  {1, 18, 1185, 0xd978800f925b1f19ULL},
  {1, 19, 745, 0xc9b5661399da1819ULL},
  {2, 0, 8719, 0xa7e5eaabbd44de35ULL},
  {2, 1, 8676, 0x078c9b7baf434c80ULL},
  {2, 2, 8658, 0x9abf709b2fd357e0ULL},
  {2, 3, 8666, 0xb5f8cd6c1b8416edULL},
  {2, 4, 8585, 0x618289e905f427ffULL},
  {2, 5, 8659, 0x5ad1f6c87eb42a69ULL},
  {2, 6, 8686, 0xdf81df77c515b3e2ULL},
  {2, 7, 8600, 0xcd103c1d76f3d680ULL},
  {2, 8, 8507, 0xfb1b5448cdeaec68ULL},
  {2, 9, 8450, 0x8d0d938682dae7b5ULL},
  {2, 10, 8510, 0x7690790b33676b20ULL},
  {2, 11, 8412, 0x2ac3596af52e07a9ULL},
  {2, 12, 8472, 0x30fe4d28ed498140ULL},
  {2, 13, 8457, 0x3b2f68b65ccf48abULL},
  {2, 14, 8415, 0xa323d6f8d7a84c42ULL},
});
} // namespace darker::test_reference
