#pragma once

// Generated by generate_menu_text.py; original glyph bytes and authored X positions.
#include <array>
#include <string_view>

namespace darker::presentation {

struct menu_line { int x; std::string_view text; };
struct menu_text {
  std::string_view select, game, level, new_game;
  menu_line name_title, name_prompt;
  std::array<menu_line,4> actions;
  std::array<menu_line,3> erase, erase_score;
  std::string_view question, yes, no;
  menu_line quit;
  std::string_view score, best_score;
};

inline constexpr std::array<menu_text,3> original_menu_text{{
  {"Select a game: 1,2,3,4 or N", "Game ", "Level ", "Start a new game", {104, "START NEW GAME"}, {88, "Please enter your name"}, {{{76, "ENTER: Run this game"}, {83, "S: Select a different game"}, {83, "E: Erase this game"}, {76, "ESC: Quit to DOS"}}}, {{{120, "ERASE GAME"}, {78, "It will be permanently lost"}, {148, "- - -"}}}, {{{100, "ERASE HIGH SCORE"}, {98, "It will be reset to 0%"}, {148, "- - -"}}}, "Do you wish to proceed?", "YES", "NO", {121, "QUIT TO DOS"}, "\004\004Score: \007%", "\004High score: \007%"},
  {"S\177lectionner un jeu: 1,2,3,4 or N", "Jeu  ", "Niveau ", "Commencer un nouveau jeu", {63, "COMMENCER UN NOUVEAU JEU"}, {108, "Entrez votre nom"}, {{{76, "ENTER: Ex\177cuter ce jeu"}, {81, "S: S\177lectionner un autre jeu"}, {81, "E: Effacer ce jeu"}, {76, "ESC: Retourner au DOS"}}}, {{{111, "EFFACER LE JEU"}, {78, "Il sera perdu pour toujours"}, {148, "- - -"}}}, {{{133, "EFFACER"}, {97, "LE MEILLEUR SCORE"}, {105, "Il sera remis \205 0%"}}}, "Voulez-vous continuer?", "OUI", "NON", {97, "RETOURNER AU DOS"}, "\004Score: \007%", "\004Meilleur score: \007%"},
  {"W\204hlen Sie ein Spiel: 1,2,3,4 oder N", "Spiel ", "Level ", "Neues Spiel starten", {92, "NEUES SPIEL STARTEN"}, {62, "Bitte geben Sie Ihren Namen ein."}, {{{76, "ENTER: Spiel starten"}, {83, "S: Anderes Spiel w\204hlen"}, {83, "E: Spiel l\203schen"}, {76, "ESC: Zur\211ck zu DOS"}}}, {{{114, "SPIEL L\213SCHEN"}, {110, "Spiel kann nicht"}, {81, "wiederhergestellt werden."}}}, {{{95, "HIGHSCORE L\213SCHEN"}, {91, "Highscore wird auf 0%"}, {117, "zur\211ckgesetzt"}}}, "Wollen Sie fortfahren?", "JA", "NEIN", {110, "ZUR\210CK ZU DOS"}, "Punktestand: \007%", "\004Highscore: \007%"},
}};

inline constexpr std::array<std::string_view,3> original_credits{{
  std::string_view{"\006Written by Jas.C.Brooke\000\003\006Artwork by Lyndon Brooke\000\003\006Music by PC Music\000\003\005\000\013\001\242\000\006Producer: Richard Biltcliffe.\000\003\006Product managers: Michaela Riches, Nadia Lawlor\000\003\006Music manager: Phil Morris\000\003\001\311\000\006Thanks to Mark & Joan Brooke and Rachel Chalmers\000\003\003\006A Day 1 production. Copyright (C) 1995 S.I.E.E\000\000", 294},
  std::string_view{"\006R\177alis\177 par Jas.C.Brooke\000\003\006Graphismes de Lyndon Brooke\000\003\006Musique de PC Music\000\003\005\000\013\001\242\000\006Chef de projet: Richard Biltcliffe.\000\003\006Chefs de produit: Michaela Riches, Nadia Lawlor\000\003\006Responsable musique: Phil Morris\000\003\001\311\000\006Remerciements \205 Mark Brooke et Rachel Chalmers\000\003\003\006Une production de Day 1. Copyright (C) 1995 S.I.E.E\000\000", 315},
  std::string_view{"\006Programmiert von Jas.C.Brooke\000\003\006Artwork von Lyndon Brooke\000\003\006Musik von PC Music\000\003\005\000\013\001\242\000\006Produzent: Richard Biltcliffe.\000\003\006Produkt-Manager: Michaela Riches, Nadia Lawlor\000\003\006Musik-Manager: Phil Morris\000\003\001\311\000\006Dank an Mark & Joan Brooke und Rachel Chalmers\000\003\003\006Eine Day 1 Produktion. Copyright (C) 1995 S.I.E.E\000\000", 303},
}};

} // namespace darker::presentation
