#include <catch2/catch_test_macros.hpp>
#include <algorithm>
#include <cmath>
#include <filesystem>
#include <future>
#include <span>
#include <string_view>
#include <vector>
#include "audio/fm_stream.h"
#include "audio/gus_synth.h"
#include "resources/archive_set.h"

TEST_CASE("Gravis native library sounds and releases notes independently of output blocks", "[audio][gus]") {
  if(std::string_view{DARKER_TEST_GUS_DIR}.empty() || std::string_view{DARKER_TEST_RESOURCE_DIR}.empty())
    SKIP("Supply DARKER_TEST_GUS_DIR and DARKER_REFERENCE_DIR for native Gravis verification");
  auto const render{[&](size_t const block) {
    darker::audio::gus_synth synth{DARKER_TEST_GUS_DIR, 48000};
    synth.reset();
    synth.send({0xc0, 0});
    synth.send({0x90, 60, 100});
    std::vector<float> pcm(48000 * 4);
    for(size_t offset{}; offset < pcm.size();) {
      auto const count{std::min(block * 2, pcm.size() - offset)};
      synth.render(std::span{pcm}.subspan(offset, count));
      offset += count;
    }
    double energy{};
    REQUIRE(std::ranges::all_of(pcm, [](float value) { return std::isfinite(value); }));
    for(float const value : pcm) energy += std::abs(value);
    REQUIRE(energy > 1);
    synth.send({0x80, 60, 0});
    synth.reset();
    std::vector<float> tail(48000 * 8);
    synth.render(tail);
    double late{};
    for(size_t i{tail.size() - 48000}; i < tail.size(); ++i) late += std::abs(tail[i]);
    REQUIRE(late < energy * 0.1);
    return pcm;
  }};
  REQUIRE(render(512) == render(257));
}

TEST_CASE("All six Gravis arrangements survive consecutive group changes", "[audio][gus]") {
  if(std::string_view{DARKER_TEST_GUS_DIR}.empty() || std::string_view{DARKER_TEST_RESOURCE_DIR}.empty())
    SKIP("Supply Gravis patches and extracted resource paths");
  auto const load{[](unsigned int const slot) {
    auto const filename{"00_" + std::to_string(slot).insert(0, 3 - std::to_string(slot).size(), '0') + ".bin"};
    return darker::resources::read_binary_file(std::filesystem::path{DARKER_TEST_RESOURCE_DIR} / filename, 65536);
  }};
  darker::audio::fm_stream stream{48000};
  std::array<std::vector<std::byte>,6> songs;
  for(unsigned int group{}; group < songs.size(); ++group) songs[group] = load(41 + group * 5);
  stream.configure_gus_music(DARKER_TEST_GUS_DIR, std::move(songs));
  for(int group{}; group < 6; ++group) {
    stream.select_music(group);
    std::vector<float> pcm(48000 * 40);
    std::async(std::launch::async, [&] { stream.render(pcm); }).get();
    double energy{};
    REQUIRE(std::ranges::all_of(pcm, [](float value) { return std::isfinite(value); }));
    for(float const value : pcm) energy += std::abs(value);
    REQUIRE(energy > 1);
    if(group == 0) {
      // The known opening arrangement has no abrupt full-scale steps here.
      // Discarding PCM generated by register polling produced 0.816-sized
      // jumps at the native interrupt cadence; continuous output peaks below 0.185.
      float largest_step{};
      for(size_t i{2}; i < 48000 * 10 * 2; ++i)
        largest_step = std::max(largest_step, std::abs(pcm[i] - pcm[i - 2]));
      REQUIRE(largest_step < 0.25f);
    }
    stream.select_music(-1);
    std::array<float,512> silence{};
    stream.render(silence);
  }
}
