#!/usr/bin/env python3
"""Capture native single-box swept intersections and impact rounding."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    image=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest()!=IMAGE_SHA256:raise ValueError('Unsupported unpacked executable')
    h=Harness(image)
    patch=lambda at,value:h.write(at,struct.pack('<H',value&65535))
    patch(0xfdf0,0x6000);h.cpu.mem_write(0x6a000,struct.pack('<H',0x1000))
    patch(0x60a0,1000);patch(0x60b8,2000);patch(0x607b,128);patch(0x60c3,0)
    hit=False
    def capture(cpu,address,size,data):
        nonlocal hit
        if address-h.BASE==0x606e:hit=True
    h.cpu.hook_add(UC_HOOK_CODE,capture)
    rng=random.Random(0x60d4)
    cases=[]
    for index in range(4096):
        origin_x=rng.choice((1000,100,32700,65400))
        origin_y=rng.choice((2000,100,32700,65400))
        patch(0x60a0,origin_x);patch(0x60b8,origin_y)
        low=[rng.randrange(-100,0),rng.randrange(-100,0)]
        high=[rng.randrange(1,101),rng.randrange(1,101)]
        height=rng.randrange(1,1000)
        h.cpu.mem_write(0x68000,bytes([8|(height>>8),height&255,low[0]&255,high[0],low[1]&255,high[1],0xf8]))
        minimum=[origin_x+low[0],origin_y+low[1],128]
        maximum=[origin_x+1+high[0],origin_y+1+high[1],128+height]
        start=[rng.randrange(lo-300,hi+300) for lo,hi in zip(minimum,maximum)]
        end=[rng.randrange(lo-300,hi+300) for lo,hi in zip(minimum,maximum)]
        if index%8==0:
            start=[rng.choice((lo-1,lo,hi-1,hi)) for lo,hi in zip(minimum,maximum)]
        if index%8==1:end=start.copy()
        if index%8==2:
            end=start.copy();end[index%3]=minimum[index%3]-50
        fields=((0x6469,0x6476),(0x64b0,0x64a2),(0x6493,0x6486))
        flags=0
        for axis,(a,b) in enumerate(fields):
            patch(a,min(start[axis],end[axis]));patch(b,max(start[axis],end[axis]))
            if end[axis]>=start[axis]:flags|=(4,1,2)[axis]
        h.write(0x611a,bytes([flags]));h.write(0x6064,b'\xff')
        h.setreg('DS',0x1000);h.setreg('SI',0x8000)
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        hit=False;h.call(0x607a)
        h.call(0x6705)
        signed=lambda value:value-65536 if value&32768 else value
        result=[signed(h.getreg('DX')),signed(h.getreg('BX')),signed(h.getreg('CX'))//8]
        cases.append((minimum,maximum,start,end,int(hit),result))
    lines=['#pragma once','','// Generated by tools/generate_collision_sweep_reference.py; original 60D4–6704',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           'struct collision_sweep_sample { std::array<int, 3> minimum, maximum, start, end; bool hit; std::array<int, 3> result; };',
           f'inline constexpr std::array<collision_sweep_sample, {len(cases)}> collision_sweep_samples{{{{']
    for minimum,maximum,start,end,hit,result in cases:
        fmt=lambda a:'{'+', '.join(map(str,a))+'}'
        lines.append('  {'+', '.join([fmt(minimum),fmt(maximum),fmt(start),fmt(end),'true' if hit else 'false',fmt(result)])+'},')
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/collision_sweep_samples.h').write_text('\n'.join(lines))
    print('Captured',len(cases),'native sweeps;',sum(c[4] for c in cases),'hits.')


if __name__=='__main__':main()
