#!/usr/bin/env python3
"""Capture native B20E caption backing strips and glyph coverage."""
import argparse
import hashlib
from pathlib import Path
import struct
from unicorn import Uc, UC_ARCH_X86, UC_MODE_16, UC_HOOK_MEM_WRITE, UC_HOOK_INSN, UC_HOOK_CODE
from unicorn.x86_const import *
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    root=parser.parse_args().workspace
    image=(root/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(image).hexdigest()==IMAGE_SHA256
    fonts=(root/'analysis/resources/00_029.bin').read_bytes()
    cpu=Uc(UC_ARCH_X86,UC_MODE_16);cpu.mem_map(0,0x100000)
    cpu.mem_write(0x10000,image);cpu.mem_write(0x62978,fonts)
    cpu.mem_write(0x10000,struct.pack('<256H',*(i*256 for i in range(256))))
    cpu.mem_write(0x1fdf4,struct.pack('<H',0x5000))
    mask=[0];glyph=[False];pixels=bytearray([7]*76800)
    def output(cpu,port,size,value,data):
        if port==0x3c5:mask[0]=value
    def write(cpu,access,address,size,value,data):
        for at in range(address,address+size):
            off=at-0x50000
            if off<0 or off>=0x10000:continue
            for plane in range(4):
                x=(off%256)*4+plane;y=off//256
                if x<320 and y<240 and mask[0]&(1<<plane):
                    pixels[y*320+x]=(24 if mask[0]&(16<<plane) else 18) if glyph[0] else 0
    def code(cpu,address,size,data):
        if address==0x1e1fe:glyph[0]=True
        if address==0x1b29f:glyph[0]=False
        if address==0x1e11f:
            # Font colour/latch setup is represented by the two captured coverage colours.
            sp=cpu.reg_read(UC_X86_REG_SP)
            cpu.reg_write(UC_X86_REG_IP,int.from_bytes(cpu.mem_read(0x60000+sp,2),'little'))
            cpu.reg_write(UC_X86_REG_SP,sp+2)
    cpu.hook_add(UC_HOOK_INSN,output,None,1,0,UC_X86_INS_OUT)
    cpu.hook_add(UC_HOOK_MEM_WRITE,write);cpu.hook_add(UC_HOOK_CODE,code)
    def call(entry,registers={}):
        for reg,value in {UC_X86_REG_CS:0x1000,UC_X86_REG_DS:0x1000,UC_X86_REG_SS:0x6000,
          UC_X86_REG_SP:0xfffc,UC_X86_REG_EFLAGS:2,**registers}.items():cpu.reg_write(reg,value)
        cpu.mem_write(0x6fffc,b'\x00\xf0');cpu.emu_start(0x10000+entry,0x1f000,count=100000)
        assert cpu.reg_read(UC_X86_REG_IP)==0xf000
    rows=[]
    text=b'Return to base.'
    for face,(offset,count,spacing) in enumerate([(0,107,0x90),(0x226a,97,0x42),(0x3758,96,0x42)]):
        call(0xe29c,{UC_X86_REG_AX:0x2978+offset,UC_X86_REG_DX:spacing*256+count,UC_X86_REG_DI:0x6000})
        for x,y,width in [(12,231,120),(99,229,123),(42,48,237),(12,231,297),(13,229,120),(14,229,121),(15,229,122)]:
            cpu.mem_write(0x102fc,bytes(30))
            cpu.mem_write(0x10306,struct.pack('<5H',width//2,x,0xe800,0x1000,1000))
            cpu.mem_write(0x1e800,bytes([len(text)])+text)
            cpu.mem_write(0x1b229,struct.pack('<H',y));cpu.mem_write(0x1b240,struct.pack('<H',0x1812));cpu.mem_write(0x1b264,b'\0')
            cpu.ctl_remove_cache(0x10000,0x20000)
            pixels[:]=bytes([7]*76800);glyph[0]=False;call(0xb20e)
            fingerprint=0xcbf29ce484222325
            for value in pixels:fingerprint=((fingerprint^value)*0x100000001b3)&((1<<64)-1)
            rows.append([face,x,y,width,fingerprint])
    lines=['#pragma once','','// Generated by tools/generate_message_display_reference.py; native B20E rectangles and E1FE coverage',
      '// Colour latch setup E11F is substituted; coverage colours are 24/18, untouched pixels 7.',
      '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','#include <cstdint>','','namespace darker::test_reference {','',
      'struct message_display_sample { unsigned int face, x, y, width; uint64_t fingerprint; };',
      f'inline constexpr std::array<message_display_sample,{len(rows)}> message_display_samples{{{{']
    lines += ['  {'+', '.join(map(str,r[:4]))+f', 0x{r[4]:016x}'+'},' for r in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/message_display_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} native caption frames.')


if __name__=='__main__':main()
