#!/usr/bin/env python3
"""Capture complete native city/terrain sweeps against original building models."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from verify_player_collisions import setup
    image=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest()!=IMAGE_SHA256:raise ValueError('Unsupported unpacked executable')
    cases=[]
    for slot in (30,31,32):
        h,parsed,tail=setup(slot)
        h.write(0x2e10,bytes([0x40 if slot==30 else 0xc0]));h.write(0x60c3,struct.pack('<H',12));h.write(0x652d,struct.pack('<H',10))
        for kind in parsed['types']:
            for state in (0,32,128):
                for sample in range(8):
                    height=(100,400,1000,2400)[sample//2]
                    start=[20*256+128,20*256+128,height]
                    end=start.copy();axis=sample%2
                    start[axis]=19*256+128;end[axis]=21*256+128
                    if sample%3==0:start,end=end,start
                    if sample==7:end[2]=0
                    h.cpu.mem_write(0x61428,bytes([kind['type'],state]))
                    for reg,value in zip(('AX','BX','CX','DX','DI','BP'),start[:2]+end[:2]+[start[2]//2,end[2]//2]):h.setreg(reg,value)
                    h.setreg('DS',0x1000);h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
                    h.call(0x6527)
                    hit=2 if h.getreg('EFLAGS')&1 else 1 if h.getreg('AX') else 0
                    category=h.read(0x6064)[0] if hit==2 else 0
                    h.call(0x6705)
                    result=[h.getreg(reg) for reg in ('DX','BX','CX')] if hit else end
                    cases.append([slot,kind['type'],state,start,end,hit,category,result])
        print('Captured bank',slot,flush=True)
    lines=['#pragma once','','// Generated by tools/generate_city_sweep_reference.py; native 6527 city/terrain sweep',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           'struct city_sweep_sample { unsigned int slot, type, state; std::array<int, 3> start, end; unsigned int hit, category; std::array<int, 3> result; };',
           f'inline constexpr std::array<city_sweep_sample, {len(cases)}> city_sweep_samples{{{{']
    fmt=lambda a:'{'+', '.join(map(str,a))+'}'
    for slot,kind,state,start,end,hit,category,result in cases:
        lines.append('  {'+', '.join([str(slot),str(kind),str(state),fmt(start),fmt(end),str(hit),str(category),fmt(result)])+'},')
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/city_sweep_samples.h').write_text('\n'.join(lines))


if __name__=='__main__':main()
