#!/usr/bin/env python3
"""Capture native spatial admission, Doppler and enemy gun endpoint records."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256

p=argparse.ArgumentParser(description=__doc__);p.add_argument('workspace',type=Path);a=p.parse_args()
root=a.workspace.resolve();sys.path.insert(0,str(root/'tools'))
from trace_hidden_commands import Harness
b=(root/'analysis/unpacked/image.bin').read_bytes();assert hashlib.sha256(b).hexdigest()==IMAGE_SHA256
class Probe(Harness):
    def hook(self,cpu,address,size,data):
        off=address-self.BASE
        if off in (0x34e8,0x351f,0x3520,0x39e5):
            self.result=self.getreg('AX') if off==0x39e5 else self.getreg('SI') if off==0x34e8 else -1
            self.setreg('IP',self.RETURN);return
        super().hook(cpu,address,size,data)
h=Probe(b);h.write(0x9c4a,b[0x944a:0x964a]);rng=random.Random(0x3488)
lines=['#pragma once','','// Generated by tools/generate_world_sound_reference.py; native 3488/3ACD/39BA/6730', '// Image SHA-256: '+IMAGE_SHA256,'#include <array>','namespace darker::test_reference {']
def table(name,rows):
    lines.append(f'inline std::array<std::array<int, {len(rows[0])}>, {len(rows)}> constexpr {name}{{{{')
    lines.extend('  {'+', '.join(str(x) for x in row)+'},' for row in rows);lines.append('}};')
rows=[]
for i in range(512):
    listener=[rng.randrange(65536) for _ in range(3)]
    source=[(v+rng.randrange(-4096,4096))&65535 for v in listener]
    if i%7==0:source[2]=(listener[2]+32768)&65535
    level=rng.randrange(65536);flags=rng.choice([0,1,2,5])
    for at,value in zip([0x2700,0x271b,0x2e36],listener):h.write(at,struct.pack('<H',value))
    h.write(0x348a,struct.pack('<H',0x6000));h.write(0x3497,bytes([flags]));h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
    for r,v in zip(['AX','BX','CX','SI'],[*source,level]):h.setreg(r,v)
    h.call(0x3488);rows.append([*source,*listener,level,flags,h.result])
table('sound_admission',rows)
rows=[]
for i in range(512):
    heading,pitch,target_heading,target_pitch=[rng.randrange(65536) for _ in range(4)];speed=rng.randrange(2000)
    obj=bytearray(112);struct.pack_into('<2H',obj,0x2a,heading,pitch);struct.pack_into('<H',obj,0x3e,speed)
    h.cpu.mem_write(h.STACK+0xda00,bytes(obj));h.setreg('BP',0xda00);h.setreg('CX',target_pitch);h.setreg('DI',target_heading);h.call(0x3acd)
    rows.append([heading,pitch,speed,target_heading,target_pitch,h.getreg('AX')])
table('sound_velocity',rows)
rows=[]
for i in range(256):
    delta=[rng.randrange(-2000,2000) for _ in range(3)];pitch=rng.randrange(100,7000)
    poses=[]
    for address in [0xda00,0xdb00]:
        vals=[rng.randrange(65536),rng.randrange(65536),rng.randrange(1000)];poses+=vals
        obj=bytearray(112);struct.pack_into('<2H',obj,0x2a,*vals[:2]);struct.pack_into('<H',obj,0x3e,vals[2]);h.cpu.mem_write(h.STACK+address,bytes(obj))
    source=0xda00 if i%2 else 0
    record=bytearray(20);struct.pack_into('<H',record,2,source);struct.pack_into('<H',record,4,pitch);struct.pack_into('<3H',record,8,*(v&65535 for v in delta))
    h.cpu.mem_write(h.STACK+0x6000,bytes(record));h.write(0x39d9,struct.pack('<H',0xdb00));h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);h.setreg('BP',0x6000);h.call(0x39ba)
    rows.append([*delta,pitch,*poses,int(bool(source)),h.result])
table('sound_pitch',rows)
class Gun(Harness):
    def call(self,offset):
        self.setreg('SP',0xbffe);self.cpu.mem_write(self.STACK+0xbffe,struct.pack('<H',self.RETURN));self.setreg('EFLAGS',2)
        self.cpu.emu_start(self.BASE+offset,self.BASE+self.RETURN,count=40000)
        assert self.getreg('IP')==self.RETURN
    def hook(self,cpu,address,size,data):
        if address-self.BASE==0x8438:
            sp=self.getreg('SP');self.setreg('IP',int.from_bytes(cpu.mem_read(self.STACK+sp,2),'little'));self.setreg('SP',sp+2);self.setreg('EFLAGS',self.getreg('EFLAGS')|1);return
        super().hook(cpu,address,size,data)
rows=[]
for hit in [False,True]:
    h=Gun(b);h.call(0x1cfb);h.write(0xbf8,struct.pack('<H',65000));h.write(0x611a,b'\0')
    for at,value in [(0x6469,1234),(0x64b0,5678),(0x6493,300)]:h.write(at,struct.pack('<H',value))
    h.setreg('AX',0 if hit else 0xff00);h.call(0x6730)
    read=lambda at:int.from_bytes(h.read(at,2),'little')
    trail=read(0x6fa8);sound=read(0x6f98)
    t=bytes(h.cpu.mem_read(h.STACK+trail,34));s=bytes(h.cpu.mem_read(h.STACK+sound,20))
    rows.append([int(hit),t[7],*struct.unpack_from('<3H',t,8),struct.unpack_from('<H',s,4)[0],struct.unpack_from('<H',s,14)[0],struct.unpack_from('<H',s,16)[0],s[19],s[7]])
table('gun_effects',rows)
lines+=['} // namespace darker::test_reference',''];(Path(__file__).resolve().parents[1]/'tests/reference/world_sound_samples.h').write_text('\n'.join(lines));print('Captured spatial admission, velocity, pitch and gun endpoint fixtures.')
