#!/usr/bin/env python3
"""Validate startup/briefing/committal pixels against DF36 before emitting C++ fingerprints."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT.parent / 'tools'))
from verify_animation_frames import verify
from inspect_visual_assets import frames

rows = []
for archive, slot in ((1, 0), (1, 1), (1, 2), (1, 3), (1, 5), (3, 2)):
    data = (ROOT.parent / f'analysis/resources/{archive:02}_{slot:03}.bin').read_bytes()
    for index, frame in enumerate(frames(data)):
        verify(data[frame['offset']:])
        fingerprint = 0xcbf29ce484222325
        for x, y, colour in frame['pixels']:
            for byte in (x & 255, x >> 8, y & 255, y >> 8, colour):
                fingerprint = ((fingerprint ^ byte) * 0x100000001b3) & 0xffffffffffffffff
        rows.append(f'  {{{archive}, {slot}, {index}, {len(frame["pixels"])}, 0x{fingerprint:016x}ULL}},')
output = '''#pragma once
#include <array>
#include <cstdint>

// Generated by tools/generate_presentation_reference.py after DF36 pixel comparisons.
namespace darker::test_reference {
struct presentation_sample { unsigned int archive, slot, frame, pixels; uint64_t fingerprint; };
inline constexpr auto presentation_samples = std::to_array<presentation_sample>({
''' + '\n'.join(rows) + '\n});\n} // namespace darker::test_reference\n'
(ROOT / 'tests/reference/presentation_samples.h').write_text(output)
print(f'{len(rows)} complete animation frames verified against native DF36.')
