#!/usr/bin/env python3
"""Capture driven angular response and exhaustive native angle-fold fingerprints."""
import argparse
import hashlib
from pathlib import Path
import random
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    native = Harness(raw)
    rng = random.Random(0x83d4)
    cases = []
    for entry in (0x83df, 0x83d4):
        vectors = [(r, g, d, t) for r in (0, 1, 65535, 32767, 32768) for t in (0, 1, 8, 127, 128, 255, 32768, 65535)
                   for g, d in ((256, 0), (257, 65535), (65535, 32768))]
        vectors += [tuple(rng.randrange(65536) for _ in range(4)) for _ in range(200)]
        for rate, gain, drive, step in vectors:
            for register, value in [('SI', rate), ('AX', gain), ('DX', drive), ('CX', step)]:
                native.setreg(register, value)
            native.call(entry)
            cases.append([entry, rate, gain, drive, step, native.getreg('SI'), native.getreg('AX'), native.getreg('CX')])
    fingerprint = 0xcbf29ce484222325
    for angle in range(65536):
        native.setreg('AX', angle)
        native.call(0x83a4)
        folded = native.getreg('DI')
        for register, value in [('DI', 0x1234), ('BX', angle), ('CX', 0x5678)]:
            native.setreg(register, value)
        native.call(0x23a0)
        for value in [folded] + [native.getreg(r) for r in ('DI', 'BX', 'CX')]:
            for byte in (value & 255, value >> 8):
                fingerprint = ((fingerprint ^ byte) * 0x100000001b3) & ((1 << 64)-1)
    lines = ['#pragma once', '', '// Generated by tools/generate_angular_motion_reference.py; native 83DF, 83D4, 83A4 and 23A0',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct angular_motion_sample { int entry, rate, gain, drive, step, result_rate, delta, result_step; };',
             f'inline constexpr std::array<angular_motion_sample, {len(cases)}> angular_motion_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row)) + '},' for row in cases]
    lines += ['}};', '', f'inline constexpr std::uint64_t angle_fold_fingerprint{{0x{fingerprint:016x}}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/angular_motion_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} angular responses and both folds for all 65536 angles.')


if __name__ == '__main__':
    main()
