#!/usr/bin/env python3
"""Capture native aircraft warning ranking and brightness at 8A58 and 574F."""
import argparse
from pathlib import Path
import random
import struct
import sys

root = argparse.ArgumentParser(description=__doc__)
root.add_argument('workspace', type=Path)
workspace = root.parse_args().workspace.resolve()
sys.path.insert(0, str(workspace / 'tools'))
from trace_hidden_commands import Harness

h = Harness((workspace / 'analysis/unpacked/image.bin').read_bytes())
h.setreg('BP', 0x1000)
h.write(0xfdec, struct.pack('<H', 0x1000))
rng = random.Random(0x8a58)
rows = []
for case in range(128):
    before = sorted([rng.randrange(65) for _ in range(4)], reverse=True)
    heading, pitch = rng.randrange(65536), rng.randrange(65536)
    desired_heading = (heading + rng.randrange(-16384,16385)) & 65535
    desired_pitch = (pitch + rng.randrange(-8192,8193)) & 65535
    distance = rng.choice([0,255,256,2815,2816,3072])
    target = 0xd986 if case % 7 else 0xd9f6
    h.write(0x576a, bytes(before))
    h.write(0x89b5, bytes([distance >> 8]))
    h.write(0x8c37, struct.pack('<H', desired_heading))
    h.write(0x8c29, struct.pack('<H', desired_pitch))
    h.cpu.mem_write(h.STACK + 0x102a, struct.pack('<HH',heading,pitch))
    h.cpu.mem_write(h.STACK + 0x1048, struct.pack('<H',target))
    h.call(0x8a58)
    after = list(h.read(0x576a,4))
    h.call(0x574f)
    levels = list(h.read(0x4547,4))
    rows.append((before,[heading,pitch,desired_heading,desired_pitch,distance,target],after,levels))
lines = ['#pragma once', '', '// Generated by generate_threat_reference.py from native 8A58 and 574F.',
         '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
         'struct threat_sample {', '  std::array<std::uint8_t,4> before;',
         '  std::array<std::uint16_t,6> input;', '  std::array<std::uint8_t,4> after;',
         '  std::array<std::uint8_t,4> levels;', '};', '',
         'inline constexpr std::array<threat_sample,128> threat_samples{{']
for row in rows:
    lines.append('  {' + ', '.join('{' + ','.join(map(str,part)) + '}' for part in row) + '},')
lines += ['}};', '', '} // namespace darker::test_reference', '']
(Path(__file__).resolve().parents[1] / 'tests/reference/threat_samples.h').write_text('\n'.join(lines))
print('Captured 128 native threat ranking and brightness cases.')
