#!/usr/bin/env python3
"""Capture original animated, line and disc model streams in both projection paths."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256
from native_flat_model import render, fingerprint


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from inspect_city import geometry_bank
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    cases = []
    for slot, types in ((30, (1, 11, 17, 21, 65, 101, 120, 121, 122, 123)), (31, (41,))):
        data = (args.workspace/f'analysis/resources/00_{slot:03}.bin').read_bytes()
        bank = geometry_bank(data, slot)
        pool = data[bank['pool_start']:bank['tail_start']]
        for heading in (8192, 40960):
            native = Harness(image)
            native.write(0x9c4a, image[0x944a:0x964a])
            for register, angle in [('DI', heading), ('BX', 61440), ('CX', 0)]:
                native.setreg(register, (((angle+15)&65535)>>6)*2)
            native.call(0x1d63)
            coefficients = [struct.unpack('<h', native.read(at, 2))[0] for at in
                            (0xfd05, 0xfd12, 0xfd1f, 0xfd31, 0xfd3e, 0xfd4b, 0xfd5d, 0xfd6a, 0xfd77)]
            for gate, clock in ((0, 0), (32768, 341), (59392, 1023), (65535, 1710)):
                source = Harness(image)
                source.write(0xbf8, struct.pack('<H', clock))
                source.call(0xdb1a)
                parameters = [0]*256
                parameters[0] = gate
                parameters[9:15] = struct.unpack('<6h', source.cpu.mem_read(source.STACK+0x7947, 12))
                for kind in types:
                    for near, depth in ((False, 2048), (True, 64)):
                        pixels = render(Harness, image, pool, bank['types'][kind-1]['geometry_pool_offset'], coefficients,
                                        [0, 11, 0, 19, depth, 83], [160, 84], list(range(28)), 17, bottom=168,
                                        near=near, parameters=parameters)
                        cases.append((slot, kind, heading, gate, clock, near, fingerprint(pixels)))
        print(f'Bank {slot}: native effect models captured', flush=True)
    lines = ['#pragma once', '', '// Generated by tools/generate_model_effect_reference.py; native complete effect models',
             '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct model_effect_sample { unsigned int slot, type, heading, gate, clock; bool near; std::uint64_t fingerprint; };',
             f'inline constexpr std::array<model_effect_sample, {len(cases)}> model_effect_samples{{{{']
    lines += ['  {'+', '.join(map(str, row[:5]))+', '+str(row[5]).lower()+f', 0x{row[6]:016x}'+'},' for row in cases]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/model_effect_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} complete model effect frames.')


if __name__ == '__main__':
    main()
