#!/usr/bin/env python3
"""Recover HUD mask constants from the supported executable, without embedding artwork."""
import argparse
import hashlib
from pathlib import Path
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('image', type=Path)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1] / 'src/graphics/cockpit_tables.h')
    args = parser.parse_args()
    image = args.image.read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    word = lambda p: int.from_bytes(image[p:p + 2], 'little')
    point = lambda p: f'{{.x{{{image[p + 1] * 2}}}, .y{{{image[p]}}}}}'
    directories = {a: [word(a + 23 + 2 * i) for i in range(image[a])] for a in (0x4615, 0x4d70)}
    boundaries = sorted([p for entries in directories.values() for p in entries] + [0x4d70, 0x5191])
    labels = {
        0x4615: ['Altitude', 'Impact damage', 'Inner damage lights', 'Stored power cells', 'Cell charging', 'Incoming power', 'Weapon charge', 'Engine light', 'Nayas receiver'],
        0x4d70: ['Low altitude', 'Directional shields', 'Engine output', 'Selected weapon reserve'],
    }
    lines = ['#pragma once', '', '// Generated by tools/generate_cockpit_tables.py; do not edit by hand',
             '// Source image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '#include "graphics/cockpit.h"', '',
             'namespace darker::graphics {', '']
    total = 0
    for directory, pointers in directories.items():
        for pointer in pointers:
            end = next(p for p in boundaries if p > pointer)
            cursor = pointer + 4
            strips = []
            while cursor + 2 <= end and image[cursor] % 2 and cursor + 1 + image[cursor] <= end:
                rows = image[cursor] // 2
                name = f'rows_{pointer:04x}_{len(strips)}'
                lines.append(f'inline std::array<mask_row, {rows}> constexpr {name}{{{{')
                for i in range(rows):
                    skip, width = image[cursor + 2 + i * 2:cursor + 4 + i * 2]
                    lines.append(f'  {{.skip{{{skip}}}, .width{{{width}}}}},')
                lines += ['}};', '']
                strips.append((image[cursor + 1], name))
                cursor += image[cursor] + 1
            # The original descriptor at 4BE6 has a two-byte tail; it is not a mask.
            if cursor != end:
                lines.append(f'// Uninterpreted tail at {cursor:04X}: {image[cursor:end].hex()}')
            lines.append(f'inline std::array<hud_strip, {len(strips)}> constexpr strips_{pointer:04x}{{{{')
            for offset, name in strips:
                lines.append(f'  {{.y_offset{{{offset}}}, .rows{{{name}}}}},')
            lines += ['}};', '']
            total += len(strips)
        lines.append(f'inline std::array<hud_component, {len(pointers)}> constexpr components_{directory:04x}{{{{')
        for i, pointer in enumerate(pointers):
            lines.append(f'  {{.address{{0x{pointer:04x}}}, .field{{0x{0x454b+i:04x}}}, .label{{"{labels[directory][i]}"}}, '
                         f'.on_source{point(pointer)}, .destination{point(pointer+2)}, .alternate_source{point(pointer-2)}, .strips{{strips_{pointer:04x}}}}},')
        lines += ['}};', '']
    assert total == 127
    for base, end, name in [(0x5227, 0x52ab, 'bearing'), (0x52e0, 0x5356, 'weapon_status')]:
        cursor = base + 2
        strips = []
        while cursor < end:
            size, offset = image[cursor:cursor + 2]
            assert size % 2 and cursor + size + 1 <= end
            rows = size // 2
            row_name = f'{name}_rows_{len(strips)}'
            lines.append(f'inline std::array<mask_row, {rows}> constexpr {row_name}{{{{')
            for i in range(rows):
                skip, width = image[cursor + 2 + 2*i:cursor + 4 + 2*i]
                lines.append(f'  {{.skip{{{skip}}}, .width{{{width}}}}},')
            lines += ['}};', '']
            strips.append((offset, row_name))
            cursor += size + 1
        assert cursor == end
        lines.append(f'inline pixel_position constexpr {name}_destination{point(base)};')
        lines.append(f'inline std::array<hud_strip, {len(strips)}> constexpr {name}_strips{{{{')
        for offset, row_name in strips:
            lines.append(f'  {{.y_offset{{{offset}}}, .rows{{{row_name}}}}},')
        lines += ['}};', '']
    lines.append('inline std::array<pixel_position, 4> constexpr weapon_status_sources{{')
    for p in range(0x5356, 0x535e, 2):
        lines.append('  ' + point(p) + ',')
    lines += ['}};', '', '// Signed trigonometric words at 944A; no floating-point regeneration',
              'inline std::array<std::int16_t, 1024> constexpr original_sine{']
    values = [int.from_bytes(image[p:p+2], 'little', signed=True) for p in range(0x944a, 0x9c4a, 2)]
    for i in range(0, 1024, 16):
        lines.append('  ' + ', '.join(map(str, values[i:i+16])) + ',')
    lines += ['};', '', '// Compass paired signed-byte offsets at 53DD',
              'inline std::array<pixel_position, 38> constexpr compass_offsets{{']
    for p in range(0x53dd, 0x5429, 2):
        x, y = (int.from_bytes(image[q:q+1], 'little', signed=True) for q in (p, p+1))
        lines.append(f'  {{.x{{{x}}}, .y{{{y}}}}},')
    lines += ['}};', '', 'inline std::array<std::uint8_t, 3> constexpr ring_steps{' + ', '.join(map(str, image[0x5e16:0x5e19])) + '};',
              'inline std::array<std::uint8_t, 3> constexpr ring_capacities{' + ', '.join(map(str, image[0x5e19:0x5e1c])) + '};',
              'inline std::array<mask_row, 4> constexpr ring_mask{{']
    for p in range(0x6010, 0x6018, 2):
        lines.append(f'  {{.skip{{{image[p]}}}, .width{{{image[p+1]}}}}},')
    lines += ['}};', '']
    for name, start, end in [('small', 0x5fcc, 0x5fdd), ('large', 0x5fdd, 0x5fea), ('skimma', 0x5fea, 0x6009)]:
        lines.append(f'inline std::array<std::uint8_t, {end-start}> constexpr marker_{name}' + '{' + ', '.join(f'0x{value:02x}' for value in image[start:end]) + '};')
    lines.append('inline std::array<std::uint8_t, 101> constexpr attitude_outline{' + ', '.join(f'0x{value:02x}' for value in image[0x5f67:0x5fcc]) + '};')
    lines += ['', '} // namespace darker::graphics', '']
    args.output.write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
