#!/usr/bin/env python3
"""Capture original-pack flat models through the native drawing interpreter."""
import argparse
import hashlib
from pathlib import Path
import sys
from generate_resource_directory import IMAGE_SHA256
from native_flat_model import render, fingerprint


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from inspect_city import geometry_bank
    from extract_models import Model
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    supported = {1, 2, 3, 13, 0x0e, 0x0f, 0x11, 0x3e, 0x4d, 0x2c, 0x25, 0x52, 0x56, 0x5a, 0x67, 0x6b, 0x6f,
                 0x5e, 0x61, 0x64, 0x73, 0x76, 0x79, 0x7c, 0x7f, 0x85, 0x88, 0x8e, 0x91, 0x94, 0x97, 0x16, 0x1a}
    # Controlled matrices exercise both sides and oblique faces; camera setup is tested separately.
    views = [(16384, 4096, 0, 4096, -4096, 0, 0, 16384, 0),
             (-16384, -4096, 0, 4096, 4096, 0, 0, 16384, 0)]
    cases = []
    for slot in (30, 31, 32):
        data = (args.workspace/f'analysis/resources/00_{slot:03}.bin').read_bytes()
        bank = geometry_bank(data, slot)
        pool = data[bank['pool_start']:bank['tail_start']]
        for entry in bank['types']:
            model = Model(pool)
            model.run(entry['geometry_pool_offset']+11)
            if not model.opcodes <= supported or not model.faces:
                continue
            for view, axes in enumerate(views):
                try:
                    pixels = render(Harness, image, pool, entry['geometry_pool_offset'], axes,
                                    [0, 11, 0, 19, 1024, 0], [160, 120], list(range(28)), 17)
                except ValueError as error:
                    if not str(error).startswith('Non-flat command'):
                        raise
                    print(f'Skipping bank {slot}, type {entry["type"]}, view {view}: {error}', flush=True)
                    continue
                cases.append((slot, entry['type'], view, fingerprint(pixels)))
        print(f'Bank {slot}: {len(cases)} cumulative reference frames', flush=True)
    lines = ['#pragma once', '', '// Generated by tools/generate_original_model_reference.py; native original-pack flat drawing',
             '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct original_model_sample { unsigned int slot, type, view; std::uint64_t fingerprint; };',
             f'inline constexpr std::array<original_model_sample, {len(cases)}> original_model_samples{{{{']
    lines += ['  {'+f'{slot}, {kind}, {view}, 0x{value:016x}'+'},' for slot, kind, view, value in cases]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/original_model_samples.h').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
