#!/usr/bin/env python3
"""Capture native script target assignments including deadline and flag mutations."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('workspace',type=Path);args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    raw=(args.workspace/'analysis/unpacked/image.bin').read_bytes();assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    h=Harness(raw);rng=random.Random(0xc2aa);rows=[]
    for opcode in range(7):
        for case in range(128):
            clock=rng.randrange(65536);flags=rng.randrange(256);cell=rng.randrange(65536);target=rng.randrange(65536)
            operand=rng.randrange(32768) if opcode<2 else rng.randrange(100)
            interval=rng.randrange(1,100)
            program=bytes([opcode])+(struct.pack('<H',operand) if opcode<2 else bytes([operand]) if opcode<4 else b'')+b'\x23'
            obj=bytearray(112);obj[7]=flags;obj[9]=cell&255;obj[11]=cell>>8
            struct.pack_into('<H',obj,0x4a,target);struct.pack_into('<H',obj,0x58,0xf000);struct.pack_into('<H',obj,0x5e,clock)
            h.cpu.mem_write(h.STACK+0xda00,bytes(obj));h.write(0xf002,bytes([interval]))
            # F002 is the interpreter multiplier; use a separate program to avoid aliasing it.
            h.write(0xe800,program);h.cpu.mem_write(h.STACK+0xda58,struct.pack('<H',0xe800))
            h.setreg('BP',0xda00);h.setreg('BX',clock);h.call(0xbf97)
            obj=bytes(h.cpu.mem_read(h.STACK+0xda00,112))
            rows.append([opcode,clock,flags,cell,target,operand,interval,int.from_bytes(obj[0x4a:0x4c],'little'),obj[7],
                         int.from_bytes(obj[0x5e:0x60],'little'),int.from_bytes(obj[0x58:0x5a],'little')-0xe800])
    lines=['#pragma once','','// Generated by tools/generate_script_target_reference.py; native BF97/C296–C2B9','#include <array>',
           'namespace darker::test_reference {',f'inline constexpr std::array<std::array<unsigned int,11>,{len(rows)}> script_target_samples{{{{']
    lines+=['  {'+','.join(map(str,row))+'},' for row in rows];lines+=['}};','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/script_target_samples.h').write_text('\n'.join(lines))
    print('Captured',len(rows),'native script target operations.')


if __name__=='__main__':main()
