#!/usr/bin/env python3
"""Capture complete native flat model drawing from synthetic bytecode."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256
from native_flat_model import render, fingerprint


def models():
    word = lambda value: struct.pack('<H', value & 65535)
    vertices = bytearray()
    for a, b, c in ((-180, 0, -150), (180, 0, -150), (180, 0, 150), (-180, 0, 150)):
        vertices += bytes([0x8e])+word(c)+word(a)+word(b)
    face = bytes([3, 0x7c, 0, 1, 2, 3])
    # Plain quad, explicit count, opposite winding, call/return, jump and both conditional commands.
    bodies = [vertices+face+b'\x0d', vertices+bytes([1, 3])+face[1:]+b'\x0d',
              vertices+bytes([3, 0x65, 3, 2, 1, 0, 13])]
    body = bytearray([0x3e])+word(0)+face+b'\x0d'
    body[1:3] = word(len(body)-1)
    bodies.append(body+vertices+b'\x0d')
    bodies.append(bytes([0x4d])+word(5)+bytes([0xff, 0xff, 0xff])+vertices+face+b'\x0d')
    for indices in ((0, 1, 2), (2, 1, 0)):
        bodies.append(vertices+bytes([0x16, *indices, len(face)])+face+b'\x0d')
    for threshold in (0, 1, 2, 128, 255):
        bodies.append(vertices+bytes([0x1a, threshold, len(face)])+face+b'\x0d')
    # Coordinate reuse and cursor rewrites before drawing.
    compact = bytes([0x5a, 0x85])+word(-150)+word(-180)+bytes([0x76, 0x73, 0x76])
    bodies.append(compact+face+b'\x0d')
    bodies.append(vertices+bytes([0x25])+word(0xfc00)+compact+face+b'\x0d')
    bodies.append(vertices+bytes([0x2c])+compact+face+b'\x0d')
    return [bytes(11)+body for body in bodies]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    cases = []
    for code in models():
        for mirrored in (False, True):
            for dynamic in (0, 17, 31):
                axes = [(-16384 if mirrored else 16384), 4096, 0, 4096, -4096, 0, 0, 16384, 0]
                shades = list(range(28)) if dynamic != 17 else list(reversed(range(28)))
                pixels = render(Harness, image, code, 0, axes, [0, 11, 0, 19, 256, 0], [160, 120], shades, dynamic)
                cases.append((code, mirrored, dynamic, fingerprint(pixels)))
    lines = ['#pragma once', '', '// Generated by tools/generate_model_renderer_reference.py; original complete flat drawing stream',
             '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct model_renderer_sample {', '  int size; bool mirrored; int dynamic; std::uint64_t fingerprint;',
             '  std::array<std::uint8_t, 64> code;', '};', f'inline constexpr std::array<model_renderer_sample, {len(cases)}> model_renderer_samples{{{{']
    for code, mirrored, dynamic, value in cases:
        assert len(code) <= 64
        lines.append('  {'+f'{len(code)}, {str(mirrored).lower()}, {dynamic}, 0x{value:016x}, '+'{'+', '.join(map(str, code))+'}},')
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/model_renderer_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} complete native model draws.')


if __name__ == '__main__':
    main()
