#!/usr/bin/env python3
"""Capture native map setup, city traversal, ordering and flat-mode rendering together."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256
from native_flat_model import make_renderer, fingerprint


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from inspect_city import geometry_bank
    from unicorn import UC_HOOK_CODE
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    cases = []
    locations = [(58*256+128, 73*256+128, 2048, 0, 61440), (49*256+128, 111*256, 512, 32768, 0),
                 (54*256+64, 72*256+64, 700, 8192, 0), (64*256+128, 64*256+128, 2048, 0, 61440),
                 (256, 256, 1024, 32768, 4096), (127*256, 127*256, 1024, 0, 61440)]
    for slot in (30, 31):
        data = (args.workspace/f'analysis/resources/00_{slot:03}.bin').read_bytes()
        bank = geometry_bank(data, slot)
        pool = data[bank['pool_start']:bank['tail_start']]
        layout = (args.workspace/f'analysis/resources/00_{slot+38:03}.bin').read_bytes()
        for number, (column, row, altitude, heading, pitch) in enumerate(locations):
            native = make_renderer(Harness, image)
            word = lambda at, value: native.write(at, struct.pack('<H', value & 65535))
            def call(offset):
                native.setreg('SP', 0xfffc)
                native.cpu.mem_write(0x5fffc, struct.pack('<H', 0x4400))
                native.setreg('EFLAGS', 2)
                native.cpu.emu_start(native.BASE+offset, native.BASE+0x4400, count=3000000)
                assert native.getreg('IP') == 0x4400, hex(native.getreg('IP'))
            native.cpu.mem_write(0x20000, pool)
            native.cpu.mem_write(0x60000, b''.join(bytes([kind, 0]) for kind in layout))
            native.cpu.mem_write(0x6a000, bytes([0, 0x10, 0, 0, 255, 0, 0, 0]))
            for entry in bank['types']:
                native.cpu.mem_write(0x6a000+entry['type']*8, struct.pack('<H', entry['geometry_pool_offset']+0x400)+bytes.fromhex(entry['record_hex'])[2:])
            native.write(0xf003, bytes([0 if slot == 30 else 2]))
            native.setreg('ES', 0x6000); native.setreg('AX', 0); native.setreg('CX', 0)
            call(0xbb6d)
            native.setreg('DS', 0x6000)
            call(0xbbfc)
            cells = bytes(native.cpu.mem_read(0x60000, 32768))
            native.write(0x9c4a, image[0x944a:0x964a])
            for register, angle in [('DI', heading), ('BX', pitch), ('CX', 0)]:
                native.setreg(register, (((angle+15)&65535)>>6)*2)
            call(0x26c4)
            for at, value in ((0x2700, column), (0x271b, row), (0x270c, 0), (0x2e36, altitude), (0x26ef, 15),
                              (0xfdf0, 0x6000), (0x3142, 0x1fc0), (0x30df, 0x1fe0), (0xfdec, 0x1000), (0xffec, 0x1000),
                              (0xfdf4, 0xa000), (0xfc13, 0x3515), (0xfe13, 0x32a8), (0x2d2f, 0x3515),
                              (0x2cb4, 0xf6), (0x2c63, 0x147), (0x2b1f, 0), (0x2af5, 0), (0xa296, 168),
                              (0xfccd, 160), (0xfcf1, 84), (0x2148, 160), (0x2158, 84), (0x2385, 160), (0x236f, 84),
                              (0x3057, 160), (0x307f, 160), (0x3040, 84), (0x317b, 160), (0x318a, 84)):
                word(at, value)
            native.write(0x2e10, bytes([0x40 if slot == 30 else 0xc0]))
            native.write(0, struct.pack('<240H', *[y*256 for y in range(240)]))
            for address in (0x2dc00, 0x2de00, 0x5e000):
                native.cpu.mem_write(address, bytes(range(28)))
            clock = number*341
            word(0xbf8, clock)
            call(0xdb1a)
            def shade(cpu, address, size, data):
                if address-native.BASE == 0x2ce4:
                    word(0x3385, 0xe000)
                    native.write(0x339a, b'\0')
                    native.setreg('IP', 0x2d07)
            native.cpu.hook_add(UC_HOOK_CODE, shade)
            native.cpu.ctl_remove_cache(native.BASE, native.BASE+65536)
            call(0x26ee)
            count = (native.getreg('BP')-0x8000)//24
            call(0x2c1f)
            cases.append((slot, column, row, altitude, heading, pitch, clock, count, fingerprint(cells), fingerprint(native.pixels)))
            print(slot, number, count, hex(cases[-1][-1]), flush=True)
    lines = ['#pragma once', '', '// Generated by tools/generate_city_frame_reference.py; original city setup and drawing, identity shade table',
             '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct city_frame_sample { unsigned int slot, column, row, altitude, heading, pitch, clock, count; std::uint64_t map, frame; };',
             f'inline constexpr std::array<city_frame_sample, {len(cases)}> city_frame_samples{{{{']
    lines += ['  {'+', '.join(map(str, row[:-2]))+f', 0x{row[-2]:016x}, 0x{row[-1]:016x}'+'},' for row in cases]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/city_frame_samples.h').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
