#!/usr/bin/env python3
"""Capture native city candidate order at 26EE, retaining circle spans and map-edge clipping."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    class Scan(Harness):
        def __init__(self, image):
            super().__init__(image)
            self.cells = []
        def hook(self, cpu, address, size, data):
            if address-self.BASE == 0x2a1a:
                cell = self.getreg('BX')
                self.cells.append((cell&255)//2+(cell>>8)*128)
                sp = self.getreg('SP')
                ip = int.from_bytes(cpu.mem_read(self.STACK+sp, 2), 'little')
                self.setreg('SP', sp+2)
                self.setreg('IP', ip)
                return
            super().hook(cpu, address, size, data)
        def call(self, offset):
            self.setreg('SP', 0xfefe)
            self.cpu.mem_write(self.STACK+0xfefe, struct.pack('<H', self.RETURN))
            self.setreg('EFLAGS', 2)
            self.cpu.emu_start(self.BASE+offset, self.BASE+self.RETURN, count=300000)
            assert self.getreg('IP') == self.RETURN
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    random_source = random.Random(0x26ee)
    cases = []
    for i in range(768):
        column, row = ((0, 0), (127, 127), (0, 127), (127, 0), (64, 64), (3, 126), (255, 64), (64, 255), (255, 255), (128, 64), (64, 128), (128, 128), (240, 64), (64, 240), (160, 160), (250, 3))[i%16]
        heading = (i%8)*8192 if i<96 else random_source.randrange(65536)
        pitch = (0, 8192, 16384, 24576, 32768, 40960, 49152, 57344)[(i//8)%8]
        radius = (2, 3, 8, 16, 24, 32)[(i//16)%6]
        native = Scan(image)
        word = lambda at, value: native.write(at, struct.pack('<H', value & 65535))
        native.cpu.mem_write(0x60000, b''.join(bytes([0 if cell%7 == 0 else 1, 0]) for cell in range(16384)))
        word(0xfdf0, 0x6000); word(0x3142, 0x7000)
        native.write(0xf003, b'\0'); word(0x26ef, radius)
        word(0x2700, column*256); word(0x271b, row*256); word(0x270c, 0)
        native.write(0x9c4a, image[0x944a:0x964a])
        for register, angle in [('BX', pitch), ('CX', 0), ('DI', heading)]:
            native.setreg(register, (((angle+15)&65535)>>6)*2)
        native.call(0x26c4)
        native.call(0x26ee)
        fingerprint = 0xcbf29ce484222325
        for cell in native.cells:
            for byte in (cell&255, cell>>8):
                fingerprint = ((fingerprint^byte)*0x100000001b3)&((1<<64)-1)
        cases.append((column, row, heading, pitch, radius, len(native.cells), fingerprint))
    lines = ['#pragma once', '', '// Generated by tools/generate_city_scan_reference.py; original 26C4 / 26EE',
             '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct city_scan_sample { unsigned int column, row, heading, pitch, radius, count; std::uint64_t fingerprint; };',
             f'inline constexpr std::array<city_scan_sample, {len(cases)}> city_scan_samples{{{{']
    lines += ['  {'+', '.join(map(str, row[:-1]))+f', 0x{row[-1]:016x}'+'},' for row in cases]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/city_scan_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} original city scan sequences.')


if __name__ == '__main__':
    main()
