#!/usr/bin/env python3
"""Capture the original Skimma mission-bearing indicator at 576E."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    root=parser.parse_args().workspace.resolve()
    sys.path.insert(0,str(root/'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    raw=(root/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    rng=random.Random(0x576e)
    rows=[]
    for i in range(1024):
        h=Harness(raw)
        site=rng.randrange(65536);x=rng.randrange(65536);y=rng.randrange(65536);heading=rng.randrange(65536)
        word=lambda v:struct.pack('<H',v&65535)
        h.setreg('BP',0xd986)
        for offset,value in ((8,x),(10,y),(0x2a,heading)):h.cpu.mem_write(h.STACK+0xd986+offset,word(value))
        h.write(0x576f,word(site))
        def hook(cpu,address,size,data):
            if address==h.BASE+0x579c:h.setreg('IP',h.RETURN)
        h.cpu.hook_add(UC_HOOK_CODE,hook);h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);h.call(0x576e)
        assert h.getreg('IP')==h.RETURN
        rows.append([site,x,y,heading,h.read(0x4542,1)[0]])
    lines=['#pragma once','','// Generated by tools/generate_skimma_bearing_reference.py; native 576E–579C',
      '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
      f'inline constexpr std::array<std::array<int,5>,{len(rows)}> skimma_bearing_samples{{{{']
    lines += ['  {'+', '.join(map(str,r))+'},' for r in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/skimma_bearing_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} original mission-bearing indicators.')


if __name__ == '__main__': main()
