#!/usr/bin/env python3
"""Recover the native integer direction lookup used by 927F."""
import argparse
import hashlib
from pathlib import Path
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('image', type=Path)
    args = parser.parse_args()
    image = args.image.read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    values = image[0x934a:0x944a]
    lines = ['#pragma once', '', '// Generated by tools/generate_direction_table.py; original bytes at 934A',
             '// Source image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '',
             'namespace darker::maths {', '', 'inline std::array<std::uint8_t, 256> constexpr direction_table{']
    lines += ['  ' + ', '.join(map(str, values[i:i+16])) + ',' for i in range(0, 256, 16)]
    lines += ['};', '', '} // namespace darker::maths', '']
    (Path(__file__).resolve().parents[1] / 'src/maths/direction_table.h').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
