#!/usr/bin/env python3
"""Capture native opcode 08's distance wait and delayed actor retirement."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    root = parser.parse_args().workspace.resolve()
    sys.path.insert(0,str(root/'tools'))
    from trace_hidden_commands import Harness
    raw = (root/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    h = Harness(raw)
    rng = random.Random(0xc30a)
    rows = []
    for i in range(512):
        x,y = rng.randrange(256),rng.randrange(256)
        px = (x + rng.choice((0,1,35,36,37,128,255))) & 255
        py = (y + rng.choice((0,0,0,1,35,36,128,255))) & 255
        flags,clock,interval = rng.randrange(256),rng.randrange(65536),rng.randrange(1,100)
        obj = bytearray(112)
        obj[7],obj[9],obj[11] = flags,x,y
        struct.pack_into('<H',obj,0x58,0xe800)
        struct.pack_into('<H',obj,0x5e,clock)
        struct.pack_into('<H',obj,0x66,0x8823)
        struct.pack_into('<H',obj,0x68,0x1234)
        h.cpu.mem_write(h.STACK+0xda00,bytes(obj))
        h.cpu.mem_write(h.STACK+0xd98f,bytes([px]))
        h.cpu.mem_write(h.STACK+0xd991,bytes([py]))
        h.write(0xe800,b'\x08\x23')
        h.write(0xf002,bytes([interval]))
        h.write(0xbf8,struct.pack('<H',clock))
        h.setreg('BP',0xda00)
        h.setreg('BX',clock)
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        h.call(0xbf97)
        assert h.getreg('IP') == h.RETURN
        obj = bytes(h.cpu.mem_read(h.STACK+0xda00,112))
        get = lambda at:int.from_bytes(obj[at:at+2],'little')
        rows.append([x,y,px,py,flags,clock,interval,obj[7],get(0x58)==0xc50f,get(0x5e),get(0x66),get(0x68)])
    lines = ['#pragma once','','// Generated by generate_actor_retirement_reference.py; native BF97/C30A/8432.',
             '#include <array>','','namespace darker::test_reference {','',
             f'inline constexpr std::array<std::array<unsigned int,12>,{len(rows)}> actor_retirement_samples{{{{']
    lines += ['  {'+','.join(str(int(v)) for v in row)+'},' for row in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/actor_retirement_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} native retirement waits and removals.')


if __name__ == '__main__':
    main()
