#!/usr/bin/env python3
"""Capture native effect motion, sprite selection and ordered ring projection."""
import argparse
import hashlib
import json
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256

p=argparse.ArgumentParser(description=__doc__)
p.add_argument('workspace',type=Path)
a=p.parse_args();root=a.workspace.resolve()
sys.path.insert(0,str(root/'tools'))
from trace_hidden_commands import Harness
from verify_effect_projection import Project
b=(root/'analysis/unpacked/image.bin').read_bytes()
assert hashlib.sha256(b).hexdigest()==IMAGE_SHA256
lines=['#pragma once','','// Generated by tools/generate_effect_reference.py; original 689F/6AA6/6CD8', '// Image SHA-256: '+IMAGE_SHA256,'#include <array>','#include <cstdint>','namespace darker::test_reference {']
def table(name,rows):
    lines.append(f'inline std::array<std::array<int64_t, {len(rows[0])}>, {len(rows)}> constexpr {name}{{{{')
    lines.extend('  {'+', '.join(str(x) for x in row)+'},' for row in rows)
    lines.append('}};')
# Re-run native projection, using the established variety of synthetic inputs.
cases=json.loads((root/'analysis/interface/effects/projection-verification.json').read_text())['cases']
h=Project();rows=[]
for case in cases:
    v=case['input'];h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);points=h.draw(v)
    digest=2166136261
    for point in points:
        for x in point: digest=((digest^(x&65535))*16777619)&0xffffffff
    rows.append([v['radius'],v['angle'],v['sampling'],*v['centre'],*(x for pair in v['basis'] for x in pair),len(points),digest])
table('effect_projection',rows)
class Motion(Harness):
    def hook(self,cpu,address,size,data):
        if address-self.BASE==0x6d00:self.setreg('IP',self.RETURN);return
        super().hook(cpu,address,size,data)
h=Motion(b);rng=random.Random(0x6cd8);rows=[]
for _ in range(512):
    v=[rng.randrange(65536),rng.randrange(256),rng.randrange(65536),rng.randrange(65536),*(rng.randrange(-128,128) for _ in range(3)),rng.randrange(65536),rng.randrange(256)]
    blob=bytearray(46);blob[6]=v[1]
    for off,val in [(12,v[0]),(0x22,v[2]),(0x24,v[3]),(0x2c,v[7])]:struct.pack_into('<H',blob,off,val)
    blob[0x2a]=v[4]&255;blob[0x2b]=v[5]&255;blob[0x29]=v[6]&255
    h.cpu.mem_write(h.STACK+0x6000,bytes(blob));h.setreg('BP',0x6000);h.setreg('BX',v[7]);h.setreg('CX',v[8]);h.call(0x6cd8)
    after=bytes(h.cpu.mem_read(h.STACK+0x6000,46))
    rows.append(v+[int.from_bytes(after[12:14],'little'),after[6],int.from_bytes(after[0x22:0x24],'little'),int.from_bytes(after[0x24:0x26],'little')])
table('effect_motion',rows)
class Selector(Harness):
    def hook(self,cpu,address,size,data):
        if address-self.BASE==0xdfa8:
            self.capture={k:self.getreg(k) for k in ('AX','BX','CX','DX','SI','DI','BP')};self.setreg('IP',self.RETURN);return
        super().hook(cpu,address,size,data)
h=Selector(b);rows=[]
for depth in [32,1752,2454,3510,4914]:
    for phase in range(22):
        for x in [158,160]:
            h.write(0x6aa7,bytes([phase]));h.write(0x6b1b,b'\0');h.write(0x6b0a,struct.pack('<H',240))
            h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
            h.setreg('AX',depth);h.setreg('DX',x);h.setreg('DI',80);h.call(0x6aa6)
            c=h.capture;expected=bytearray(320*240)
            masks=h.read(c['AX'],2*(c['BX']&255))
            for y in range(c['BX']&255):
                skip,width=masks[2*y:2*y+2]
                for col in range(skip,skip+width):
                    expected[(c['DI']+y)*320+c['DX']+col]=((c['SI']+y)*37+(c['CX']+col)*13)%255+1
            digest=2166136261
            for pixel in expected:digest=((digest^pixel)*16777619)&0xffffffff
            rows.append([depth,phase,x,digest])
table('particle_pixels',rows)
verification=json.loads((root/'analysis/interface/effects/verification.json').read_text())
table('effect_ages',[[v['flags'],v['elapsed'],v.get('phase',-1)] for v in verification['ages']])
table('effect_trails',[[v['severity'],v['random_word'],*v['position'],v['flags']] for v in verification['trails']])
lines+=['} // namespace darker::test_reference','']
(Path(__file__).resolve().parents[1]/'tests/reference/effect_samples.h').write_text('\n'.join(lines))
print('Captured',len(cases),'native projections, 512 motion cases and 220 sprite selections; retained native age/trail fixtures.')
