#!/usr/bin/env python3
"""Capture native Delphi warehouse spawning and protected take-off motion."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    root = parser.parse_args().workspace.resolve()
    sys.path.insert(0,str(root/'tools'))
    from verify_player_collisions import setup
    raw = (root/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    h,bank,_ = setup(30)
    word = lambda v:struct.pack('<H',v & 65535)
    get = lambda at:int.from_bytes(h.cpu.mem_read(h.STACK+0xda00+at,2),'little')
    read = lambda at:int.from_bytes(h.read(at,2),'little')
    model = bank['special_offsets'][20]+0x400
    height = struct.unpack('<h',h.cpu.mem_read(0x70000+model+7,2))[0]
    h.write(0x1926+20*24,word(model))
    h.write(0x6202,b'\0')
    h.call(0x8eee)
    assert h.getreg('IP') == h.RETURN
    sites = struct.unpack('<8H',raw[0x8f2a:0x8f3a])
    rng = random.Random(0x8e3f)
    preparations = []
    for trial in range(32):
        before = [rng.randrange(256) for _ in sites]
        for site,value in zip(sites,before):
            h.cpu.mem_write(0x60000+(site>>8)*256+(site&255)*2,bytes([76,value]))
        h.cpu.mem_write(h.STACK+0x7935,bytes(30))
        h.setreg('DS',0x1000);h.call(0x8eee)
        assert h.getreg('IP') == h.RETURN
        after = [h.cpu.mem_read(0x60000+(site>>8)*256+(site&255)*2+1,1)[0] for site in sites]
        platforms = list(struct.unpack('<8h',h.cpu.mem_read(h.STACK+0x7937,16)))
        preparations.append(before+after+platforms)
    rows = []
    for i in range(384):
        site = sites[i % 8]
        flags = rng.choice((0,0x20,0x40,0x60,0x80,0xc0))
        px = ((site & 255) + rng.choice((0,0,4,15,16,255))) & 255
        py = ((site >> 8) + rng.choice((0,0,1,15,16,128))) & 255
        free,enabled = rng.choice((0,1,1)),rng.choice((0,1,255))
        timer = rng.choice((0,1,7,8,0x200,0x7fff,0xffff))
        clock,step,seed = rng.randrange(65536),rng.choice((1,8,32,255)),rng.randrange(65536)
        heading = rng.randrange(256)*256
        h.cpu.mem_write(0x60000,bytes(32768))
        h.cpu.mem_write(0x60000+(site>>8)*256+(site&255)*2,bytes([76,flags]))
        obj = bytearray(112)
        struct.pack_into('<H',obj,0x5a,0xe800)
        h.cpu.mem_write(h.STACK+0xda00,bytes(obj))
        h.setreg('BP',0xda00);h.setreg('BX',0x1926+20*24);h.call(0xbf41)
        h.write(0x6fd8,struct.pack('<4H',0,0,0xda00 if free else 0,0))
        h.cpu.mem_write(h.STACK+0xd98f,bytes([px]));h.cpu.mem_write(h.STACK+0xd991,bytes([py]))
        h.write(0xc52,word(timer));h.write(0xbf0,word(clock));h.write(0x92d3,word(seed))
        h.write(0x8eb0,bytes([enabled]));h.write(0x8e18,bytes([heading>>8]))
        h.setreg('DS',0x1000);h.setreg('CX',step)
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);h.call(0x8e3f)
        assert h.getreg('IP') == h.RETURN
        admitted = read(0x6fd8) != 0
        obj = bytes(h.cpu.mem_read(h.STACK+0xda00,112))
        rows.append([site,flags,px,py,free,enabled,timer,clock,step,seed,heading,admitted,
                     read(0xc52),read(0x92d3),h.read(0x8e18)[0]*256,
                     *[get(at) for at in (8,10,12,0x2a,0x2c,0x2e,0x3e,0x48,0x4a,0x62,0x66,0x68,0x5e)],obj[7],get(0x58)==0xe800])
    # The departure helper runs speed/movement before steering, unlike ordinary airborne AI.
    obj = bytearray(112)
    obj[7] = 0x50
    struct.pack_into('<3H',obj,8,21632,14328,100-height)
    struct.pack_into('<3H',obj,0x2a,0x8000,0,0)
    struct.pack_into('<H',obj,0x3e,100)
    struct.pack_into('<H',obj,0x5e,1024)
    h.cpu.mem_write(h.STACK+0xda00,bytes(obj))
    h.setreg('BP',0xda00);h.setreg('BX',0x1926+20*24);h.call(0xbf41)
    h.cpu.mem_write(h.STACK+0xda66,word(0x8ddd))
    departures = []
    for frame in range(1,129):
        h.setreg('DS',0x1000);h.setreg('BP',0xda00);h.setreg('CX',8)
        h.write(0xbf0,word(frame*8));h.call(0x8ddd)
        assert h.getreg('IP') == h.RETURN
        obj = bytes(h.cpu.mem_read(h.STACK+0xda00,112))
        departures.append([*[get(at) for at in (8,10,12,0x2a,0x2c,0x2e,0x3e,0x26,0x28,0x66)],*obj[4:7],obj[7]])
    lines = ['#pragma once','','// Generated by generate_aircraft_spawning_reference.py; native 8E3F and 8DDD.',
             '#include <array>','','namespace darker::test_reference {','']
    for name,samples in (('aircraft_site_samples',preparations),('aircraft_spawning_samples',rows),('aircraft_departure_samples',departures)):
        lines += [f'inline constexpr std::array<std::array<int,{len(samples[0])}>,{len(samples)}> {name}{{{{']
        lines += ['  {'+','.join(str(int(v)) for v in row)+'},' for row in samples]
        lines += ['}};','']
    lines += ['} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/aircraft_spawning_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} native warehouse cases and {len(departures)} take-off updates.')


if __name__ == '__main__':
    main()
