#!/usr/bin/env python3
"""Capture original intrusive object lists and random recurrence for engine tests."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    assert digest == '7599201a01aa24b7e6ad1ae4295d493821cde7c3a43b247c464522626c0380a4'
    native = Harness(raw)
    addresses = [0] + [0x6000 + i*112 for i in range(6)]
    def ssword(address, value):
        native.cpu.mem_write(native.STACK + address, struct.pack('<H', value))
    def readlink(address):
        return addresses.index(int.from_bytes(native.cpu.mem_read(native.STACK + address, 2), 'little'))
    cases = []
    for active in range(7):
        for operation, entry in enumerate((0x1c95, 0x1cbf, 0x7ab4, 0x1cd4)):
            for target in (range(1, active+1) if operation >= 2 else (0,)):
                for index in range(1, 7):
                    next_id = index+1 if index < (active if index <= active else 6) else 0
                    previous = index-1 if index <= active else index
                    ssword(addresses[index], addresses[next_id])
                    ssword(addresses[index]+2, addresses[previous])
                native.write(0x5000, struct.pack('<3H', addresses[1] if active else 0, addresses[active], addresses[active+1] if active < 6 else 0))
                native.setreg('DI', 0x5000)
                native.setreg('BP', addresses[target])
                native.call(entry)
                result = [addresses.index(native.getreg('BP'))]
                result += [addresses.index(v) for v in struct.unpack('<3H', native.read(0x5000, 6))]
                for index in range(1, 7):
                    result += [readlink(addresses[index]), readlink(addresses[index]+2)]
                cases.append((active, operation, target, result))
    random_hashes = []
    for page in range(256):
        checksum = 14695981039346656037
        for low in range(256):
            seed = page*256+low
            native.write(0x92d3, struct.pack('<H', seed))
            native.call(0x92d2)
            result = native.read(0x92d3, 2)
            assert int.from_bytes(result, 'little') == native.getreg('AX')
            for value in result:
                checksum = ((checksum ^ value)*1099511628211) & ((1 << 64)-1)
        random_hashes.append(checksum)
    lines = ['#pragma once', '', '// Generated by tools/generate_world_reference.py through native execution',
             '// Image SHA-256: ' + digest, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct object_list_sample { int active; int operation; int target; std::array<int, 16> result; };',
             f'inline constexpr std::array<object_list_sample, {len(cases)}> object_list_samples{{{{']
    lines += ['  {' + f'{active}, {operation}, {target}, ' + '{' + ', '.join(map(str, result)) + '}},' for active, operation, target, result in cases]
    lines += ['}};', '', 'inline constexpr std::array<std::uint64_t, 256> random_hashes{']
    lines += [f'  0x{value:016x}ULL,' for value in random_hashes]
    lines += ['};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/world_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} list mutations and all 65,536 random states.')


if __name__ == '__main__':
    main()
