#!/usr/bin/env python3
"""Execute native scenario list setup and incremental building-objective checks."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    h = Harness(raw)
    h.write(0xfdf0, struct.pack('<H', 0x6000)); h.write(0xc16f, b'\0')
    rng = random.Random(0xc85a)
    rows = []
    for case in range(64):
        end = 254 + case % 2
        mask = 0x20 if case % 4 < 2 else 0x60
        states = [rng.randrange(256) for _ in range(5)]
        for i, state in enumerate(states):
            h.cpu.mem_write(0x60000 + (i*2+2)*256 + (i*2+1)*2, bytes([1, state]))
        h.write(0xf000, bytes([1,2,255,3,4,5,6,end,7,8,9,10,255]))
        h.setreg('SI', 0xf000); h.setreg('DX', 0x20); h.call(0xc85a)
        pointer = int.from_bytes(h.read(0xc84f,2),'little') - 0xf000
        updated = [h.cpu.mem_read(0x60000+(i*2+2)*256+(i*2+1)*2+1,1)[0] for i in range(5)]
        h.write(0xc841,bytes([mask]));h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        steps = []
        for step in range(8):
            h.call(0xc82f)
            at = int.from_bytes(h.read(0xc84f,2),'little') - 0xf000
            h.call(0xc84e)
            steps += [at, int((h.getreg('AX') & 255) == 0)]
        rows.append([end,mask,*states,*updated,pointer,*steps])
    lines = ['#pragma once', '', '// Generated by tools/generate_scenario_world_reference.py; native C85A/C82F/C84E',
             '#include <array>', '', 'namespace darker::test_reference {', '',
             f'inline constexpr std::array<std::array<unsigned int,29>,{len(rows)}> scenario_world_samples{{{{']
    lines += ['  {' + ','.join(map(str,row)) + '},' for row in rows]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/scenario_world_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} scenario setups and 512 objective frames.')


if __name__ == '__main__':
    main()
