#!/usr/bin/env python3
"""Execute native radio coverage and the complete normal energy-tower radar loop."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    raw=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    h=Harness(raw)
    h.setreg('ES',0x6000);h.cpu.emu_start(h.BASE+0x396,h.BASE+0x3ab,count=5000)
    lookup=bytes(h.cpu.mem_read(0x6a800,256))
    h.write(0x9c4a,raw[0x944a:0x964a]);h.write(0xfdf0,struct.pack('<H',0x6000))
    pixels=[]
    def hook(cpu,address,size,data):
        if address-h.BASE==0x53cf:
            pixels.extend([h.getreg('DX'),h.getreg('DI'),h.getreg('AX')>>8])
            h.setreg('IP',int.from_bytes(cpu.mem_read(h.STACK+h.getreg('SP'),2),'little'))
            h.setreg('SP',h.getreg('SP')+2)
    h.cpu.hook_add(UC_HOOK_CODE,hook)
    rng=random.Random(0x5898);rows=[]
    for case in range(512):
        x,y=[rng.randrange(32768) for _ in range(2)]
        heading=rng.randrange(65536);disabled=rng.randrange(65536);seed=rng.randrange(256)
        underground=case%17==0
        grid=bytearray(65536)
        for cy in range(0,128,9):
            for cx in range(0,128,9):
                state=[128,0,160,255,64][(cx//9+cy//9*15+seed)%5]
                at=cy*256+cx*2;grid[at:at+2]=bytes([1,state])
        for ry,cy in enumerate((13,49,85,121)):
            for rx,cx in enumerate((13,49,85,121)):
                at=cy*256+cx*2;grid[at:at+2]=bytes([12,32 if disabled&(1<<(ry*4+rx)) else 0])
        grid[0xa000:0xa002]=struct.pack('<H',0x1000);grid[0xa800:0xa900]=lookup
        h.cpu.mem_write(0x60000,bytes(grid));h.setreg('DS',0x1000)
        h.cpu.mem_write(h.STACK+0xd98e,struct.pack('<HH',x,y))
        h.write(0x2701,bytes([x>>8]));h.write(0x271c,bytes([y>>8]));h.write(0x6202,bytes([2 if underground else 0]))
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        h.cpu.emu_start(h.BASE+0x5a75,h.BASE+0x5ab9,count=1000)
        mask=int.from_bytes(h.read(0x59c5,2),'little')
        cells=[rng.randrange(128) for _ in range(16)];admitted=[]
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        for i in range(0,16,2):
            h.setreg('AX',cells[i]+cells[i+1]*256);h.call(0x59a3)
            admitted.append(h.getreg('EFLAGS')&1)
        h.write(0x3e46,struct.pack('<H',(heading>>6)*2));pixels.clear();h.setreg('DS',0x1000)
        h.cpu.emu_start(h.BASE+0x5898,h.BASE+0x5928,count=10000)
        assert h.getreg('IP')==0x5928
        rows.append([x,y,heading,disabled,seed,int(underground),mask]+cells+admitted+[len(pixels)//3]+pixels+[0]*(75-len(pixels)))
    lines=['#pragma once','','// Generated by tools/generate_radar_beacons_reference.py; native 5A75/59A3/5898',
           '#include <array>','','namespace darker::test_reference {','',
           f'inline constexpr std::array<std::array<unsigned int,107>,{len(rows)}> radar_beacon_samples{{{{']
    assert all(len(row)==107 for row in rows)
    lines+=['  {'+','.join(map(str,row))+'},' for row in rows]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/radar_beacon_samples.h').write_text('\n'.join(lines))
    print('Captured',len(rows),'native coverage and tower radar frames.')


if __name__=='__main__':main()
