#!/usr/bin/env python3
"""Capture the original binary near-plane edge intersection, including saturation."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    random_source = random.Random(0x22b4)
    depths = [(8192, 8191), (8193, 8191), (8448, 8191), (8448, 0), (32767*256, 8191), (8192, -32000*256)]
    depths += [(random_source.randrange(8192, 20000*256), random_source.randrange(-10000*256, 8192)) for _ in range(122)]
    cases = []
    for near, far in depths:
        for amplitude in (256, 10000, 1000000, 8000000):
            inside = [random_source.randrange(-amplitude, amplitude) for _ in range(2)]+[near]
            outside = [random_source.randrange(-amplitude, amplitude) for _ in range(2)]+[far]
            origin = [random_source.randrange(-256, 256), random_source.randrange(-256, 256)]
            native = Harness(image)
            for at, value in zip((0x2385, 0x236f), origin):
                native.write(at, struct.pack('<H', value & 65535))
            for at, point in ((0xfc00, inside), (0xfc04, outside)):
                native.cpu.mem_write(0x20000+at, struct.pack('<HH', point[2]&255, (point[2]>>8)&65535))
                native.cpu.mem_write(0x20000+at-0x800, struct.pack('<i', point[0]))
                native.cpu.mem_write(0x20000+at-0x400, struct.pack('<i', point[1]))
            for register, value in [('DS', 0x2000), ('BX', 0xfc00), ('BP', 0xfc04), ('CX', near>>8), ('AX', (far>>8)&65535)]:
                native.setreg(register, value)
            native.call(0x22b4)
            signed = lambda value: (value+32768)%65536-32768
            result = [signed(native.getreg('AX')), signed(native.getreg('CX'))]
            cases.append((inside, outside, origin, result))
    lines = ['#pragma once', '', '// Generated by tools/generate_near_clip_reference.py; original 22B4',
             '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct near_clip_sample {', '  std::array<std::int32_t, 3> inside, outside;',
             '  std::array<std::int16_t, 2> origin, result;', '};',
             f'inline constexpr std::array<near_clip_sample, {len(cases)}> near_clip_samples{{{{']
    lines += ['  {'+', '.join('{'+', '.join(map(str, values))+'}' for values in row)+'},' for row in cases]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/near_clip_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} native near-plane intersections.')


if __name__ == '__main__':
    main()
