#!/usr/bin/env python3
"""Capture BE07 actor construction without substituting placement or definition helpers."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    rows = []
    rng = random.Random(0xbe07)
    for i in range(384):
        form = i % 3
        mode = rng.randrange(2 if form == 0 else 3)
        slot = rng.randrange(29) if form == 0 else rng.randrange(29, 33) if form == 1 else rng.randrange(33)
        counted = rng.randrange(2)
        heading, attributes = rng.randrange(256), rng.randrange(256)
        x, y = [rng.randrange(128) * 256 + 128 for _ in range(2)] if form != 2 else [rng.randrange(65536) for _ in range(2)]
        motion = [rng.randrange(256) for _ in range(6)]
        target = rng.choice([0, 7, 0xffff, 0xff00, 0xff01, 0xff20])
        height = rng.randrange(-4096, 4096)
        index = rng.randrange(1, 40)
        header = slot | counted * 128 | (64 if form == 2 else 0)
        placement = bytes([header])
        if form == 0:
            placement += bytes([attributes])
        placement += bytes([heading])
        if form == 2:
            placement += struct.pack('<2H', x, y)
        else:
            placement += bytes([x >> 8, y >> 8])
            if form == 0:
                placement += bytes(motion)
            placement += struct.pack('<H', target)
        h = Harness(raw)
        h.write(0xf000, placement + b'\xff' + bytes(32))
        h.write(0x3142, struct.pack('<H', 0x7000))
        h.write(0x1926 + slot * 24, struct.pack('<H', 0x400))
        h.cpu.mem_write(0x70407, struct.pack('<h', height))
        h.write(0x6202, bytes([mode]))
        h.write(0xbea7, raw[0xbdec + mode * 9 + 7:0xbdec + mode * 9 + 9])
        h.setreg('SI', 0xf000)
        h.setreg('BP', 0xda00 - 112)
        h.setreg('CX', index)
        h.call(0xbe07)
        obj = bytes(h.cpu.mem_read(h.STACK + 0xda00, 112))
        word = lambda offset: int.from_bytes(obj[offset:offset+2], 'little')
        script = word(0x58)
        checkpoint = word(0x5a)
        # Resource-backed pointers become offsets; C50F is represented as stopped.
        output = [*struct.unpack_from('<3H', obj, 8), word(0x2a), word(0x3e), obj[7], obj[0x46], obj[0x6f],
                  word(0x66), word(0x4a), word(0x62), word(0x4c), word(0x30), word(0x32), word(0x34), word(0x36),
                  *struct.unpack_from('<3H', obj, 0x38), *obj[0x50:0x56], obj[0x20], obj[0x21],
                  script - 0xf000 if script >= 0xf000 else 0, checkpoint - 0xf000 if checkpoint >= 0xf000 else 0,
                  int(script == 0xc50f), word(0x5e)]
        rows.append(([form, mode, slot, counted, heading * 256, attributes, x, y, *motion, target, height, index, len(placement)], output))
    lines = ['#pragma once', '', '// Generated by tools/generate_scenario_actor_reference.py; native BE07/BF1A/C7BF',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct scenario_actor_sample { std::array<int, 18> input; std::array<int, 31> output; };',
             'inline constexpr std::array<scenario_actor_sample, 384> scenario_actor_samples{{']
    lines += ['  {{' + ', '.join(map(str, a)) + '}, {' + ', '.join(map(str, b)) + '}},' for a, b in rows]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/scenario_actor_samples.h').write_text('\n'.join(lines))
    print('Captured 384 original actor constructors across three placement forms.')


if __name__ == '__main__':
    main()
