#!/usr/bin/env python3
"""Capture original city model selection, extent culling and drawing records."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from inspect_city import geometry_bank
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    random_source = random.Random(0x2a1a)
    cases = []
    for slot in (30, 31, 32):
        data = (args.workspace/f'analysis/resources/00_{slot:03}.bin').read_bytes()
        bank = geometry_bank(data, slot)
        pool = data[bank['pool_start']:bank['tail_start']]
        mask = image[0xbdec+9*(slot-30)+4]
        for entry in bank['types']:
            for variant in range(4):
                state = (0, 32, 128, 160)[variant]
                camera = [random_source.randrange(-8*1024, 8*1024)&65535 for _ in range(2)]+[random_source.randrange(0, 4096)]
                angles = [random_source.randrange(65536), random_source.choice((0, 4096, 61440)), 0]
                native = Harness(image)
                word = lambda at, value: native.write(at, struct.pack('<H', value & 65535))
                native.write(0x9c4a, image[0x944a:0x964a])
                for register, angle in zip(('DI', 'BX', 'CX'), angles):
                    native.setreg(register, (((angle+15)&65535)>>6)*2)
                native.call(0x1d63)
                for at, value in zip((0x2e28, 0x2e2c, 0x2e36), camera):
                    word(at, value)
                native.cpu.mem_write(0x70400, pool)
                record = bytes.fromhex(entry['record_hex'])
                native.cpu.mem_write(0x6a000+entry['type']*8, struct.pack('<H', entry['geometry_pool_offset']+0x400)+record[2:])
                native.write(0x2e10, bytes([mask*2]))
                native.cpu.ctl_remove_cache(native.BASE+0x2de1, native.BASE+0x2eab)
                word(0x2b1f, 0); word(0x2af5, 0)
                for register, value in [('DS', 0x6000), ('ES', 0x7000), ('BP', 0x8000), ('BX', 0x4080), ('AX', entry['type']|(state<<8)), ('CX', 1)]:
                    native.setreg(register, value)
                native.call(0x2a1a)
                accepted = native.getreg('BP') == 0x8018
                output = [0]*10
                if accepted:
                    result = native.cpu.mem_read(native.STACK+0x8000, 24)
                    u16 = lambda at: struct.unpack_from('<H', result, at)[0]
                    output = [u16(20)-0x400, u16(8), result[4], u16(12), result[6], u16(10), result[5], u16(14), u16(16), int(record[4] == 255)]
                cases.append(([slot, entry['type'], state, mask], camera, angles, accepted, output))
    lines = ['#pragma once', '', '// Generated by tools/generate_city_placement_reference.py; original 2A1A with original banks',
             '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct city_placement_sample {', '  std::array<unsigned int, 4> model;',
             '  std::array<std::uint16_t, 3> camera, angles;', '  bool visible;', '  std::array<std::uint16_t, 10> result;', '};',
             f'inline constexpr std::array<city_placement_sample, {len(cases)}> city_placement_samples{{{{']
    for model, camera, angles, visible, result in cases:
        groups=['{'+', '.join(map(str, a))+'}' for a in (model, camera, angles)]
        lines.append('  {'+', '.join(groups)+', '+str(visible).lower()+', {'+', '.join(map(str,result))+'}},')
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/city_placement_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} native city placements and culling decisions.')


if __name__ == '__main__':
    main()
