#!/usr/bin/env python3
"""Capture complete native craft callback plus city collision and crash response."""
import argparse
import hashlib
from pathlib import Path
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('workspace',type=Path);args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_flight_collision import trace
    image=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest()!=IMAGE_SHA256:raise ValueError('Unsupported unpacked executable')
    frames=[]
    for craft in (25,26,27):
        for kind in (11,30):
            for height in (100,400):
                for engine in (False,True):
                    run=trace(craft,kind,height,engine,False)
                    for f in run['frames']:
                        frames.append(([craft,kind,height,int(engine),f['tick']],f['after_collision'],f['velocity'],f['angles'],[f['callback'],f['building_state']]))
    lines=['#pragma once','','// Generated by tools/generate_player_flight_reference.py; native craft callback followed by 6F0F',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           'struct player_flight_sample { std::array<int, 5> input; std::array<int, 3> position; std::array<int, 2> velocity; std::array<int, 3> angles; std::array<int, 2> outcome; };',
           f'inline constexpr std::array<player_flight_sample, {len(frames)}> player_flight_samples{{{{']
    lines+=['  {'+', '.join('{'+', '.join(map(str,part))+'}' for part in case)+'},' for case in frames]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/player_flight_samples.h').write_text('\n'.join(lines))
    print('Captured',len(frames),'native integrated flight/collision frames.')


if __name__=='__main__':main()
