#!/usr/bin/env python3
"""Capture native BF97 timing, checkpoints, waits and counted-message scheduling."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from verify_mission_scheduler import Probe, IMAGE
    assert hashlib.sha256(IMAGE).hexdigest()==IMAGE_SHA256
    rows=[]
    def capture(script,now,deadline=1000,multiplier=50,checkpoint=0,coarse=0,objectives=0,counter=0,other=0,suppress=False):
        h=Probe(script,deadline,multiplier)
        h.put(0x5a,0xf100+checkpoint);h.put(0x5c,coarse)
        h.write(0xc84f,struct.pack('<H',0xf600));h.write(0xf600,b'\xff')
        h.write(0xc16f,bytes([objectives]));h.write(0xc21b,bytes([counter]));h.write(0xc221,bytes([other]))
        h.write(0xc059,struct.pack('<H',0xf400));h.write(0xf400,b'\0\x18\x03ABC')
        h.cpu.mem_write(h.STACK+h.BP+7,bytes([32 if suppress else 0]))
        h.cpu.mem_write(h.STACK+h.BP+3*112+7,bytes([counter]))
        h.write(0xfdf0,struct.pack('<H',0x3000))
        h.cpu.mem_write(0x3a000,struct.pack('<H',0x1000))
        h.cpu.mem_write(0x30000+0x1415,bytes([counter]))
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        for address in (0x304,0x30e,0x318):h.write(address,b'\0\0')
        result=h.update(now)
        stopped=result['resume']==0xc50f
        # The native stop target is executable-resident; compare it as a state, not a fake resource offset.
        resume=0 if stopped else result['resume']-0xf100
        text_cursor=int.from_bytes(h.read(0xc059,2),'little')-0xf400
        address={0x0d:0x304,0x0e:0x318}.get(script[0],0x30e)
        expiry=int.from_bytes(h.read(address,2),'little')
        rows.append((list(script),[now,deadline,multiplier,checkpoint,coarse,objectives,counter,other,int(suppress)],
                     [resume,result['deadline'],h.get(0x5a)-0xf100,h.get(0x5c),int(stopped),text_cursor,expiry,len(result['dispatches'])]))
    for deadline in (0,1,1000,32767,32768,65535):
        for delta in (-32768,-32767,-1,0,1,32767):capture(b'\x23',(deadline+delta)&65535,deadline)
    for start in (0,1000,65500):
        for late in (0,49,50,99,100,150):capture(bytes([0x22,1,0x22,1,0x23]),(start+late)&65535,start)
    for now in (0,127,128,255,256,65535,65536,0xffffff):capture(bytes([0x1a,0x23]),now,now&65535)
    for coarse in (0,100,65520):
        for delta in (15,16,17):
            now=((coarse+delta)&65535)<<8
            capture(bytes([0x1b,2,0x23]),now,now&65535,coarse=coarse)
    for multiplier in (1,50,255):
        for late in (0,1,7*multiplier,8*multiplier,16*multiplier):
            capture(bytes([0x1a,0x1e,0x23]),1000+late,multiplier=multiplier,objectives=1)
    for opcode in (0x1f,0x20):
        for count in (0,1,127,255):
            for threshold in (0,1,127,255):
                capture(bytes([opcode,threshold,0x23]),1000,counter=count,other=count)
    for opcode in (0x0c,0x0d,0x0e):
        for suppress in (False,True):
            for late in (0,2099,2100):
                capture(bytes([opcode,25,27,opcode,40,42,0x23]),1000+late,suppress=suppress)
    for now in (1000,1399,1400,1899,1900,3999,4000):
        capture(bytes.fromhex('1a1e220a0c191b0c282a23'),now,objectives=int(now<1400))
    for mask in range(256):
        value=(mask*73+19)&255
        capture(bytes([0x1c,3,mask,0x23]),1000,counter=value)
        capture(bytes([0x1d,0x15,0x14,mask,0x23]),1000,counter=value)
    capture(bytes([0x25,2,0x07,0x07,0x22,1,0x23]),1000)
    lines=['#pragma once','','// Generated by tools/generate_mission_script_reference.py; native BF97 and handlers',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           'struct mission_script_sample { std::array<int, 16> program; unsigned int size; std::array<int, 9> input; std::array<int, 8> output; };',
           f'inline constexpr std::array<mission_script_sample, {len(rows)}> mission_script_samples{{{{']
    for program,inputs,outputs in rows:
        lines.append('  {{'+', '.join(map(str,program))+'}, '+str(len(program))+', {'+', '.join(map(str,inputs))+'}, {'+', '.join(map(str,outputs))+'}},')
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/mission_script_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} native scheduler cases.')


if __name__=='__main__':main()
