#!/usr/bin/env python3
"""Execute BF41 definition expansion for original records and byte boundaries."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    native = Harness(raw)
    cases = []
    inputs = [(slot, -1, 0, model) for slot in range(33) for model in (0, 0x1234, 0xfffc)]
    inputs += [(-1, field, value, 0x4321) for field in range(4) for value in (0, 1, 127, 128, 255)]
    for slot, field, value, model in inputs:
        definition = bytearray(raw[0x1926+slot*24:0x1926+(slot+1)*24]) if slot >= 0 else bytearray(24)
        if slot < 0:
            definition[4+field] = value
            definition[2:4] = struct.pack('<H', 0xbeef)
        definition[0:2] = struct.pack('<H', model)
        native.write(0x5000, bytes(definition))
        before = bytes([0xa5])*112
        native.cpu.mem_write(native.STACK+0x6000, before)
        native.setreg('BP', 0x6000)
        native.setreg('BX', 0x5000)
        native.call(0xbf41)
        after = bytes(native.cpu.mem_read(native.STACK+0x6000, 112))
        offsets = (0x22, 0x66, 0x4c, 0x30, 0x32, 0x34, 0x36)
        expected = [int.from_bytes(after[a:a+2], 'little') for a in offsets]
        writes = [0x44, *offsets]
        assert after[0x44:0x46] == b'\0\x50'
        assert all(before[i] == after[i] for i in range(112) if all(i not in (a, a+1) for a in writes))
        cases.append([slot, field, value, model, *expected])
    lines = ['#pragma once', '', '// Generated by tools/generate_definition_reference.py using native BF41 execution',
             '// Source image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct definition_sample { int slot, field, value, model, expected_model, update, flags, angular, motion0, motion1, motion2; };',
             f'inline constexpr std::array<definition_sample, {len(cases)}> definition_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row)) + '},' for row in cases]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/definition_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} expansions; native writes confined to eight expected words.')


if __name__ == '__main__':
    main()
