#!/usr/bin/env python3
"""Capture native angular response and homing updates with target angles supplied."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    native = Harness(raw)
    responses = []
    for error in (0, 1, 0x27ff, 0x2800, 0x4000, 0x8000, 0xd7ff, 0xffff):
        for rate in (0, 1000, 0x8000, 0xffff):
            for step in (0, 1, 32, 128, 256, 65535):
                for response in (96, 2040):
                    for reg, value in [('AX', error), ('SI', rate), ('BX', response), ('CX', step)]:
                        native.setreg(reg, value)
                    native.call(0x83bf)
                    responses.append([error, rate, step, response, native.getreg('SI'), native.getreg('AX'), native.getreg('CX')])

    class Homing(Harness):
        heading = 0
        pitch = 0

        def hook(self, cpu, address, size, data):
            if address-self.BASE == 0xcc9c:
                self.setreg('DI', self.heading)
                self.setreg('DX', self.pitch)
                self.setreg('IP', 0xccdb)
                return
            super().hook(cpu, address, size, data)

    native = Homing(raw)
    native.write(0x9c4a, raw[0x944a:0x964a])
    native.write(0x5000, raw[0x1926:0x193e])
    homing = []
    for heading in (0, 1, 0x3fff, 0x4000, 0x8000, 0xc000, 0xffff):
        for pitch in (0, 0x2000, 0x8000, 0xffff):
            for step in (1, 32, 65535):
                for rate in (0, 1000, 0xffff):
                    state = bytearray(112)
                    state[4:7] = bytes([255, 127, 1])
                    state[8:14] = struct.pack('<3H', 0, 65535, 0)
                    state[0x26:0x2a] = struct.pack('<2H', rate, rate)
                    state[0x30:0x32] = struct.pack('<H', 480)
                    state[0x3e:0x40] = struct.pack('<H', 1000)
                    state[0x44:0x46] = struct.pack('<H', 0x5000)
                    native.cpu.mem_write(native.STACK+0x6000, bytes(state))
                    native.heading, native.pitch = heading, pitch
                    native.setreg('BP', 0x6000)
                    native.setreg('CX', step)
                    native.call(0xcc61)
                    result = bytes(native.cpu.mem_read(native.STACK+0x6000, 112))
                    out = [*struct.unpack('<3H', result[8:14]), *result[4:7], *struct.unpack('<5H', result[0x26:0x30]), int.from_bytes(result[0x3e:0x40], 'little')]
                    homing.append([heading, pitch, step, rate, *out])
    lines = ['#pragma once', '', '// Generated by tools/generate_steering_reference.py through native execution',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct response_sample { int error, rate, step, response, next_rate, delta, next_step; };',
             f'inline constexpr std::array<response_sample, {len(responses)}> response_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row)) + '},' for row in responses]
    lines += ['}};', '', 'struct homing_sample { int heading, pitch, step, rate; std::array<int, 12> result; };',
              f'inline constexpr std::array<homing_sample, {len(homing)}> homing_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row[:4])) + ', {' + ', '.join(map(str, row[4:])) + '}},' for row in homing]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/steering_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(responses)} angular responses and {len(homing)} homing updates.')


if __name__ == '__main__':
    main()
