#!/usr/bin/env python3
"""Recover HUD mask constants from the supported executable, without embedding artwork."""
import argparse
import hashlib
from pathlib import Path
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('image', type=Path)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1] / 'src/graphics/cockpit_tables.h')
    args = parser.parse_args()
    image = args.image.read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    word = lambda p: int.from_bytes(image[p:p + 2], 'little')
    point = lambda p: f'{{.x{{{image[p + 1] * 2}}}, .y{{{image[p]}}}}}'
    directories = {a: [word(a + 23 + 2 * i) for i in range(image[a])] for a in (0x4615, 0x4d70)}
    boundaries = sorted([p for entries in directories.values() for p in entries] + [0x4d70, 0x5191])
    labels = {
        0x4615: ['Altitude', 'Impact damage', 'Inner damage lights', 'Stored power cells', 'Cell charging', 'Incoming power', 'Weapon charge', 'Engine light', 'Nayas receiver'],
        0x4d70: ['Low altitude', 'Directional shields', 'Engine output', 'Selected weapon reserve'],
    }
    lines = ['#pragma once', '', '// Generated by tools/generate_cockpit_tables.py; do not edit by hand',
             '// Source image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '#include "graphics/cockpit.h"', '',
             'namespace darker::graphics {', '']
    total = 0
    for directory, pointers in directories.items():
        for pointer in pointers:
            end = next(p for p in boundaries if p > pointer)
            cursor = pointer + 4
            strips = []
            while cursor + 2 <= end and image[cursor] % 2 and cursor + 1 + image[cursor] <= end:
                rows = image[cursor] // 2
                name = f'rows_{pointer:04x}_{len(strips)}'
                lines.append(f'inline std::array<mask_row, {rows}> constexpr {name}{{{{')
                for i in range(rows):
                    skip, width = image[cursor + 2 + i * 2:cursor + 4 + i * 2]
                    lines.append(f'  {{.skip{{{skip}}}, .width{{{width}}}}},')
                lines += ['}};', '']
                strips.append((image[cursor + 1], name))
                cursor += image[cursor] + 1
            # The original descriptor at 4BE6 has a two-byte tail; it is not a mask.
            if cursor != end:
                lines.append(f'// Uninterpreted tail at {cursor:04X}: {image[cursor:end].hex()}')
            lines.append(f'inline std::array<hud_strip, {len(strips)}> constexpr strips_{pointer:04x}{{{{')
            for offset, name in strips:
                lines.append(f'  {{.y_offset{{{offset}}}, .rows{{{name}}}}},')
            lines += ['}};', '']
            total += len(strips)
        lines.append(f'inline std::array<hud_component, {len(pointers)}> constexpr components_{directory:04x}{{{{')
        for i, pointer in enumerate(pointers):
            lines.append(f'  {{.address{{0x{pointer:04x}}}, .field{{0x{0x454b+i:04x}}}, .label{{"{labels[directory][i]}"}}, '
                         f'.on_source{point(pointer)}, .destination{point(pointer+2)}, .alternate_source{point(pointer-2)}, .strips{{strips_{pointer:04x}}}}},')
        lines += ['}};', '']
    assert total == 127
    lines += ['} // namespace darker::graphics', '']
    args.output.write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
