#!/usr/bin/env python3
"""Capture complete near-clipped model drawing through the original FE interpreter."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256
from native_flat_model import render, fingerprint


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    word = lambda value: struct.pack('<H', value & 65535)
    vertices = b''.join(bytes([0x8e])+word(c)+word(a)+word(b) for a, b, c in
                        ((-32, -128, -24), (32, 128, -24), (32, 128, 24), (-32, -128, 24)))
    models = []
    for mirrored in (False, True):
        indices = [3, 2, 1, 0] if mirrored else [0, 1, 2, 3]
        flat = bytes([3, 76, *indices])
        models += [bytes(11)+vertices+flat+b'\x0d',
                   bytes(11)+vertices+bytes([0x16, *indices[:3], len(flat)])+flat+b'\x0d',
                   bytes(11)+vertices+bytes([0x0f, 76])+b''.join(bytes([i, i*7]) for i in indices)+b'\x0d']
    cases = []
    for code, gouraud in [(code, gouraud) for code in models for gouraud in (False, True)]:
        for depth in (-65, -1, 0, 1, 31, 32, 33, 63, 64, 65, 100):
            for fraction in (0, 255):
                pixels = render(Harness, image, code, 0, [16384, 4096, 0, 0, 0, 16384, 0, 16384, 0],
                                [0, 11, 0, 19, depth, fraction], [160, 84], list(range(28)), 0, bottom=168, near=True, flat=not gouraud)
                cases.append((code, depth, fraction, gouraud, fingerprint(pixels)))
    lines = ['#pragma once', '', '// Generated by tools/generate_near_model_reference.py; original FE interpreter and clipping',
             '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct near_model_sample {', '  int size, depth, fraction; bool gouraud; std::uint64_t fingerprint;',
             '  std::array<std::uint8_t, 64> code;', '};', f'inline constexpr std::array<near_model_sample, {len(cases)}> near_model_samples{{{{']
    for code, depth, fraction, gouraud, value in cases:
        assert len(code) <= 64
        lines.append('  {'+f'{len(code)}, {depth}, {fraction}, {str(gouraud).lower()}, 0x{value:016x}, '+'{'+', '.join(map(str, code))+'}},')
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/near_model_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} complete native near-clipped model draws.')


if __name__ == '__main__':
    main()
