#!/usr/bin/env python3
"""Capture the first mission's airborne callbacks, excluding scripts, firing and HUD threat selection."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from verify_player_collisions import setup
    from unicorn import UC_HOOK_CODE
    image = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(image).hexdigest() == IMAGE_SHA256
    h, bank, _ = setup(30)
    h.write(0xfdec, struct.pack('<H', 0x1000))
    h.cpu.mem_write(0x6a004, b'\xff')
    types = (args.workspace / 'analysis/resources/00_068.bin').read_bytes()
    limits = {t['type']: bytes.fromhex(t['record_hex'])[6] for t in bank['types']}
    counters = [0] * 256
    cells = bytearray()
    for i, kind in enumerate(types):
        row, column = divmod(i, 128)
        state = 255 if kind == 1 and row % 9 == 0 and column % 9 == 0 else 0
        cells.extend((kind, (state + counters[kind]) & 255))
        counters[kind] += 1
        if counters[kind] >= limits.get(kind, 0): counters[kind] = 0
    h.cpu.mem_write(0x60000, bytes(cells))
    h.write(0x2e10, b'\x40')
    definition = 0x1926 + 19 * 24
    model = bank['special_offsets'][19] + 0x400
    height = struct.unpack('<h', h.cpu.mem_read(0x70000 + model + 7, 2))[0]
    h.write(definition, struct.pack('<H', model))
    bases = [0xd986 + index * 112 for index in (1, 2)]
    for index, (bp, x, y, strength, behaviour) in enumerate(zip(bases, (10112, 6272), (23680, 23936), (153, 178), (240, 241)), 1):
        obj = bytearray(112)
        struct.pack_into('<HH', obj, 0, bases[0] if index == 2 else 0, bases[1] if index == 1 else 0)
        obj[7] = 2
        struct.pack_into('<3H', obj, 8, x, y, 11 * 256 - height)
        obj[0x20:0x22] = bytes((index, 19))
        struct.pack_into('<H', obj, 0x3e, 31 * 16)
        obj[0x50:0x56] = bytes((0, 127, 12, 10, strength, behaviour))
        struct.pack_into('<H', obj, 0x4a, (x >> 8) | (y & 0xff00))
        h.cpu.mem_write(h.STACK + bp, bytes(obj))
        h.setreg('BP', bp); h.setreg('BX', definition); h.call(0xbf41)
    h.write(0x6fd8, struct.pack('<HH', bases[1], bases[0]))
    player = bytearray(112)
    struct.pack_into('<3H', player, 8, 10000, 23700, 3000)
    h.cpu.mem_write(h.STACK + 0xd986, bytes(player))

    def hook(cpu, address, size, data):
        off = address - h.BASE
        if off in (0xbf97, 0x8afd):
            sp = h.getreg('SP')
            h.setreg('IP', int.from_bytes(cpu.mem_read(h.STACK + sp, 2), 'little'))
            h.setreg('SP', sp + 2)
        elif off == 0x8a58:
            h.setreg('IP', 0x8aa0)

    h.cpu.hook_add(UC_HOOK_CODE, hook)
    h.cpu.ctl_remove_cache(h.BASE, h.BASE + 65536)
    rows = []
    for frame in range(1024):
        if frame >= 256:
            position = list(struct.unpack('<3H', h.cpu.mem_read(h.STACK + bases[0] + 8, 6)))
            position[0] = (position[0] + 100) & 65535
            h.cpu.mem_write(h.STACK + 0xd986 + 8, struct.pack('<3H', *position))
        for bp in reversed(bases):
            h.setreg('DS', 0x1000); h.setreg('BP', bp); h.setreg('CX', 8)
            h.call(0x8823)
            raw = bytes(h.cpu.mem_read(h.STACK + bp, 112))
            values = [int.from_bytes(raw[o:o+2], 'little') for o in (8,10,12,0x2a,0x2c,0x2e,0x3e,0x26,0x28,0x48,0x4c,0x4e,0x56,0x64)] + list(raw[4:7])
            rows.append(values)
    lines = ['#pragma once', '', '// Generated by tools/generate_actor_flight_reference.py; original 8823 callback',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'inline constexpr std::array<std::array<int, 17>, 2048> actor_flight_samples{{']
    lines += ['  {' + ', '.join(map(str, row)) + '},' for row in rows]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/actor_flight_samples.h').write_text('\n'.join(lines))
    print('Captured 2,048 original actor flight updates.')


if __name__ == '__main__':
    main()
