#!/usr/bin/env python3
"""Capture the seven embedded setup programs with original helpers and varied retained state."""
import argparse
import json
from pathlib import Path
import random
import struct
import sys


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from verify_mission_native import block_check, GLOBALS, IMAGE_SHA256
    fields = (8,10,12,42,44,46,62,66,34,104,94,102,56,58,60,98,74)
    rows = []
    kind = 0
    for record in json.loads((args.workspace/'analysis/missions/scenarios.json').read_text())['records']:
        for block in record.get('native_setup',[]):
            for seed in range(32):
                rng = random.Random(seed)
                obj = bytearray(rng.randrange(256) for _ in range(112))
                struct.pack_into('<H',obj,0x22,0x1200)
                globals_ = {p:rng.randrange(256) for p in GLOBALS}
                h = block_check(record,block,seed)
                after = bytes(h.cpu.mem_read(h.STACK+0xd986,112))
                words = lambda data: [struct.unpack_from('<H',data,p)[0] for p in fields]+[data[7]]
                before_globals = [globals_[p] | globals_[p+1]<<8 for p in (0x8540,0x7fa6)]
                before_globals += [globals_[0x7f0e]<<8,globals_[0x5e11],globals_[0x5e14]]
                after_globals = [int.from_bytes(h.read(p,2),'little') for p in (0x8540,0x7fa6)]
                after_globals += [h.read(0x7f0e)[0]<<8,h.read(0x5e11)[0],h.read(0x5e14)[0]]
                height = [0,1,65535,264,4096,32768][seed%6]
                clock = [0,65280,65535,64767,32767,4660][seed%6]
                rows.append([kind,height,clock]+words(obj)+before_globals+words(after)+after_globals)
            kind += 1
    lines = ['#pragma once','','// Generated by tools/generate_scenario_setup_reference.py',
      '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
      f'inline constexpr std::array<std::array<int,{len(rows[0])}>,{len(rows)}> scenario_setup_samples{{{{']
    lines += ['  {'+', '.join(map(str,r))+'},' for r in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/scenario_setup_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} embedded setup cases.')


if __name__ == '__main__':
    main()
