#!/usr/bin/env python3
"""Capture native 8F3B flatbed routes and looping cardinal turns."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256

PROGRAMS = [bytes.fromhex('50 51 03 02 41 03 31 02 41 03 11 03 10 11 08'),
            bytes.fromhex('10 21 02 81 03 11 ff f9')]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256

    class Probe(Harness):
        removed = False

        def hook(self, cpu, address, size, data):
            p = address - self.BASE
            if p in (0x9185, 0x6ec7):
                if p == 0x6ec7:
                    self.removed = True
                sp = self.getreg('SP')
                self.setreg('IP', int.from_bytes(cpu.mem_read(self.STACK + sp, 2), 'little'))
                self.setreg('SP', sp + 2)
                return
            super().hook(cpu, address, size, data)

    samples = []
    for source, program in enumerate(PROGRAMS):
        for heading in (0, 0x4000, 0x8000, 0xc000):
            for step in (50, 255, 1023):
                h = Probe(raw)
                obj = bytearray(112)
                struct.pack_into('<3H', obj, 8, 14720, 20608, 0)
                struct.pack_into('<H', obj, 0x2a, heading)
                struct.pack_into('<H', obj, 0x58, 0xf000)
                struct.pack_into('<H', obj, 0x5e, 0xf000)
                h.cpu.mem_write(h.STACK + 0xd986, bytes(obj))
                h.setreg('BP', 0xd986)
                h.write(0xf000, program)
                h.write(0x3142, struct.pack('<H', 0x7000))
                h.cpu.mem_write(0x70007, struct.pack('<h', 37))
                fingerprint = 0xcbf29ce484222325
                count = 0
                for tick in range(0, 200000, step):
                    h.write(0xbf8, struct.pack('<H', tick & 65535))
                    h.call(0x8f3b)
                    after = bytes(h.cpu.mem_read(h.STACK + 0xd986, 112))
                    words = [*struct.unpack_from('<3H', after, 8), *after[4:7],
                             *struct.unpack_from('<3H', after, 0x2a),
                             int.from_bytes(after[0x3e:0x40], 'little'), after[7],
                             int.from_bytes(after[0x5e:0x60], 'little'),
                             int.from_bytes(after[0x58:0x5a], 'little') - 0xf000,
                             after[0x52], int(h.removed)]
                    for word in words:
                        fingerprint = ((fingerprint ^ word) * 0x100000001b3) & ((1 << 64) - 1)
                    count += 1
                    if h.removed:
                        break
                samples.append((source, heading, step, count, fingerprint))
    lines = ['#pragma once', '', '// Generated by tools/generate_vehicle_route_reference.py; native 8F3B',
             '// Combat suppressed; native movement and removal retained', '#include <array>', '#include <cstdint>', '',
             'namespace darker::test_reference {', '',
             'struct vehicle_route_sample { unsigned int program, heading, step, calls; uint64_t fingerprint; };',
             f'inline constexpr std::array<vehicle_route_sample,{len(samples)}> vehicle_route_samples{{{{']
    lines += [f'  {{{p},{h},{s},{n},0x{v:016x}ULL}},' for p,h,s,n,v in samples]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/vehicle_route_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(samples)} native routes, {sum(row[3] for row in samples)} callbacks.')


if __name__ == '__main__':
    main()
