#!/usr/bin/env python3
"""Execute Dual Launch firing, separation and category explosion passes in the DOS image."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args = parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    raw = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    rng = random.Random(0xcbe7)
    groups = []
    rows = []
    for i in range(1024):
        a = [rng.randrange(65536) for _ in range(3)]
        b = [(v+rng.choice((-2048,-1280,-480,-40,-1,0,1,39,40,479,1280,rng.randrange(-2000,2001))))&65535 for v in a]
        h = Harness(raw)
        h.cpu.mem_write(h.STACK+0xd008,struct.pack('<3H',*a))
        h.cpu.mem_write(h.STACK+0xd108,struct.pack('<3H',*b))
        h.cpu.mem_write(h.STACK+0xd06c,struct.pack('<H',0xd100))
        h.setreg('BP',0xd000)
        captured = []
        def separation(cpu,address,size,data):
            if address == h.BASE+0xcc0d:
                captured.append(h.getreg('AX'));h.setreg('IP',h.RETURN)
        h.cpu.hook_add(UC_HOOK_CODE,separation)
        h.call(0xcbe7)
        assert len(captured) == 1
        rows.append(a+b+captured)
    groups.append(('dual_separation_samples',7,rows))
    rows = []
    for i in range(2048):
        a = [rng.randrange(65536) for _ in range(3)]
        b = [(v+rng.choice((-1400,-1280,-480,-1,0,1,479,480,1279,1280,rng.randrange(-1500,1501))))&65535 for v in a]
        airborne = i%2
        h = Harness(raw)
        h.write(0x6fd8,struct.pack('<H',0xd100))
        h.write(0xcd48,bytes([25 if airborne else 6]))
        h.cpu.mem_write(h.STACK+0xd008,struct.pack('<3H',*a))
        h.cpu.mem_write(h.STACK+0xd100,bytes(112))
        h.cpu.mem_write(h.STACK+0xd108,struct.pack('<3H',*b))
        h.setreg('BP',0xd000);h.setreg('DI',0x6fd8);h.setreg('AX',0x5f22);h.setreg('SI',0x500 if airborne else 0x1e0)
        strength = []
        def impact(cpu,address,size,data):
            if address == h.BASE+0xce26:
                strength.append(h.getreg('AH'));h.setreg('IP',h.RETURN)
        h.cpu.hook_add(UC_HOOK_CODE,impact)
        h.call(0x6db5)
        assert h.getreg('IP') == h.RETURN and len(strength) <= 1
        rows.append(a+b+[airborne,int(bool(strength)),strength[0] if strength else 0])
    groups.append(('dual_impact_samples',9,rows))
    rows = []
    for i in range(1024):
        selection = rng.choice((3,7));reserve=rng.choice((0,10750,10751,51966,51967,65535))
        flags=rng.choice((0,0,16,32));free=int(i%9!=0);pressed=rng.randrange(2);tail=rng.choice((-1,0,2,6))
        mask=rng.choice((0x4016,0x8021,0x80,0xffff))
        h=Harness(raw)
        h.write(0x7fa6,struct.pack('<H',reserve));h.write(0x6fbc,struct.pack('<H',0xd200 if free else 0))
        h.write(0x6fba,struct.pack('<H',0 if tail<0 else 0xd000));h.write(0xc9f7,struct.pack('<H',mask if pressed else 0))
        h.write(0xb91f,bytes([25]));h.write(0xc97a,struct.pack('<H',mask));h.write(0x4543,bytes([selection,0]));h.write(0x5f0f,struct.pack('<H',0xec00));h.write(0x6202,b'\0')
        h.cpu.mem_write(h.STACK+0xd98d,bytes([flags]));h.cpu.mem_write(h.STACK+0xd044,struct.pack('<H',0x1926+max(0,tail)*24))
        h.setreg('AL',selection);h.setreg('SI',0x4545);h.setreg('DX',mask)
        fired=[]
        def launch(cpu,address,size,data):
            if address == h.BASE+0xcb01:
                fired.append(int.from_bytes(h.read(0x5f0f,2),'little'))
                # Return normally to preserve CA99's target restoration.
                sp=h.getreg('SP');ip=int.from_bytes(cpu.mem_read(h.STACK+sp,2),'little')
                h.setreg('SP',sp+2);h.setreg('IP',ip)
        h.cpu.hook_add(UC_HOOK_CODE,launch);h.call(0xc8e9)
        assert h.getreg('IP') == h.RETURN and int.from_bytes(h.read(0x5f0f,2),'little') == 0xec00
        rows.append([selection,reserve,flags,free,pressed,tail,int.from_bytes(h.read(0x7fa6,2),'little'),
                     int(h.read(0x5f02)[0]==0),h.read(0x4543)[0],int(bool(fired)),fired[0] if fired else 0,mask])
    groups.append(('dual_firing_samples',12,rows))
    lines=['#pragma once','','// Generated by tools/generate_dual_launch_reference.py; C8E9/C9C2, CBE7, 6DB5/CD13',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','']
    for name,width,rows in groups:
        lines += [f'inline constexpr std::array<std::array<int,{width}>,{len(rows)}> {name}{{{{']
        lines += ['  {'+','.join(map(str,row))+'},' for row in rows]
        lines += ['}};','']
        print(name,len(rows))
    lines += ['} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/dual_launch_samples.h').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
