#!/usr/bin/env python3
"""Capture original player route reacquisition around shipped underground starts."""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    root = parser.parse_args().workspace.resolve()
    sys.path.insert(0,str(root / 'tools'))
    from trace_hidden_commands import Harness
    raw = (root / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    h = Harness(raw)
    h.write(0x9c4a,raw[0x944a:0x984a])
    h.write(0xfdf2,struct.pack('<H',0x4000))
    h.write(0xfdf0,struct.pack('<H',0x3000))
    h.cpu.mem_write(0x70000,(root / 'analysis/resources/00_078.bin').read_bytes())
    h.setreg('DS',0x7000)
    h.setreg('SI',0)
    h.setreg('SP',0xfefe)
    h.cpu.mem_write(h.STACK+0xfefe,struct.pack('<H',h.RETURN))
    h.setreg('EFLAGS',2)
    h.cpu.emu_start(h.BASE+0xd0be,h.BASE+h.RETURN,count=1000000)
    assert h.getreg('IP') == h.RETURN
    samples = []
    records = json.loads((root / 'analysis/missions/scenarios.json').read_text())['records']
    for record in records:
        if record.get('craft_configuration') != 4:
            continue
        map_slot = record['map_resource']
        cells = bytearray(32768)
        cells[::2] = (root / f'analysis/resources/00_{map_slot:03}.bin').read_bytes()
        h.cpu.mem_write(0x30000,bytes(cells))
        for obj in record.get('objects',[]):
            if obj['format'] != 'moving':
                continue
            x,y = obj['position_words']
            h.cpu.mem_write(h.STACK+0xd986,bytes(112))
            h.setreg('BP',0xd986)
            h.setreg('DX',x)
            h.setreg('BX',y)
            h.setreg('DI',obj['heading_word'])
            h.setreg('SI',0xf000)
            h.call(0xbee7)
            cell = (h.getreg('DX') >> 8) | (h.getreg('BX') & 0xff00)
            route = h.cpu.mem_read(h.STACK+0xd986+0x6e,1)[0]
            initial_x,initial_y = h.getreg('DX'),h.getreg('BX')
            for dx,dy in ((0,0),(32,0),(-32,0),(0,32),(0,-32),(120,0),(-120,0),(0,120),(0,-120),(160,96),(-160,-96)):
                for height in (192,352,512):
                    x,y = (initial_x+dx) & 65535,(initial_y+dy) & 65535
                    source = cell if len(samples) % 2 else 0xffff
                    heading = (len(samples)*37) & 255
                    h.write(0xd1c0,bytes([heading]))
                    h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
                    h.cpu.mem_write(h.STACK+0xd986+0x62,struct.pack('<H',source))
                    h.cpu.mem_write(h.STACK+0xd986+0x6e,bytes([route | 0x40]))
                    h.setreg('BP',0xd986)
                    h.setreg('BX',x)
                    h.setreg('CX',y)
                    h.setreg('AX',height)
                    h.call(0xd39c)
                    assert h.getreg('IP') == h.RETURN
                    accepted = (h.getreg('AX') & 255) < 64
                    samples.append([map_slot,source,route | 0x40,heading,x,y,height,int(accepted),
                                    h.getreg('BX') if accepted else 0,(h.getreg('AX') >> 8) if accepted else 0])
    lines = ['#pragma once','','// Generated by generate_tunnel_reacquisition_reference.py; native D39C with original maps and routes.',
             '#include <array>','#include <cstdint>','','namespace darker::test_reference {','',
             f'inline constexpr std::array<std::array<uint16_t,10>,{len(samples)}> tunnel_reacquisition_samples{{{{']
    lines += ['  {'+','.join(map(str,s))+'},' for s in samples]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1] / 'tests/reference/tunnel_reacquisition_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(samples)} native tunnel reacquisition samples.')


if __name__ == '__main__':
    main()
