#!/usr/bin/env python3
"""Capture original 841C distance and 8AA8 engagement/cooldown arithmetic."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    raw=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    h=Harness(raw);rng=random.Random(0x8AA8);rows=[]
    for i in range(2048):
        player=[rng.randrange(65536) for _ in range(2)]
        offsets=[rng.randrange(-5000,5001) if i%2 else rng.randrange(-32768,32768) for _ in range(2)]
        position=[(a+b)&65535 for a,b in zip(player,offsets)]
        level,cooldown=rng.randrange(65536),rng.randrange(65536)
        decay,rise,strength,shift=[rng.randrange(256) for _ in range(4)]
        step=rng.choice([0,1,8,80,255,256,65535,rng.randrange(65536)])
        actor=bytearray(112)
        struct.pack_into('<2H',actor,8,*position)
        struct.pack_into('<H',actor,0x44,0xf000)
        actor[0x52:0x55]=bytes([decay,rise,strength])
        struct.pack_into('<H',actor,0x56,level)
        struct.pack_into('<H',actor,0x64,cooldown)
        h.cpu.mem_write(h.STACK+0xda00,bytes(actor))
        h.cpu.mem_write(h.STACK+0xd98e,struct.pack('<2H',*player))
        h.write(0xf00d,bytes([shift]))
        h.setreg('BP',0xda00);h.setreg('CX',step)
        h.call(0x8aa8)
        after=h.cpu.mem_read(h.STACK+0xda00,112)
        rows.append(([*position,*player,level,cooldown,decay,rise,strength,shift,step],
                     [int.from_bytes(after[0x56:0x58],'little'),int.from_bytes(after[0x64:0x66],'little')]))
    lines=['#pragma once','','// Generated by tools/generate_awareness_reference.py; native 841C/8AA8',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           'struct awareness_sample { std::array<int, 11> input; std::array<int, 2> output; };',
           f'inline constexpr std::array<awareness_sample, {len(rows)}> awareness_samples{{{{']
    lines += ['  {{'+', '.join(map(str,a))+'}, {'+', '.join(map(str,b))+'}},' for a,b in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/awareness_samples.h').write_text('\n'.join(lines))
    print('Captured 2,048 native engagement and cooldown cases.')


if __name__=='__main__':main()
