#!/usr/bin/env python3
"""Capture complete native Skimma flight/shield callback sequences."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    image=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest()!=IMAGE_SHA256:raise ValueError('Unsupported unpacked executable')
    rng=random.Random(0x8108);cases=[]
    for sequence in range(32):
        h=Harness(image)
        put=lambda at,value:h.cpu.mem_write(h.STACK+0xd986+at,struct.pack('<H',value&65535))
        patch=lambda at,value:h.write(at,struct.pack('<H',value&65535))
        get=lambda at:int.from_bytes(h.cpu.mem_read(h.STACK+0xd986+at,2),'little')
        value=lambda at:int.from_bytes(h.read(at,2),'little')
        h.write(0x9c4a,image[0x944a:0x964a])
        for at in (8,10):put(at,rng.randrange(32768))
        put(12,rng.randrange(16,12000))
        h.cpu.mem_write(h.STACK+0xd98a,bytes(rng.randrange(256) for _ in range(3)))
        for at in (0x2a,0x2c,0x2e):put(at,rng.randrange(65536))
        for at in (0x26,0x28):put(at,rng.randrange(-1024,1025))
        put(0x3e,rng.choice((0,100,1000,2047,2048,3000)));put(0x40,rng.randrange(-200,201));put(0x42,rng.randrange(2000))
        patch(0x80c7,rng.randrange(-256,257));patch(0x8109,rng.randrange(65536))
        def state():
            return ([get(at) for at in (8,10,12)]+list(h.cpu.mem_read(h.STACK+0xd98a,3))+
                    [get(at) for at in (0x2a,0x2c,0x2e,0x3e,0x26,0x28,0x42,0x40)]+[value(0x80c7),value(0x8109)])
        for tick in range(16):
            step=rng.choice((1,2,8,16,32,100,127));bank,pitch=[rng.randrange(-2048,2049)&65535 for _ in range(2)]
            response=rng.choice((352,384));setting=rng.choice((248,500,640));brake=int(tick%5==0);bias=rng.choice((-106,-110))
            for at,initial in ((0x7eba,bank),(0x7ecf,pitch),(0xb9f4,0x240 if brake else 0),(0x7f20,setting)):patch(at,initial)
            h.write(0x8006,bytes([bias&255]));put(0x30,response)
            before=state();h.setreg('BP',0xd986);h.setreg('CX',step);h.setreg('DS',0x1000)
            h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);h.call(0x8108)
            cases.append(([step,bank,pitch,response,setting,brake,bias],before,state()))
    lines=['#pragma once','','// Generated by tools/generate_skimma_flight_reference.py; original 8108 callback',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           'struct skimma_flight_sample { std::array<int, 7> input; std::array<int, 16> before, after; };',
           f'inline constexpr std::array<skimma_flight_sample, {len(cases)}> skimma_flight_samples{{{{']
    lines+=['  {'+', '.join('{'+', '.join(map(str,part))+'}' for part in case)+'},' for case in cases]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/skimma_flight_samples.h').write_text('\n'.join(lines))
    print('Captured',len(cases),'native Skimma updates.')


if __name__=='__main__':main()
