#!/usr/bin/env python3
"""Run the original placement helper against every shipped underground moving object."""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    root = parser.parse_args().workspace.resolve()
    sys.path.insert(0, str(root / 'tools'))
    from trace_hidden_commands import Harness
    raw = (root / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    h = Harness(raw)
    h.write(0xfdf2, struct.pack('<H', 0x4000))
    h.write(0xfdf0, struct.pack('<H', 0x3000))
    h.cpu.mem_write(0x70000, (root / 'analysis/resources/00_078.bin').read_bytes())
    h.setreg('DS', 0x7000)
    h.setreg('SI', 0)
    h.setreg('SP', 0xfefe)
    h.cpu.mem_write(h.STACK + 0xfefe, struct.pack('<H', h.RETURN))
    h.setreg('EFLAGS', 2)
    h.cpu.emu_start(h.BASE + 0xd0be, h.BASE + h.RETURN, count=1000000)
    assert h.getreg('IP') == h.RETURN
    samples = []
    records = json.loads((root / 'analysis/missions/scenarios.json').read_text())['records']
    for record in records:
        if record.get('craft_configuration') != 4:
            continue
        data = (root / f"analysis/resources/00_{record['map_resource']:03}.bin").read_bytes()
        cells = bytearray(32768)
        cells[::2] = data
        h.cpu.mem_write(0x30000, bytes(cells))
        for obj in record.get('objects', []):
            if obj['format'] != 'moving':
                continue
            x, y = obj['position_words']
            heading = obj['heading_word']
            h.cpu.mem_write(h.STACK + 0xd986, bytes(112))
            h.setreg('BP', 0xd986)
            h.setreg('DX', x)
            h.setreg('BX', y)
            h.setreg('DI', heading)
            h.setreg('SI', 0xf000)
            try:
                h.call(0xbee7)
            except Exception:
                print('Failed placement:', record['resource'], record['record'], obj['index'], x, y, heading)
                raise
            samples.append([int(record['resource'][3:]), record['record'], obj['index'], obj['definition_slot'],
                            h.getreg('DX'), h.getreg('BX'), h.getreg('CX'), h.getreg('DI'),
                            h.cpu.mem_read(h.STACK + 0xd986 + 0x6e, 1)[0]])
    lines = ['#pragma once', '', '// Generated by generate_tunnel_placement_reference.py; native BEE7 with original route and map resources.',
             '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             f'inline constexpr std::array<std::array<uint16_t,9>,{len(samples)}> tunnel_placement_samples{{{{']
    lines += ['  {' + ','.join(map(str, sample)) + '},' for sample in samples]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/tunnel_placement_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(samples)} native underground placements.')


if __name__ == '__main__':
    main()
