#!/usr/bin/env python3
"""Execute native map homing with the map/geometry lookup supplied explicitly."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')

    class Guidance(Harness):
        target = (0, 0)

        def hook(self, cpu, address, size, data):
            if address-self.BASE == 0xd089:
                for reg, value in [('AX', self.target[0]), ('BX', self.target[1]), ('DI', 12000), ('DX', 4096)]:
                    self.setreg(reg, value)
                sp = self.getreg('SP')
                ip = int.from_bytes(self.cpu.mem_read(self.STACK+sp, 2), 'little')
                self.setreg('SP', sp+2)
                self.setreg('IP', ip)
                return
            super().hook(cpu, address, size, data)

    native = Guidance(raw)
    native.write(0x9c4a, raw[0x944a:0x964a])
    samples = []
    for heading in range(0, 65536, 8192):
        for x, y in ((0, 0), (-7, -7), (7, 7), (8, 0), (-8, 0), (1000, 0), (-1000, 0), (0, 1000), (0, -1000), (32768, 0)):
            for shift in (0, 3, 16, 32):
                native.target = (x & 65535, y & 65535)
                definition = bytearray(raw[0x1926+5*24:0x1926+6*24])
                definition[16] = shift
                native.write(0x5000, bytes(definition))
                state = bytearray(112)
                state[4:7] = bytes([255, 127, 1])
                state[8:14] = struct.pack('<3H', 0, 0, 8192)
                state[0x26:0x2a] = struct.pack('<2H', 100, 65535)
                state[0x2a:0x30] = struct.pack('<3H', heading, 4096, 1234)
                state[0x3e:0x40] = struct.pack('<H', 1000)
                state[0x6c:0x6e] = struct.pack('<H', 0x0101)
                native.cpu.mem_write(native.STACK+0xd000, bytes(state))
                native.setreg('BP', 0xd000)
                native.setreg('BX', 0x5000)
                native.call(0xbf41)
                for tick, step in enumerate((1, 32, 65535)):
                    native.setreg('BP', 0xd000)
                    native.setreg('CX', step)
                    native.call(0xcc61)
                    result = bytes(native.cpu.mem_read(native.STACK+0xd000, 112))
                    out = [*struct.unpack('<3H', result[8:14]), *result[4:7], *struct.unpack('<5H', result[0x26:0x30]), int.from_bytes(result[0x3e:0x40], 'little')]
                    samples.append([heading, x & 65535, y & 65535, shift, tick, step, *out])
    lines = ['#pragma once', '', '// Generated by tools/generate_map_guidance_reference.py; native CC61 with D089 lookup supplied',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct map_guidance_sample { int heading, x, y, shift, tick, step; std::array<int, 12> result; };',
             f'inline constexpr std::array<map_guidance_sample, {len(samples)}> map_guidance_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row[:6])) + ', {' + ', '.join(map(str, row[6:])) + '}},' for row in samples]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/map_guidance_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(samples)} map-guidance updates.')


if __name__ == '__main__':
    main()
