#!/usr/bin/env python3
"""Capture native player crash state and subsequent attitude updates."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args();sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    image=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest()!=IMAGE_SHA256:raise ValueError('Unsupported unpacked executable')
    h=Harness(image);rng=random.Random(0x6ef7);cases=[]
    def skip_effect(cpu,address,size,data):
        if address-h.BASE==0x680c:
            sp=h.getreg('SP');target=int.from_bytes(cpu.mem_read(h.STACK+sp,2),'little')
            h.setreg('SP',sp+2);h.setreg('IP',target)
    h.cpu.hook_add(UC_HOOK_CODE,skip_effect)
    put=lambda at,value:h.cpu.mem_write(h.STACK+0xd986+at,struct.pack('<H',value&65535))
    get=lambda at:int.from_bytes(h.cpu.mem_read(h.STACK+0xd986+at,2),'little')
    for index in range(512):
        clock=rng.randrange(65536);step=rng.choice((0,1,8,16,80,127));flags=rng.randrange(256)
        before=[rng.randrange(65536) for _ in range(4)]+[flags,rng.randrange(65536)]
        for at,value in zip((0x2a,0x2c,0x2e,0x3e),before):put(at,value)
        h.cpu.mem_write(h.STACK+0xd98d,bytes([flags]));put(0x68,before[5]);put(0x66,0x7eb6)
        h.write(0xbf8,struct.pack('<H',clock));h.setreg('BP',0xd986);h.setreg('DS',0x1000)
        h.call(0x6f4f)
        started=int(get(0x66)==0x6ef7)
        after=[get(at) for at in (0x2a,0x2c,0x2e,0x3e)]+[h.cpu.mem_read(h.STACK+0xd98d,1)[0],get(0x68)]
        h.setreg('CX',step);h.call(0x6ef7)
        advanced=[get(at) for at in (0x2a,0x2c,0x2e)]
        cases.append(([clock,step],before,after,started,advanced))
    lines=['#pragma once','','// Generated by tools/generate_player_crash_reference.py; original 6F4F/6EF7',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           'struct player_crash_sample { std::array<int, 2> input; std::array<int, 6> before, after; bool started; std::array<int, 3> advanced; };',
           f'inline constexpr std::array<player_crash_sample, {len(cases)}> player_crash_samples{{{{']
    fmt=lambda a:'{'+', '.join(map(str,a))+'}'
    for args,before,after,started,advanced in cases:lines.append('  {'+', '.join((fmt(args),fmt(before),fmt(after),'true' if started else 'false',fmt(advanced)))+'},')
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/player_crash_samples.h').write_text('\n'.join(lines))


if __name__=='__main__':main()
