#!/usr/bin/env python3
"""Capture original keyboard/mouse steering and persistent smoothing state."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    image=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest()!=IMAGE_SHA256:raise ValueError('Unsupported unpacked executable')
    rng=random.Random(0x7ad6)
    fields=(0x7aef,0x7b4c,0x7b49,0xd62d,0x7afe,0x7b67,0x7b64,0xd5ca)
    cases=[]
    for sequence in range(32):
        h=Harness(image)
        h.write(0x3b52,b'\0') # Ordinary mouse path, without the specialised VR orientation source.
        h.write(0x1749,b'\0') # Suppress the separate joystick fallback when keyboard/mouse return zero.
        word=lambda at,value:h.write(at,struct.pack('<H',value&65535))
        for at in fields:word(at,rng.randrange(-4096,4097) if sequence>=16 else 0)
        x,y=0,0
        for tick in range(32):
            held=((sequence+tick)%32) if tick<16 else 0
            if sequence%4==0:held=0
            x=(x+rng.randrange(-100,101))&65535;y=(y+rng.randrange(-100,101))&65535
            step=rng.choice((1,2,8,16,32,100,127))
            sensitivity=rng.choice((1,12,25))
            keys=(0x10 if held&1 else 0)|(4 if held&2 else 0)|(0x80 if held&4 else 0)|(0x8000 if held&8 else 0)
            word(0x15b0,keys);h.write(0x15aa,bytes([4 if held&16 else 0]))
            word(0x11da,x);word(0x11dc,y);word(0x7ca2,sensitivity)
            before=[int.from_bytes(h.read(at,2),'little') for at in fields]
            h.setreg('CX',step)
            h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
            h.call(0x7ad6)
            after=[int.from_bytes(h.read(at,2),'little') for at in fields]
            cases.append(([held,x,y,step,sensitivity],before,after,[h.getreg('AX'),h.getreg('DX')]))
    lines=['#pragma once','','// Generated by tools/generate_flight_controls_reference.py; original keyboard/ordinary-mouse path',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           'struct flight_controls_sample { std::array<int, 5> input; std::array<int, 8> before, after; std::array<int, 2> drive; };',
           f'inline constexpr std::array<flight_controls_sample, {len(cases)}> flight_controls_samples{{{{']
    lines+=['  {'+', '.join('{'+', '.join(map(str,part))+'}' for part in case)+'},' for case in cases]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/flight_controls_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} native steering updates.')


if __name__=='__main__':main()
