#!/usr/bin/env python3
"""Capture native 26EE window setup and 2F35 moving-object visibility decisions."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    h = Harness(raw)
    rng = random.Random(0x2f35)
    rows = []
    for radius in (8, 15):
        for delta in range(256):
            x, y = [rng.randrange(65536) for _ in range(2)]
            # Run the original patching instructions, stopping before city traversal.
            h.write(0x26ef, struct.pack('<H', radius))
            h.write(0x2700, struct.pack('<H', x))
            h.write(0x271b, struct.pack('<H', y))
            h.write(0x270c, b'\0\0')
            h.cpu.ctl_remove_cache(h.BASE, h.BASE + 65536)
            h.cpu.emu_start(h.BASE + 0x26ee, h.BASE + 0x2732, count=100)
            for axis in (0, 1):
                position = [x, y]
                position[axis] = (position[axis] + delta * 256) & 65535
                h.cpu.mem_write(h.STACK + 0xe008, struct.pack('<HHH', *position, 0))
                h.setreg('BP', 0xe000)
                h.cpu.ctl_remove_cache(h.BASE, h.BASE + 65536)
                h.call(0x2f35)
                rows.append([x, y, radius, *position, h.getreg('EFLAGS') & 1])
    lines = ['#pragma once', '', '// Generated by tools/generate_object_window_reference.py; original 26EE and 2F35',
             '#include <array>', '', 'namespace darker::test_reference {', '',
             f'inline constexpr std::array<std::array<unsigned int,6>,{len(rows)}> object_window_samples{{{{']
    lines += ['  {' + ','.join(map(str, row)) + '},' for row in rows]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/object_window_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} native moving-object window decisions.')


if __name__ == '__main__':
    main()
