#!/usr/bin/env python3
"""Execute original target direction and complete object-homing trajectories."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    native = Harness(raw)
    def put(offset, data):
        native.cpu.mem_write(native.STACK+offset, data)
    source = (65535, 2000, 32768)
    put(0xd008, struct.pack('<3H', *source))
    directions = []
    for x in (-32768, -16384, -256, -1, 0, 1, 256, 16384, 32767):
        for y in (-32768, -16384, -256, -1, 0, 1, 256, 16384, 32767):
            for z in (-32768, -1, 0, 1, 32767):
                target = [(v+d) & 65535 for v, d in zip(source, (x, y, z))]
                for reg, value in [('BP', 0xd000), ('DX', target[0]), ('BX', target[1]), ('AX', target[2])]:
                    native.setreg(reg, value)
                native.call(0x9250)
                directions.append([*target, (native.getreg('DI')+32768) & 65535, native.getreg('AX')])
    native.write(0x9c4a, raw[0x944a:0x964a])
    native.write(0x5000, raw[0x1926:0x193e])
    trajectories = []
    targets = [(0, 0, 0), (4096, 65535, 4096), (65535, 4096, 16384), (32768, 32767, 8192), (0, 65535, 8192), (0, 0, 0)]
    for scenario, base in enumerate(targets):
        state = bytearray(112)
        state[4:7] = bytes([255, 127, 1])
        state[8:14] = struct.pack('<3H', 0, 65535, 8192)
        state[0x2a:0x30] = struct.pack('<3H', 0, 0, 1234)
        state[0x30:0x32] = struct.pack('<H', 480)
        state[0x3e:0x40] = struct.pack('<H', 1000)
        state[0x44:0x46] = struct.pack('<H', 0x5000)
        state[0x6c:0x6e] = struct.pack('<H', 0xd000 if scenario == 5 else 0xd200)
        put(0xd000, bytes(state))
        for tick in range(64):
            target = [(v+(tick*17 if axis == 0 and scenario < 4 else 0)) & 65535 for axis, v in enumerate(base)]
            put(0xd208, struct.pack('<3H', *target))
            step = (1, 2, 4, 8)[tick % 4]
            native.setreg('BP', 0xd000)
            native.setreg('CX', step)
            native.call(0xcc61)
            result = bytes(native.cpu.mem_read(native.STACK+0xd000, 112))
            out = [*struct.unpack('<3H', result[8:14]), *result[4:7], *struct.unpack('<5H', result[0x26:0x30]), int.from_bytes(result[0x3e:0x40], 'little')]
            trajectories.append([scenario, tick, step, *target, *out])
    lines = ['#pragma once', '', '// Generated by tools/generate_direction_reference.py; native 9250 and CC61',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct direction_sample { int x, y, z, heading, pitch; };',
             f'inline constexpr std::array<direction_sample, {len(directions)}> direction_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row)) + '},' for row in directions]
    lines += ['}};', '', 'struct trajectory_sample { int scenario, tick, step; std::array<int, 3> target; std::array<int, 12> result; };',
              f'inline constexpr std::array<trajectory_sample, {len(trajectories)}> trajectory_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row[:3])) + ', {' + ', '.join(map(str, row[3:6])) + '}, {' + ', '.join(map(str, row[6:])) + '}},' for row in trajectories]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/direction_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(directions)} directions and {len(trajectories)} trajectory steps.')


if __name__ == '__main__':
    main()
