#!/usr/bin/env python3
"""Capture complete native Pinner Mimic steering and displacement."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    raw=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    h=Harness(raw);h.write(0x9c4a,raw[0x944a:0x964a]);rng=random.Random(0xcbce);rows=[]
    for i in range(2048):
        position=[rng.randrange(65536) for _ in range(3)]
        fractions=[rng.randrange(256) for _ in range(3)]
        angles=[rng.randrange(65536) for _ in range(3)]
        speed=rng.randrange(65536)
        player=[rng.randrange(65536) for _ in range(2)]
        remaining=rng.randrange(1537) if i%2 else rng.randrange(65536)
        step=rng.randrange(81) if i%4 else rng.randrange(65536)
        obj=bytearray(112);obj[4:7]=bytes(fractions)
        struct.pack_into('<3H',obj,8,*position);struct.pack_into('<3H',obj,0x2a,*angles)
        struct.pack_into('<H',obj,0x3e,speed);struct.pack_into('<H',obj,0x44,0x193e)
        h.cpu.mem_write(h.STACK+0xda00,bytes(obj));h.cpu.mem_write(h.STACK+0xd9b2,struct.pack('<2H',*player))
        h.setreg('BP',0xda00);h.setreg('DX',remaining);h.setreg('CX',step);h.call(0xcbce)
        after=bytes(h.cpu.mem_read(h.STACK+0xda00,112))
        result=[*struct.unpack_from('<3H',after,8),*after[4:7],*struct.unpack_from('<3H',after,0x2a),
                int.from_bytes(after[0x3e:0x40],'little'),int.from_bytes(after[0x36:0x38],'little')]
        rows.append([*position,*fractions,*angles,speed,*player,remaining,step,*result])
    lines=['#pragma once','','// Generated by tools/generate_mimic_reference.py; complete native CBCE motion',
           '#include <array>','','namespace darker::test_reference {','',
           f'inline constexpr std::array<std::array<unsigned int,25>,{len(rows)}> mimic_samples{{{{']
    lines+=['  {'+','.join(map(str,row))+'},' for row in rows]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/mimic_samples.h').write_text('\n'.join(lines))
    print('Captured',len(rows),'complete native Mimic motion calls.')


if __name__=='__main__':main()
