#!/usr/bin/env python3
"""Capture native projectile expiry, reference repair and mission-counter effects."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')

    class Expiry(Harness):
        def hook(self, cpu, address, size, data):
            offset = address-self.BASE
            if offset == 0x7a52:
                sp = self.getreg('SP')-2
                self.cpu.mem_write(self.STACK+sp, struct.pack('<H', 0x6fb8))
                self.setreg('SP', sp)
            if offset == 0x79bf:
                self.setreg('IP', self.RETURN)
                return
            super().hook(cpu, address, size, data)

    native = Expiry(raw)
    word = lambda value: struct.pack('<H', value & 65535)
    def put(offset, value):
        native.cpu.mem_write(native.STACK+offset, word(value))
    def get(offset):
        return int.from_bytes(native.cpu.mem_read(native.STACK+offset, 2), 'little')
    def dsword(offset):
        return int.from_bytes(native.read(offset, 2), 'little')
    def initialise():
        # The original clears SS:C800..FFFF, so keep the probe's return stack below it.
        native.setreg('SP', 0x7000)
        native.cpu.mem_write(native.STACK+0x7000, word(native.RETURN))
        native.cpu.emu_start(native.BASE+0x1cfb, native.BASE+native.RETURN, count=100000)
        assert native.getreg('IP') == native.RETURN
        pointer = dsword(0x6fbc)
        ids = []
        while pointer:
            ids.append(pointer)
            pointer = get(pointer)
        assert ids == [0xd1a6+112*i for i in reversed(range(12))]
    cases = []
    for lifecycle in (0, 1, 2, 3, 4, 254, 255):
        for completed, outstanding in ((0, 0), (255, 128), (2, 2)):
            for selected in (0, 1):
                initialise()
                for i in range(3):
                    native.setreg('DI', 0x6fb8)
                    native.call(0x1c95)
                head, expired, tail = [0xd1a6+112*i for i in (9, 10, 11)]
                for node, target in ((head, expired), (expired, expired), (tail, 0x1234)):
                    put(node+0x6c, target)
                native.cpu.mem_write(native.STACK+expired+7, bytes([8]))
                native.cpu.mem_write(native.STACK+expired+0x46, bytes([lifecycle]))
                for offset, value in [(0x5f0f, expired if selected else head), (0x2449, expired if selected else tail),
                                      (0x78f2, expired if selected else 0x1234), (0x5e03, 17)]:
                    native.write(offset, word(value))
                native.write(0xc21b, bytes([completed]))
                native.write(0xc16f, bytes([outstanding]))
                native.cpu.ctl_remove_cache(native.BASE+0xc16e, native.BASE+0xc177)
                native.setreg('BP', expired)
                native.call(0x7a52)
                result = [dsword(a) for a in (0x6fb8, 0x6fba, 0x6fbc)] + [native.getreg('BP')]
                result += [get(node+0x6c) for node in (head, expired, tail)]
                result += [dsword(a) for a in (0x5f0f, 0x2449, 0x78f2, 0x5e03)]
                result += [native.read(0xc21b)[0], native.read(0xc16f)[0], native.cpu.mem_read(native.STACK+expired+7, 1)[0],
                           native.cpu.mem_read(native.STACK+expired+0x46, 1)[0], get(expired), get(expired+2)]
                cases.append([lifecycle, completed, outstanding, selected, *result])
    lines = ['#pragma once', '', '// Generated by tools/generate_expiry_reference.py; native pool initialisation and 7A52',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct expiry_sample { int lifecycle, completed, outstanding, selected; std::array<int, 17> result; };',
             f'inline constexpr std::array<expiry_sample, {len(cases)}> expiry_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row[:4])) + ', {' + ', '.join(map(str, row[4:])) + '}},' for row in cases]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/expiry_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} full native expiry cases and verified all projectile pool IDs.')


if __name__ == '__main__':
    main()
