#!/usr/bin/env python3
"""Capture native flat-polygon clipping and scan coverage before VGA plane writes."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def hull(points):
    points = sorted(set(points))
    def cross(a, b, c):
        return (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])
    halves = []
    for order in (points, points[::-1]):
        part = []
        for point in order:
            while len(part) >= 2 and cross(part[-2], part[-1], point) <= 0:
                part.pop()
            part.append(point)
        halves.append(part[:-1])
    return halves[0]+halves[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')

    class Raster(Harness):
        def hook(self, cpu, address, size, data):
            if address-self.BASE == 0xa583:
                right, left, row = self.getreg('CX'), self.getreg('SI'), self.getreg('BP')//256
                assert 0 <= left <= 320 and 0 <= right <= 320 and row < 240, (row, left, right)
                if right > left:
                    self.pixels[row*320+left:row*320+right] = bytes([37])*(right-left)
                # Replace only the VGA plane writes; retain the common scanline advance.
                self.setreg('CX', (right-left)&65535)
                self.setreg('IP', 0xa566)
                return
            super().hook(cpu, address, size, data)

    rng = random.Random(0xa1b6)
    shapes = [[(50, 20), (100, 100), (10, 100)], [(10, 10), (100, 10), (100, 100), (10, 100)],
              [(-100, -100), (420, -100), (420, 340), (-100, 340)], [(0, 0), (319, 0), (319, 240), (0, 240)],
              [(10, 10), (11, 11), (10, 12)], [(10, 10), (10, 10), (10, 10)],
              [(-100, 10), (-50, 20), (-80, 50)], [(0, 300), (50, 300), (50, 400)]]
    for _ in range(48):
        shapes.append(hull([(rng.randrange(-150, 470), rng.randrange(-120, 360)) for _ in range(8)]))
    cases = []
    for shape in shapes:
        for points, right, bottom in [(points, right, bottom) for points in (shape, shape[1:]+shape[:1], shape[::-1])
                                      for right, bottom in ((319, 240), (159, 100), (319, 200))]:
            native = Raster(raw)
            native.pixels = bytearray(320*240)
            word = lambda value: struct.pack('<H', value&65535)
            native.setreg('DS', 0x2000)
            native.cpu.mem_write(0x201ec, word(0x1000))
            native.write(0xfdf4, word(0xa000))
            native.write(0, struct.pack('<240H', *[y*256 for y in range(240)]))
            native.write(0xa296, word(bottom))
            native.write(0xa320, word(right))
            native.cpu.mem_write(0x2fc00, b''.join(struct.pack('<hh', *point) for point in points))
            native.cpu.mem_write(0x20400, bytes(range(len(points))))
            native.setreg('SI', 0x400)
            native.setreg('CX', len(points)-1)
            native.call(0xa1b6)
            fingerprint = 0xcbf29ce484222325
            for byte in native.pixels:
                fingerprint = ((fingerprint ^ byte)*0x100000001b3)&((1<<64)-1)
            cases.append((points, right, bottom, fingerprint, sum(byte != 0 for byte in native.pixels)))
    lines = ['#pragma once', '', '// Generated by tools/generate_flat_polygon_reference.py; native A1B6 through A583, VGA writes intercepted',
             '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '#include "graphics/flat_polygon.h"', '',
             'namespace darker::test_reference {', '', 'struct flat_polygon_sample {', '  int count, right, bottom;', '  std::array<graphics::screen_vertex, 8> vertices;',
             '  std::uint64_t fingerprint;', '  int pixels;', '};', f'inline constexpr std::array<flat_polygon_sample, {len(cases)}> flat_polygon_samples{{{{']
    for points, right, bottom, fingerprint, pixels in cases:
        values = ', '.join('{'+str(x)+', '+str(y)+'}' for x,y in points)
        lines.append('  {'+str(len(points))+', '+str(right)+', '+str(bottom)+', {{'+values+'}}, 0x'+f'{fingerprint:016x}'+', '+str(pixels)+'},')
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/flat_polygon_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} native polygons with clipping, reversed winding and rotated vertex starts.')


if __name__ == '__main__':
    main()
