#!/usr/bin/env python3
"""Capture CE26 object impacts including the original random angular kick."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')

    class Impact(Harness):
        def hook(self, cpu, address, size, data):
            if address-self.BASE == 0x6815:
                self.effect = self.getreg('SI')
                self.setreg('IP', self.RETURN)
                return
            super().hook(cpu, address, size, data)

    native = Impact(raw)
    bp = 0xd000
    word = lambda value: struct.pack('<H', value & 65535)
    def put(offset, value):
        native.cpu.mem_write(native.STACK+bp+offset, word(value))
    def get(offset):
        return int.from_bytes(native.cpu.mem_read(native.STACK+bp+offset, 2), 'little')
    rng = random.Random(0xce26)
    cases = []
    for resistance in (1, 2, 16, 64, 128, 255):
        strengths = sorted({0, 1, resistance-1, resistance, min(255, resistance+1), min(255, 2*resistance-1), min(255, 2*resistance), 255})
        for strength in strengths:
            for damage in (0, 0x7fff, 0xfffe, 0xffff):
                for mode in (0, 2):
                    for expiring in (False, True):
                        pitch, heading, accumulator, seed, clock = [rng.randrange(65536) for _ in range(5)]
                        deadline = (clock + rng.choice((255, 256, 257, 32768, 65535))) & 65535
                        flags = 0x28 if expiring else 8
                        for offset, value in [(0x44, 0xf000), (0x66, 0x8823), (0x64, damage), (0x56, accumulator),
                                              (0x68, deadline), (0x26, pitch), (0x28, heading)]:
                            put(offset, value)
                        native.cpu.mem_write(native.STACK+bp+7, bytes([flags]))
                        native.write(0xf008, bytes([resistance]))
                        native.write(0x6202, bytes([mode]))
                        native.write(0xbf8, word(clock))
                        native.write(0x92d3, word(seed))
                        native.cpu.ctl_remove_cache(native.BASE+0x92d2, native.BASE+0x92ed)
                        native.setreg('BP', bp)
                        native.setreg('AX', strength << 8)
                        native.effect = None
                        native.call(0xce26)
                        assert native.effect in (0x72df, 0x7319)
                        result = [get(a) for a in (0x26, 0x28, 0x56, 0x64, 0x66, 0x68)]
                        result += [native.cpu.mem_read(native.STACK+bp+7, 1)[0], int.from_bytes(native.read(0x92d3, 2), 'little'), native.effect]
                        cases.append([strength, resistance, mode, clock, seed, pitch, heading, accumulator, damage, deadline, flags, *result])
    lines = ['#pragma once', '', '// Generated by tools/generate_impact_reference.py; native CE26, 854E, 8568 and 92D2',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct impact_sample {', '  int strength, resistance, mode, clock, seed, pitch, heading, accumulator, damage, deadline, flags;',
             '  std::array<int, 9> result;', '};', f'inline constexpr std::array<impact_sample, {len(cases)}> impact_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row[:11])) + ', {' + ', '.join(map(str, row[11:])) + '}},' for row in cases]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/impact_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} native impacts with uninterrupted random kick and damage arithmetic.')


if __name__ == '__main__':
    main()
