"""Probe full Diffuser firing dispatch and its shared building-hit state."""
import argparse,sys,struct,random,hashlib
from pathlib import Path
def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    root=parser.parse_args().workspace.resolve()
    sys.path[:0]=[str(root/'tools'),str(root/'darker-cpp/tools')]
    from trace_hidden_commands import Harness
    from generate_resource_directory import IMAGE_SHA256
    from unicorn import UC_HOOK_CODE
    raw=(root/'analysis/unpacked/image.bin').read_bytes();assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    rng=random.Random(0xce84);rows=[]
    for i in range(768):
     h=Harness(raw);selection=rng.choice((4,5));mode=rng.choice((0,2));cost=(128 if mode==2 else raw[0x1926+(selection-1)*24+10])*256+255
     reserve=rng.choice((0,cost-1,cost,65535,rng.randrange(65536)));pressed=rng.randrange(2);free=i%9!=0;flags=rng.choice((0,0,16,32));target=rng.choice((0,0x1717,0x7fff,0x8000,0xd000,0xffff))
     for p,v in ((0xc9f7,0x8021 if pressed else 0),(0x6fbc,0xd200 if free else 0),(0x7fa6,reserve),(0x5f0f,target)):h.write(p,struct.pack('<H',v))
     h.write(0x4543,bytes([0,selection]));h.write(0xb91f,b'\x19');h.write(0x6202,bytes([mode]));h.cpu.mem_write(h.STACK+0xd98d,bytes([flags]));fired=[]
     def launch(cpu,a,s,d):
      if a==h.BASE+0xcb01:
       fired.append(1);sp=h.getreg('SP');h.setreg('IP',int.from_bytes(cpu.mem_read(h.STACK+sp,2),'little'));h.setreg('SP',sp+2)
     h.cpu.hook_add(UC_HOOK_CODE,launch);h.call(0xc8e9)
     rows.append([selection,mode,reserve,pressed,int(free),flags,target,int.from_bytes(h.read(0x7fa6,2),'little'),int(h.read(0x5f16)[0]==0),h.read(0x4544)[0],int(bool(fired))])
    print('firing',len(rows),sum(r[-1] for r in rows))
    impact=[]
    for i in range(1024):
     h=Harness(raw);gas=rng.randrange(2);category=rng.randrange(5);state=rng.randrange(256);cell=0x1717;oldcell=rng.choice((cell,0,0x1817));clock=rng.randrange(65536);delta=rng.choice((0,1,0xefff,0xf000,0xf001,0xffff,rng.randrange(65536)));deadline=(clock-delta)&65535;sound_deadline=rng.randrange(65536)
     for p,v in ((0xfdf0,0x6000),(0xbf0,clock),(0xc4a,deadline),(0x3da3,oldcell),(0x37f6,sound_deadline)):h.write(p,struct.pack('<H',v))
     h.write(0x6064,bytes([category]));h.cpu.mem_write(0x60000+0x172f,bytes([state]));h.cpu.mem_write(h.STACK+0xd044,struct.pack('<H',0x1986 if gas else 0x196e));result=[]
     def stop(cpu,a,s,d):
      if a-h.BASE in (0x67ea,0x67bf,0x680c):result.append(a-h.BASE);h.setreg('IP',h.RETURN)
     h.cpu.hook_add(UC_HOOK_CODE,stop);h.setreg('BP',0xd000);h.setreg('AX',cell);h.setreg('DI',2);h.call(0xce84);assert len(result)==1
     impact.append([gas,category,state,cell,oldcell,clock,deadline,sound_deadline,result[0],int.from_bytes(h.read(0x3da3,2),'little'),int.from_bytes(h.read(0xc4a,2),'little'),int.from_bytes(h.read(0x37f6,2),'little')])
    print('impacts',len(impact))
    lines=['#pragma once','','// Generated by tools/generate_diffuser_reference.py; native C8E9/CA69 and CE84','#include <array>','','namespace darker::test_reference {','']
    for name,group in [('diffuser_firing_samples',rows),('diffuser_impact_samples',impact)]:
     lines += [f'inline constexpr std::array<std::array<unsigned int,{len(group[0])}>,{len(group)}> {name}{{{{']
     lines += ['  {'+','.join(map(str,r))+'},' for r in group];lines += ['}};','']
    lines += ['} // namespace darker::test_reference','']
    (root/'darker-cpp/tests/reference/diffuser_samples.h').write_text('\n'.join(lines))


if __name__ == "__main__":
    main()
