#!/usr/bin/env python3
"""Capture original Skimma recoil arithmetic over every signed-byte state."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    assert digest == '7599201a01aa24b7e6ad1ae4295d493821cde7c3a43b247c464522626c0380a4'

    class Recoil(Harness):
        random_byte = 0

        def hook(self, cpu, address, size, data):
            offset = address - self.BASE
            if offset in (0xc96d, 0xc991):
                self.setreg('IP', self.RETURN)
                return
            if offset == 0x92d2:
                self.setreg('AX', self.random_byte)
                sp = self.getreg('SP')
                ip = int.from_bytes(self.cpu.mem_read(self.STACK + sp, 2), 'little')
                self.setreg('SP', sp + 2)
                self.setreg('IP', ip)
                return
            super().hook(cpu, address, size, data)

    def checksum(data):
        result = 14695981039346656037
        for value in data:
            result = ((result ^ value) * 1099511628211) & ((1 << 64) - 1)
        return result

    native = Recoil(raw)
    frames = []
    for step in (0, 1, 4, 31, 64, 127, 128, 255, 256, 511, 65535):
        pixels = bytearray()
        for previous in range(256):
            native.write(0xc9ff, bytes([previous]))
            native.write(0x7a2b, struct.pack('<H', step))
            native.call(0xc950)
            pixels += native.read(0xc9ff) + native.read(0x5d4b, 2) + struct.pack('<H', native.getreg('BX'))
        frames.append((step, checksum(pixels)))
    kicks = []
    for random_byte in range(256):
        values = bytearray()
        native.random_byte = random_byte
        for previous in range(256):
            native.write(0xc9ff, bytes([previous]))
            native.call(0xc984)
            values += native.read(0xc9ff)
        kicks.append((random_byte, checksum(values)))
    lines = ['#pragma once', '', '// Generated by tools/generate_recoil_reference.py from native execution',
             '// Image SHA-256: ' + digest, '', '#include <array>', '#include <cstdint>', '',
             'namespace darker::test_reference {', '', 'struct recoil_sample { std::uint16_t input; std::uint64_t checksum; };']
    for name, rows in [('recoil_frames', frames), ('recoil_kicks', kicks)]:
        lines += [f'inline constexpr std::array<recoil_sample, {len(rows)}> {name}{{{{']
        lines += [f'  {{{value}, 0x{hash_value:016x}ULL}},' for value, hash_value in rows]
        lines += ['}};', '']
    lines += ['} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/recoil_samples.h').write_text('\n'.join(lines))
    print('Captured 2,816 frame updates and all 65,536 recoil kick combinations.')


if __name__ == '__main__':
    main()
