#!/usr/bin/env python3
"""Recover the shared fixed-point sine words without floating-point regeneration."""
import argparse
import hashlib
from pathlib import Path
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('image', type=Path)
    args = parser.parse_args()
    image = args.image.read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    values = [int.from_bytes(image[p:p+2], 'little', signed=True) for p in range(0x944a, 0x9c4a, 2)]
    lines = ['#pragma once', '', '// Generated by tools/generate_sine_table.py; native words at 944A',
             '// Source image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '',
             'namespace darker::math {', '', 'inline std::array<std::int16_t, 1024> constexpr original_sine{']
    lines += ['  ' + ', '.join(map(str, values[i:i+16])) + ',' for i in range(0, 1024, 16)]
    lines += ['};', '', '} // namespace darker::math', '']
    (Path(__file__).resolve().parents[1] / 'src/math/sine_table.h').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
