#!/usr/bin/env python3
"""Capture B292 page positions, colour tokens, cursor state and byte consumption."""
import argparse
import hashlib
import json
from pathlib import Path
import struct
from unicorn import Uc, UC_ARCH_X86, UC_MODE_16, UC_HOOK_CODE
from unicorn.x86_const import *
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    image=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(image).hexdigest()==IMAGE_SHA256
    fonts=(args.workspace/'analysis/resources/00_029.bin').read_bytes()
    document=json.loads((args.workspace/'analysis/text/formatted-text.json').read_text())
    cpu=Uc(UC_ARCH_X86,UC_MODE_16)
    cpu.mem_map(0,0x100000)
    cpu.mem_write(0x10000,image)
    cpu.mem_write(0x62978,fonts)
    colour=[0x3456]
    glyphs=[]

    def ret():
        sp=cpu.reg_read(UC_X86_REG_SP)
        ip=int.from_bytes(cpu.mem_read(0x60000+sp,2),'little')
        cpu.reg_write(UC_X86_REG_SP,sp+2)
        cpu.reg_write(UC_X86_REG_IP,ip)

    def hook(cpu,address,size,_):
        if address==0x1e1fe:
            code=cpu.reg_read(UC_X86_REG_AX)&255
            x,y=cpu.reg_read(UC_X86_REG_DX),cpu.reg_read(UC_X86_REG_DI)
            glyphs.append((code,x,y,colour[0]))
            advance=4 if code<33 else fonts[107+(code-33)*2]
            cpu.reg_write(UC_X86_REG_DX,(x+advance)&65535)
            ret()
        elif address==0x1e11f:
            value=cpu.reg_read(UC_X86_REG_AX)
            if value!=65535:colour[0]=value
            ret()

    cpu.hook_add(UC_HOOK_CODE,hook)

    def call(entry,extra):
        for reg,value in {UC_X86_REG_CS:0x1000,UC_X86_REG_DS:0x1000,UC_X86_REG_SS:0x6000,
                          UC_X86_REG_SP:0xfffc,UC_X86_REG_EFLAGS:2,**extra}.items():cpu.reg_write(reg,value)
        cpu.mem_write(0x6fffc,b'\xf0\xff')
        cpu.emu_start(0x10000+entry,0x1fff0,count=1000000)
        assert cpu.reg_read(UC_X86_REG_IP)==0xfff0

    call(0xe29c,{UC_X86_REG_AX:0x2978,UC_X86_REG_DX:0x906b,UC_X86_REG_DI:0x6000})
    rows=[]
    samples=[]
    for section in document['sections']:
        for page in section['pages']:
            raw=bytes.fromhex(page['raw_hex'])
            samples.append((int(section['resource'][3:]),page['offset'],raw))
    # Controls 6/7 are supported by B292 but absent from the extracted mission pages.
    extra=[bytes([5,11,0xf0,1,20,30,2,0x34,0x12,ord('A'),4,ord('B'),3,7,2,255,255,ord('C'),0]),
           bytes([6])+b'Hello world\0!\0',bytes([7,0])]
    for i,raw in enumerate(extra):samples.append((16,i,raw))
    for slot,offset,raw in samples:
        cpu.mem_write(0x1f000,raw)
        cpu.mem_write(0x1b2bd,b'\0\0')
        cpu.mem_write(0x1b2c1,b'\x10')
        cpu.mem_write(0x1b2f1,b'\xc3')
        cpu.ctl_remove_cache(0x1b292,0x1b2fb)
        glyphs.clear();colour[0]=0x3456
        call(0xb292,{UC_X86_REG_DX:0,UC_X86_REG_DI:0,UC_X86_REG_SI:0xf000})
        values=[cpu.reg_read(UC_X86_REG_SI)-0xf000,cpu.reg_read(UC_X86_REG_DX),cpu.reg_read(UC_X86_REG_DI),colour[0],
                cpu.mem_read(0x1b2bd,1)[0],cpu.mem_read(0x1b2c1,1)[0],len(glyphs)]
        for glyph in glyphs:values+=glyph
        fingerprint=0xcbf29ce484222325
        for value in values:
            for byte in value.to_bytes(4,'little'):fingerprint=((fingerprint^byte)*0x100000001b3)&((1<<64)-1)
        supported=all(code<140 for code,_,_,_ in glyphs)
        rows.append((slot,offset,len(raw),supported,fingerprint))
    lines=['#pragma once','','// Generated by tools/generate_text_reference.py; native B292 with glyph and colour calls intercepted',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','#include <cstdint>','','namespace darker::test_reference {','',
           'struct text_sample { unsigned int resource, offset, size; bool supported; std::uint64_t fingerprint; };',
           f'inline constexpr std::array<text_sample, {len(rows)}> text_samples{{{{']
    lines += [f'  {{{slot}, {offset}, {size}, {str(supported).lower()}, 0x{fingerprint:016x}}},' for slot,offset,size,supported,fingerprint in rows]
    lines += ['}};','']
    for i,raw in enumerate(extra):lines += [f'inline constexpr std::array<std::uint8_t, {len(raw)}> text_extra_{i}{{'+', '.join(map(str,raw))+'};']
    lines += ['','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/text_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} page/control cases; {sum(not r[3] for r in rows)} contain original codes outside the font directory.')


if __name__=='__main__':main()
