#!/usr/bin/env python3
"""Execute native 9185 launcher guards and CAF0 paired launch accounting."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args = parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    raw = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    rng = random.Random(0x9185)
    rows = []
    for i in range(4096):
        direction = rng.randrange(4)*2
        quarter = direction//2
        column,row = rng.choice((0,1,30,60,126,127)),rng.choice((0,1,30,60,126,127))
        position = [column*256+128,row*256+128,128]
        back = rng.choice((-3000,-1,0,1,32,300,1000,2000,3000))
        side = rng.choice((-1000,-300,-100,-1,0,1,100,300,1000))
        dx,dy = ((side,back),(back,-side),(-side,-back),(-back,side))[quarter]
        player = [(position[0]+dx)&65535,(position[1]+dy)&65535,rng.choice((0,64,1000,8000,16000,65535))]
        difficulty = rng.choice((0,1,96,128,255))
        delay = (((0x2ff^difficulty)<<3)-1024)&65535
        elapsed = rng.choice((0,767,768,769,delay-1,delay,delay+1,65535))
        clock = rng.randrange(65536)
        last = (clock-elapsed)&65535
        phase = rng.choice((0,1,127,128,254,255))
        free = int(i%5 != 0)
        slot = 31 if i%13 == 0 else 32
        markers = [rng.choice((255,255,255,0,128,254)) for _ in range(2)]
        h = Harness(raw)
        obj = bytearray(112)
        struct.pack_into('<3H',obj,8,*position)
        struct.pack_into('<H',obj,0x44,0x1926+slot*24)
        struct.pack_into('<H',obj,0x6a,last)
        obj[0x50] = phase
        h.cpu.mem_write(h.STACK+0xd000,bytes(obj))
        h.cpu.mem_write(h.STACK+0xd98e,struct.pack('<3H',*player))
        h.write(0xbf0,struct.pack('<H',clock))
        h.write(0x3dc5,bytes([difficulty]))
        h.write(0x6fc4,struct.pack('<H',0xdb00 if free else 0))
        h.write(0xfdf0,struct.pack('<H',0x6000))
        h.cpu.mem_write(0x6a000,struct.pack('<H',0x1000))
        h.cpu.mem_write(0x6a004,b'\xff')
        cx,cy = column,row
        for n,marker in enumerate(markers):
            cx = (cx-(0,-1,0,1)[quarter])&255
            cy = (cy-(-1,0,1,0)[quarter])&255
            h.cpu.mem_write(0x6a00c+n*8,bytes([marker]))
            if cx < 128 and cy < 128:
                h.cpu.mem_write(0x60000+cy*256+cx*2,bytes([n+1,0]))
        fired = []
        def hook(cpu,address,size,data):
            if address == h.BASE+0xcb01:
                assert h.getreg('BX') == 0x1ad6 and h.getreg('AX') == 0xd986
                fired.append(h.getreg('DX'))
                h.setreg('IP',h.RETURN)
        h.cpu.hook_add(UC_HOOK_CODE,hook)
        h.setreg('BP',0xd000);h.setreg('DI',direction)
        h.call(0x9185)
        assert h.getreg('IP') == h.RETURN
        after = bytes(h.cpu.mem_read(h.STACK+0xd000,112))
        rows.append([slot,*position,direction,*player,phase,last,clock,difficulty,free,*markers,
                     after[0x50],int.from_bytes(after[0x6a:0x6c],'little'),int(bool(fired)),fired[0] if fired else 0])
    lines = ['#pragma once','','// Generated by tools/generate_vehicle_combat_reference.py; native 9185/CAF0',
             '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
             f'inline constexpr std::array<std::array<unsigned int,19>,{len(rows)}> vehicle_combat_samples{{{{']
    lines += ['  {'+','.join(map(str,row))+'},' for row in rows]
    lines += ['}};','']
    routes = []
    for action in range(10):
        for heading in (0,0x4000,0x8000,0xc000):
            for phase in (0,512,2048,4000):
                h = Harness(raw)
                obj = bytearray(112)
                struct.pack_into('<3H',obj,8,14720,20608,128)
                struct.pack_into('<H',obj,0x2a,heading)
                obj[0x52] = action
                h.cpu.mem_write(h.STACK+0xd000,bytes(obj))
                h.write(0xbf8,struct.pack('<H',phase))
                h.write(0x3142,struct.pack('<H',0x7000))
                called = []
                def route_hook(cpu,address,size,data):
                    entry = address-h.BASE
                    if entry not in (0x9185,0x67bf,0x6815,0x6742):
                        return
                    if entry == 0x9185:
                        called.append(h.getreg('DI'))
                    sp = h.getreg('SP')
                    h.setreg('IP',int.from_bytes(cpu.mem_read(h.STACK+sp,2),'little'))
                    h.setreg('SP',sp+2)
                h.cpu.hook_add(UC_HOOK_CODE,route_hook)
                h.setreg('BP',0xd000)
                h.call(0x8f3b)
                assert h.getreg('IP') == h.RETURN and len(called) <= 1
                routes.append([action,heading,phase,called[0] if called else 255])
    lines += [f'inline constexpr std::array<std::array<unsigned int,4>,{len(routes)}> vehicle_firing_route_samples{{{{']
    lines += ['  {'+','.join(map(str,row))+'},' for row in routes]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/vehicle_combat_samples.h').write_text('\n'.join(lines))
    print('Captured',len(rows),'launcher cases;',sum(row[17] for row in rows),'successful allocations.')


if __name__ == '__main__':
    main()
