#!/usr/bin/env python3
"""Capture native per-object clock, position snapshot and projectile callback ordering."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')

    class Update(Harness):
        expired = False
        expected_step = 0

        def hook(self, cpu, address, size, data):
            offset = address-self.BASE
            if offset == 0x7a2d:
                assert self.getreg('CX') == self.expected_step
            if offset in (0x7a30, 0x7a52):
                self.expired = offset == 0x7a52
                self.setreg('IP', self.RETURN)
                return
            super().hook(cpu, address, size, data)

    native = Update(raw)
    native.write(0x9c4a, raw[0x944a:0x964a])
    native.write(0x5000, raw[0x1926:0x193e])
    samples = []
    for callback in (0xcc64, 0xcc61):
        for mode in range(5):
            for target_kind in range(3):
                flags, lifetime, altitude = [(0x20, 128, 8192), (0x20, 1024, 0x5000), (0x40, 128, 8192), (0, 32, 65535), (0x20, 0, 8192)][mode]
                state = bytearray(112)
                state[4:7] = bytes([255, 127, 1])
                state[7] = flags
                state[8:14] = struct.pack('<3H', 0, 65535, altitude)
                state[0x26:0x2a] = struct.pack('<2H', 100, 65535)
                state[0x2a:0x30] = struct.pack('<3H', 8192, 4096, 1234)
                state[0x30:0x32] = struct.pack('<H', 480)
                state[0x38:0x3e] = struct.pack('<3H', 0x1111, 0x2222, 0x3333)
                state[0x3e:0x40] = struct.pack('<H', 1000)
                state[0x44:0x46] = struct.pack('<H', 0x5000)
                state[0x66:0x6a] = struct.pack('<2H', callback, (65500+lifetime) & 65535)
                state[0x6c:0x6e] = struct.pack('<H', 0xd000 if target_kind == 2 else 0xd200)
                state[0x6f] = 123
                native.cpu.mem_write(native.STACK+0xd000, bytes(state))
                clock = 65500
                for tick in range(24):
                    step = (1, 4, 16, 64)[tick % 4]
                    clock = (clock+step) & 65535
                    target = (4096+tick*17 if target_kind == 1 else 4096, 16384, 4096)
                    native.cpu.mem_write(native.STACK+0xd208, struct.pack('<3H', *target))
                    native.write(0xbf0, struct.pack('<H', clock))
                    native.expected_step = step
                    native.write(0x7a2b, struct.pack('<H', step))
                    # The timestep is an instruction operand: invalidate translated code after patching.
                    native.cpu.ctl_remove_cache(native.BASE+0x7a2a, native.BASE+0x7a30)
                    native.setreg('BP', 0xd000)
                    native.call(0x79e5)
                    result = bytes(native.cpu.mem_read(native.STACK+0xd000, 112))
                    out = [*struct.unpack('<3H', result[8:14]), *result[4:7], *struct.unpack('<5H', result[0x26:0x30]),
                           int.from_bytes(result[0x3e:0x40], 'little'), *struct.unpack('<3H', result[0x38:0x3e]),
                           result[7], result[0x6f], int.from_bytes(result[0x68:0x6a], 'little'), int(native.expired)]
                    samples.append([callback, mode, target_kind, tick, clock, step, *target, *out])
                    if native.expired:
                        break
    lines = ['#pragma once', '', '// Generated by tools/generate_update_reference.py; native 79E5 through callback return',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct update_frame_sample { int callback, mode, target_kind, tick, clock, step; std::array<int, 3> target; std::array<int, 19> result; };',
             f'inline constexpr std::array<update_frame_sample, {len(samples)}> update_frame_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row[:6])) + ', {' + ', '.join(map(str, row[6:9])) + '}, {' + ', '.join(map(str, row[9:])) + '}},' for row in samples]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/update_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(samples)} native update frames across 30 sequences.')


if __name__ == '__main__':
    main()
