#!/usr/bin/env python3
"""Capture native owner registration and repeated script/message context exchange."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from verify_mission_activation import Probe
    image=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(image).hexdigest()==IMAGE_SHA256
    owners=[];exchanges=[]
    for clock in (0,1000,32768,65535):
        for old in (0,0xd9f6,0xda66):
            h=Probe();h.write(0xf100,b'\x24');h.word(0x3e8c,old);h.put(0x5e,clock)
            result=h.update(clock)
            owners.append((clock,old,h.word(0x3e8c),h.get(0x5a),result['deadline'],int(result['resume']==0xc50f)))
        h=Probe();h.write(0xf100,b'\x26\x23');h.write(0xf200,b'\x0c\x01\x00\x26\x23');h.put(0x5e,clock)
        h.word(0xc789,0xf200);h.word(0xc77f,0xf500);h.word(0xc059,0xf400);h.write(0x7e61,b'\0');h.write(0xf500,b'\x18\x03ABC');h.cpu.mem_write(h.STACK+h.BP+7,b'\0')
        result=h.update(clock)
        assert result['dispatches']==[0xf100,0xf200,0xf203,0xf101]
        exchanges.append((clock,result['deadline'],h.word(0xc059)-0xf400,h.word(0xc77f)-0xf500,
                          h.word(0xc789)-0xf200,h.read(0x7e61)[0],int(result['resume']==0xc50f),h.word(0x30a)+1-0xf500,h.word(0x30e)))
    lines=['#pragma once','','// Generated by tools/generate_mission_exchange_reference.py; original C2E4/C77E',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','']
    for name,rows in [('mission_owner_samples',owners),('mission_exchange_samples',exchanges)]:
        lines += [f'inline constexpr std::array<std::array<int, {len(rows[0])}>, {len(rows)}> {name}{{{{']
        lines += ['  {'+', '.join(map(str,row))+'},' for row in rows]
        lines += ['}};','']
    lines += ['} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/mission_exchange_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(owners)} native owner registrations and {len(exchanges)} consecutive exchange traces.')


if __name__=='__main__':main()
