#!/usr/bin/env python3
"""Extract the original three language menu tables without Unicode substitution."""
import argparse
import hashlib
import struct
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('workspace', type=Path)
root = parser.parse_args().workspace
image = (root / 'analysis/unpacked/image.bin').read_bytes()
assert hashlib.sha256(image).hexdigest() == '7599201a01aa24b7e6ad1ae4295d493821cde7c3a43b247c464522626c0380a4'

def string(address):
    return image[address:image.index(0,address)]

def literal(value):
    return '"' + ''.join(chr(c) if 32 <= c < 127 and c not in (34,92) else '\\%03o' % c for c in value) + '"'

def positioned(address):
    value = string(address)
    return '{' + str(value[0]) + ', ' + literal(value[1:]) + '}'

# Native language directories at E3E2, E5D3 and E80E; strings retain custom font codes.
rows = [
 (0xe553,0xe56f,0xe576,0xe5c1,0xe41e,0xe477,0xe4a8,0xe57f,0xe598,0xe5a1,0xe518,0xe5a4,0xe5b0),
 (0xe77c,0xe79e,0xe7a5,0xe7f4,0xe61d,0xe67e,0xe6b3,0xe7af,0xe7c7,0xe7d0,0xe738,0xe7d4,0xe7df),
 (0xe9d0,0xe9f5,0xe9fd,0xea4c,0xe868,0xe8be,0xe8fb,0xea06,0xea1e,0xea27,0xe984,0xea2c,0xea3c),
]
# The name-entry block uses embedded move commands, not separate NUL strings.
name_blocks = [0xe525,0xe74a,0xe993]
lines = ['#pragma once', '', '// Generated by generate_menu_text.py; original glyph bytes and authored X positions.',
 '#include <array>', '#include <string_view>', '', 'namespace darker::presentation {', '',
 'struct menu_line { int x; std::string_view text; };',
 'struct menu_text {',
 '  std::string_view select, game, level, new_game;',
 '  menu_line name_title, name_prompt;',
 '  std::array<menu_line,4> actions;',
 '  std::array<menu_line,3> erase, erase_score;',
 '  std::string_view question, yes, no;',
 '  menu_line quit;',
 '  std::string_view score, best_score;',
 '};', '', 'inline constexpr std::array<menu_text,3> original_menu_text{{']
for row,block in zip(rows,name_blocks):
    select,game,level,new,actions,erase,erase_score,question,yes,no,quit,score,best = row
    # Skip colour command 02 00 7D and Y move 01 B0; X follows.
    a = block + 5
    z = image.index(1,a)
    name_title = '{' + str(image[a]) + ', ' + literal(image[a+1:z]) + '}'
    name_prompt = positioned(z+2)
    def list_lines(address,count):
        result=[]
        for _ in range(count):
            result.append(positioned(address))
            address=image.index(0,address)+1
        return '{{' + ', '.join(result) + '}}'
    # Erasure messages are exactly three authored rows in every language.
    values=[literal(string(select)),literal(string(game)[:-1]),literal(string(level)[:-1]),literal(string(new)),
      name_title,name_prompt,list_lines(actions,4),list_lines(erase,3),list_lines(erase_score,3),
      literal(string(question)),literal(string(yes).split(bytes([2]))[0].rstrip()),literal(string(no)),
      positioned(quit-1),literal(string(score)),literal(string(best))]
    lines.append('  {' + ', '.join(values) + '},')
lines += ['}};', '', 'inline constexpr std::array<std::string_view,3> original_credits{{']
# 9D7A selects a formatted page, whose centred lines have their own terminators.
def page_end(address):
    while True:
        command = image[address]
        address += 1
        if command == 0:
            return address
        if command in (1, 2, 5):
            address += 2
        elif command == 6:
            address = page_end(address)

for address in struct.unpack_from('<3H', image, 0x9d7a):
    page = image[address:page_end(address)]
    lines.append('  std::string_view{' + literal(page) + ', ' + str(len(page)) + '},')
lines += ['}};', '', '} // namespace darker::presentation', '']
(Path(__file__).resolve().parents[1] / 'src/presentation/menu_text.h').write_text('\n'.join(lines))
