#!/usr/bin/env python3
"""Execute CDB9 against shipped Delphi model links and projectile definition classes."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args = parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from verify_player_collisions import setup
    from unicorn import UC_HOOK_CODE
    raw = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    h,bank,tail = setup(30)
    decision = []
    def hook(cpu,address,size,data):
        if address in (h.BASE+0x67c1,h.BASE+0x680c):
            decision.append(address == h.BASE+0x67c1)
            h.setreg('IP',h.RETURN)
    h.cpu.hook_add(UC_HOOK_CODE,hook)
    rows = []
    for kind in (1,11,12,29,30,76,77,80,83,84,85,86,89,100,105):
        for state in (0,32,64,96,128,192):
            h.cpu.mem_write(0x612a0,bytes([kind,state]))
            h.setreg('DS',0x1000);h.setreg('BX',0x1250)
            h.call(0x2de1)
            linked = int.from_bytes(h.cpu.mem_read(0x70000+h.getreg('SI'),2),'little') != 0
            for slot in (0,5,8,10,14,18,25,32):
                for category in (0,1,2,3):
                    h.setreg('DS',0x1000)
                    h.write(0x6064,bytes([category]))
                    h.cpu.mem_write(h.STACK+0xd044,struct.pack('<H',0x1926+slot*24))
                    h.setreg('BP',0xd000);h.setreg('AX',0x1250);h.setreg('CX',128)
                    decision.clear()
                    h.call(0xcdb9)
                    assert h.getreg('IP') == h.RETURN and len(decision) == 1
                    rows.append([kind,state,slot,category,int(linked),int(decision[0])])
    lines = ['#pragma once','','// Generated by tools/generate_building_impact_reference.py; native CDB9 with bank 30',
             '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
             f'inline constexpr std::array<std::array<unsigned int,6>,{len(rows)}> building_impact_samples{{{{']
    lines += ['  {'+','.join(map(str,row))+'},' for row in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/building_impact_samples.h').write_text('\n'.join(lines))
    print('Captured',len(rows),'native building impact decisions.')


if __name__ == '__main__':
    main()
