#!/usr/bin/env python3
"""Capture native ground/static/air collision-list selection and unshortened impact endpoints."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('workspace',type=Path)
    root=p.parse_args().workspace.resolve();sys.path.insert(0,str(root/'tools'))
    from verify_player_collisions import setup
    assert hashlib.sha256((root/'analysis/unpacked/image.bin').read_bytes()).hexdigest()==IMAGE_SHA256
    h,bank,_=setup(30);h.cpu.mem_write(0x6a004,b'\xff')
    rng=random.Random(0x7008);rows=[]
    for case in range(512):
        start=[16000+rng.randrange(-300,301),16000+rng.randrange(-300,301),3000+rng.randrange(-512,513)]
        end=[16000+rng.randrange(-300,301),16000+rng.randrange(-300,301),3000+rng.randrange(-512,513)]
        expansion=rng.choice([0,2,12]);initial=[];categories=[0,1,2,0,1,2];rng.shuffle(categories)
        for n,category in enumerate(categories):
            bp=0xd000+n*112;slot=[19,29,30][category];position=[16000+rng.randrange(-200,201),16000+rng.randrange(-200,201),3000+rng.randrange(-512,513)]
            flags=rng.choice([0,8,16,32,40]);obj=bytearray(112);obj[7]=flags
            after=next((j for j in range(n+1,6) if categories[j]==category),None)
            struct.pack_into('<H',obj,0,0xd000+after*112 if after is not None else 0)
            struct.pack_into('<3H',obj,8,*position);struct.pack_into('<H',obj,0x22,bank['special_offsets'][slot]+0x400)
            h.cpu.mem_write(h.STACK+bp,bytes(obj));initial += [category,slot,flags,*position]
        for category,address in [(0,0x6fd8),(1,0x6fc8),(2,0x6fb0)]:h.write(address,struct.pack('<H',0xd000+categories.index(category)*112))
        h.write(0x60c3,struct.pack('<H',expansion));h.write(0x652d,struct.pack('<H',10));h.write(0x6d77,struct.pack('<H',0x80))
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);h.setreg('DS',0x1000)
        for register,value in [('AX',start[0]),('BX',start[1]),('DI',start[2]>>1),('CX',end[0]),('DX',end[1]),('BP',end[2]>>1),('SI',0x7008)]:h.setreg(register,value)
        h.call(0x6d35);flags=h.getreg('EFLAGS');hit=bool(flags&1) and not bool(flags&64)
        victim=(h.getreg('BX')-0xd000)//112 if hit else -1
        h.call(0x6705);impact=[h.getreg(r) for r in ('DX','BX','CX')]
        rows.append([expansion,*start,*end,*initial,victim,*impact])
    width=len(rows[0]);lines=['#pragma once','','// Generated by tools/generate_actor_sweep_reference.py; native 6D35/6D60/6705',
      '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
      f'inline constexpr std::array<std::array<int,{width}>,{len(rows)}> actor_sweep_samples{{{{']
    lines+=['  {'+','.join(map(str,row))+'},' for row in rows];lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/actor_sweep_samples.h').write_text('\n'.join(lines))
    print('Captured',len(rows),'mixed collision-list sweeps;',sum(r[-4]>=0 for r in rows),'hits.')


if __name__=='__main__':main()
