#!/usr/bin/env python3
"""Capture Caero launch placement and gate departure state from BD34/C5F9."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    raw=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    h=Harness(raw)
    h.write(0xfdf0,struct.pack('<H',0x3000))
    h.write(0x3142,struct.pack('<H',0x7000))
    h.write(0xf003,b'\1')
    def stop(cpu,address,size,_):
        if address==h.BASE+0xbd98:h.setreg('IP',h.RETURN)
    h.cpu.hook_add(UC_HOOK_CODE,stop)
    rows=[];starts=[];rng=random.Random(0xC6D2)
    for i in range(512):
        column,row=rng.randrange(5,123),rng.randrange(5,123)
        site=row*256+column*2
        cells=bytearray(32768)
        cells[site]=17
        h.cpu.mem_write(0x30000,bytes(cells))
        h.write(0xc81e,struct.pack('<H',site))
        destination = 0x3064 if i % 2 else site
        h.write(0xc610,struct.pack('<H',destination))
        obj=bytearray(112);obj[0x22:0x24]=struct.pack('<H',0x400)
        h.cpu.mem_write(h.STACK+0xd986,bytes(obj))
        height=rng.choice([-104,0,104,-200,2048])
        h.cpu.mem_write(0x70407,struct.pack('<h',height))
        h.setreg('BP',0xd986);h.setreg('DS',0x1000)
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        h.call(0xbd34)
        state=bytes(h.cpu.mem_read(h.STACK+0xd986,112))
        flags=state[7]
        changes=[h.cpu.mem_read(0x30000+site+d+1,1)[0] for d in (-256,0,256)]
        assert changes==[128]*3,(i,site,changes,h.getreg("DI"),h.getreg("ES"),h.read(0xf003))
        starts.append((site,height,*struct.unpack_from('<3H',state,8),*struct.unpack_from('<3H',state,0x2a),flags))
        kind=rng.choice([0,17,18,19,20,21,22,23,24,77])
        x,y=column*256+128+rng.randrange(-600,601),row*256+152+rng.randrange(-600,601)
        if x//256==column and y//256==row and kind!=17:y+=256
        gate=rng.choice([0,0xe800,0xffff,rng.randrange(65536)])
        step=rng.randrange(81)
        obj[7]=16;obj[8:12]=struct.pack('<2H',x&65535,y&65535)
        h.cpu.mem_write(h.STACK+0xd986,bytes(obj))
        h.cpu.mem_write(0x30000,bytes(cells))
        h.cpu.mem_write(h.STACK+0x7935,struct.pack('<H',gate))
        h.write(0x3708,b'\x35');h.write(0x7a2b,struct.pack('<H',step))
        h.setreg('BP',0xd986);h.setreg('DS',0x1000);h.setreg('ES',0x3000);h.setreg('AX',kind)
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        h.call(0xc5f9)
        resultgate=int.from_bytes(h.cpu.mem_read(h.STACK+0x7935,2),'little')
        resultflags=h.cpu.mem_read(h.STACK+0xd98d,1)[0]
        sound=h.read(0x3708)[0]
        changes=[h.cpu.mem_read(0x30000+site+d+1,1)[0] for d in (-256,0,256)]
        assert changes==([128]*3 if kind not in range(17,25) else [0]*3)
        rows.append((site,kind,x&65535,y&65535,gate,step,resultgate,resultflags,sound,destination,int.from_bytes(h.read(0xc81e,2),'little')))
    lines=['#pragma once','','// Generated by tools/generate_hangar_reference.py; native BD34 and C5F9',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           'struct hangar_start_sample { int site, model_height; std::array<int, 3> position, angles; int flags; };',
           f'inline constexpr std::array<hangar_start_sample, {len(starts)}> hangar_start_samples{{{{']
    lines += ['  {'+f'{v[0]}, {v[1]}, '+'{'+', '.join(map(str,v[2:5]))+'}, {'+', '.join(map(str,v[5:8]))+'}, '+str(v[8])+'},' for v in starts]
    lines += ['}};','','struct hangar_departure_sample { int site, type, x, y, gate, step, result, flags, sound, destination, return_site; };',
              f'inline constexpr std::array<hangar_departure_sample, {len(rows)}> hangar_departure_samples{{{{']
    lines += ['  {'+', '.join(map(str,row))+'},' for row in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/hangar_samples.h').write_text('\n'.join(lines))
    print('Captured 512 launch placements and 512 gate/departure cases.')


if __name__=='__main__':main()
