#!/usr/bin/env python3
"""Capture native collision stream decoding with original geometry banks."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from verify_player_collisions import setup
    from unicorn import UC_HOOK_CODE
    image=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest()!=IMAGE_SHA256:raise ValueError('Unsupported unpacked executable')
    cases=[]
    for slot in (30,31,32):
        h,parsed,tail=setup(slot)
        h.write(0x2e10,bytes([0x40 if slot==30 else 0xc0]))
        boxes=[]
        def capture(cpu,address,size,data):
            if address-h.BASE==0x60d4:
                boxes.append([h.getreg(r) for r in ('BP','BX','DI','CX','DX','SI')]+[h.read(0x606f)[0]>>3])
                # The decoder has pushed the primitive test's return address.
                # Skip intersection only, returning carry as a rejected hit.
                h.setreg('SP',h.getreg('SP')+2)
                h.setreg('EFLAGS',3)
                h.setreg('IP',0x606c)
        h.cpu.hook_add(UC_HOOK_CODE,capture)
        for kind in parsed['types']:
            for state in (0,32,64,128):
                for expansion in (0,7):
                    boxes.clear()
                    if kind['collision_marker']!=255:
                        h.setreg('DS',0x1000)
                        h.cpu.mem_write(0x61428,bytes([kind['type'],state]))
                        h.setreg('BX',0x1414)
                        h.call(0x2de1)
                        model=h.getreg('SI');x=h.getreg('AX');y=h.getreg('BX')
                        pointer=int.from_bytes(h.cpu.mem_read(0x70000+model+4,2),'little')
                        for at,value in ((0x60a0,x),(0x60b8,y),(0x607b,kind['collision_marker']*32),(0x60c3,expansion)):
                            h.write(at,struct.pack('<H',value))
                        h.setreg('DS',0x1000);h.setreg('SI',pointer)
                        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
                        h.call(0x607a)
                    fingerprint=0xcbf29ce484222325
                    for box in boxes:
                        for value in box:
                            for byte in (value&255,value>>8):fingerprint=((fingerprint^byte)*0x100000001b3)&0xffffffffffffffff
                    cases.append([slot,kind['type'],state,expansion,len(boxes),fingerprint])
        print('Captured bank',slot,flush=True)
    lines=['#pragma once','','// Generated by tools/generate_city_collision_reference.py; native 607A–60D2',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','#include <cstdint>','','namespace darker::test_reference {','',
           'struct city_collision_sample { unsigned int slot, type, state, expansion, count; std::uint64_t fingerprint; };',
           f'inline constexpr std::array<city_collision_sample, {len(cases)}> city_collision_samples{{{{']
    lines+=['  {'+', '.join(map(str,case[:-1]))+f', 0x{case[-1]:016x}'+'},' for case in cases]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/city_collision_samples.h').write_text('\n'.join(lines))


if __name__=='__main__':main()
