#!/usr/bin/env python3
"""Capture native transient record allocation, oldest eviction and free-list reuse."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(image).hexdigest() == IMAGE_SHA256
    h = Harness(image)
    word = lambda x: struct.pack('<H',x)
    pointer = lambda slot: 0xe000+slot*20
    read = lambda at: int.from_bytes(h.read(at,2),'little')
    node = lambda at: int.from_bytes(h.cpu.mem_read(h.STACK+at,2),'little')
    for slot in range(16): h.cpu.mem_write(h.STACK+pointer(slot),word(pointer(slot+1) if slot<15 else 0))
    h.write(0x6f98,struct.pack('<4H',0,0,pointer(0),0))
    def active():
        result=[]; at=read(0x6f98)
        while at:
            result.append(at);at=node(at)
            assert len(result)<=16
        return result
    rng=random.Random(0x1cbf);rows=[]
    for n in range(512):
        mask=0
        if n%64<40:
            h.setreg('DI',0x6f98);h.call(0x1cbf)
        else:
            selected=rng.sample(active(),min(len(active()),rng.randrange(1,5)))
            mask=sum(1<<((at-0xe000)//20) for at in selected)
            for at in active():
                if at in selected:
                    h.setreg('DI',0x6f98);h.setreg('BP',at);h.call(0x1cd4)
        values=[(at-0xe000)//20+17 for at in reversed(active())]
        rows.append([int(n%64<40),mask,len(values),*values,*([0]*(16-len(values)))])
    lines=['#pragma once','','// Native 1CBF/1CD4 with a 16-record free chain; generated by generate_sound_pool_reference.py.',
           '// Image SHA-256: '+IMAGE_SHA256,'#include <array>','namespace darker::test_reference {',
           'inline constexpr std::array<std::array<unsigned int,19>,512> sound_pool_samples{{']
    lines+=['  {'+', '.join(map(str,row))+'},' for row in rows]
    lines+=['}};','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/sound_pool_samples.h').write_text('\n'.join(lines))
    print('Captured 512 native pool operations including repeated saturation, retirement and reuse')


if __name__=='__main__': main()
