#!/usr/bin/env python3
"""Capture C9C2 firing guards, target requirements and surface/underground energy costs."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    image = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(image).hexdigest() == IMAGE_SHA256
    rows = []
    cases = [(selection, energy, flags, trigger, free, 0xffff, 0)
             for selection in (1,2)
             for energy in (0,6398,6399,6400,7422,7423,7424,53247,65535)
             for flags in (0,2,16,32,48) for trigger in (0,1) for free in (0,1)]
    for selection in (1,2,6,8,10):
        for mode in (0,2):
            cost = 0x80ff if mode == 2 else image[0x190e+selection*24+10]*256+255
            cases.extend((selection, energy, flags, trigger, free, target, mode)
                         for energy in (cost-1,cost,cost+1,65535)
                         for flags in (0,16) for trigger in (0,1) for free in (0,1)
                         for target in (0xffff,0xd986,0xec00,0x1234,0x7fff))
    for selection, energy, flags, trigger, free, target, mode in cases:
        h = Harness(image)
        h.write(0x7fa6, struct.pack('<H', energy))
        h.write(0x6fbc, struct.pack('<H', 0xd000 if free else 0))
        h.write(0xc9f7, struct.pack('<H', 0x40))
        h.write(0x6202, bytes([mode]))
        h.write(0x5f0f, struct.pack('<H',target))
        h.cpu.mem_write(h.STACK + 0xd98d, bytes([flags]))
        h.setreg('AL', selection); h.setreg('SI', 0x4545); h.setreg('DX', trigger * 0x40)
        fired = []
        def hook(cpu, address, size, data):
            if address == h.BASE + 0xcb01:
                fired.append(h.getreg('DX'))
                h.setreg('IP', h.RETURN)
        h.cpu.hook_add(UC_HOOK_CODE, hook)
        h.call(0xc9c2)
        assert h.getreg('IP') == h.RETURN
        rows.append([energy,flags,trigger,free,int.from_bytes(h.read(0x7fa6,2),'little'),
                     int(h.read(0x4545)[0] == 0),int(bool(fired)),fired[0] if fired else 0,selection,target,mode])
    lines = ['#pragma once', '', '// Generated by tools/generate_caero_weapon_reference.py; original C9C2/CAC0',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             f'inline constexpr std::array<std::array<int, 11>, {len(rows)}> caero_weapon_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row)) + '},' for row in rows]
    lines += ['}};', '', '// Native BCA4 world setup patches Pinner Direct strength at 192E.',
              'inline constexpr std::array<std::array<int,2>,2> pinner_world_strength_samples{{']
    for mode in (0,2):
        h = Harness(image)
        h.write(0x6202,bytes([mode]))
        def stop_setup(cpu,address,size,data):
            if address == h.BASE+0xbccb:
                h.setreg('IP',h.RETURN)
        h.cpu.hook_add(UC_HOOK_CODE,stop_setup)
        h.call(0xbca4)
        assert h.getreg('IP') == h.RETURN
        lines.append('  {'+str(mode)+','+str(h.read(0x192e)[0])+'},')
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/caero_weapon_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} original Caero firing cases.')


if __name__ == '__main__':
    main()
