#!/usr/bin/env python3
"""Capture native underground entry placement and portal speed/capture transitions."""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    root = parser.parse_args().workspace.resolve()
    sys.path.insert(0,str(root/'tools'))
    from verify_player_collisions import setup
    from unicorn import UC_HOOK_CODE
    raw = (root/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    h,bank,_ = setup(32)
    model = bank['special_offsets'][28]+0x400
    height = struct.unpack('<h',h.cpu.mem_read(0x70000+model+7,2))[0]
    h.write(0x1926+28*24,struct.pack('<H',model))
    h.write(0xf003,b'\x04');h.write(0x6202,b'\x02');h.write(0xb91f,b'\x19')
    def hook(cpu,address,size,data):
        if address == h.BASE+0xbd98:h.setreg('IP',h.RETURN)
    h.cpu.hook_add(UC_HOOK_CODE,hook)
    word = lambda value:struct.pack('<H',value & 65535)
    put = lambda at,value:h.cpu.mem_write(h.STACK+0xd986+at,word(value))
    get = lambda at:int.from_bytes(h.cpu.mem_read(h.STACK+0xd986+at,2),'little')
    value = lambda at:int.from_bytes(h.read(at,2),'little')
    entries,transitions = [],[]
    for record in json.loads((root/'analysis/missions/scenarios.json').read_text())['records']:
        if record.get('craft_configuration') != 4:continue
        op = next(i for i in record['instructions'] if i['opcode'] == 0x28)
        operands = bytes.fromhex(op['operands_hex'])
        site = int.from_bytes(operands[1:],'little')
        map_slot = record['map_resource']
        cells = bytearray(32768);cells[::2] = (root/f'analysis/resources/00_{map_slot:03}.bin').read_bytes()
        for heading in (0,64,128,192):
            h.cpu.mem_write(0x60000,bytes(cells));h.write(0x6fd0,bytes(6))
            h.write(0xc81e,word(site));h.write(0xbd56,bytes([heading]))
            h.setreg('DS',0x1000);h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);h.call(0xbd06)
            entries.append([map_slot,site,heading,height,*[get(at) for at in (8,10,12,0x2a,0x2c)],
                            h.cpu.mem_read(h.STACK+0xd98d,1)[0],value(0x7f20),value(0x7fa6),value(0x8540),get(0x62)])
        for column_delta in (-1,0,1):
            for row_delta in (-1,0,1,2,3):
                for route in (0,64,128,192):
                    for flags in (0,16):
                        column = ((site & 255)>>1)+column_delta;row = (site>>8)+row_delta
                        forward = (96,130,384)[len(transitions)%3]
                        lookahead = (0,64,172)[len(transitions)%3]
                        step = (1,8,32)[len(transitions)%3]
                        h.cpu.mem_write(0x60000,bytes(cells))
                        h.cpu.mem_write(h.STACK+0xd986,bytes(112))
                        put(8,column*256+128);put(10,row*256+128);put(0x66,0xd510)
                        h.cpu.mem_write(h.STACK+0xd98d,bytes([flags]));h.cpu.mem_write(h.STACK+0xd9f4,bytes([route]))
                        for at,v in ((0xc81e,site),(0xc610,site),(0x7f20,forward),(0xd27c,lookahead),(0x7a2b,step)):h.write(at,word(v))
                        h.cpu.mem_write(h.STACK+0x7935,word(0))
                        h.setreg('BP',0xd986);h.setreg('DS',0x1000)
                        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);h.call(0xc582)
                        changed=[h.cpu.mem_read(0x60000+site+delta+1,1)[0] for delta in (-256,0,256)]
                        transitions.append([map_slot,site,column,row,route,flags,forward,lookahead,step,
                                            h.cpu.mem_read(h.STACK+0xd98d,1)[0],value(0x7f20),value(0xd27c),get(0x66),
                                            int.from_bytes(h.cpu.mem_read(h.STACK+0x7935,2),'little'),*changed,value(0xc81e)])
    lines=['#pragma once','','// Generated by generate_tunnel_portal_reference.py; native BD06–BD98 and C582.',
           '#include <array>','','namespace darker::test_reference {','']
    for name,rows in (('tunnel_entry_samples',entries),('tunnel_portal_samples',transitions)):
        lines += [f'inline constexpr std::array<std::array<int,{len(rows[0])}>,{len(rows)}> {name}{{{{']
        lines += ['  {'+','.join(map(str,row))+'},' for row in rows]
        lines += ['}};','']
    lines += ['} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/tunnel_portal_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(entries)} tunnel entries and {len(transitions)} portal updates.')


if __name__ == '__main__':main()
