#!/usr/bin/env python3
"""Build compact C++ test fixtures from existing native HUD traces (development only)."""
import argparse
import hashlib
import json
from pathlib import Path
from format_cpp_initialisers import format_designated_initialisers


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1] / 'tests/reference/navigation_samples.h')
    args = parser.parse_args()
    compass_path = args.workspace / 'analysis/interface/sprites/procedural-hud.json'
    radar_path = args.workspace / 'analysis/interface/dynamic/verification.json'
    compass = json.loads(compass_path.read_text())['compass']['phases']
    radar = json.loads(radar_path.read_text())['radar_checks']
    lines = ['#pragma once', '', '// Generated by tools/generate_navigation_reference.py from original-code captures',
             '// Compass trace SHA-256: ' + hashlib.sha256(compass_path.read_bytes()).hexdigest(),
             '// Radar trace SHA-256: ' + hashlib.sha256(radar_path.read_bytes()).hexdigest(), '', '#include <array>',
             '#include "graphics/navigation_hud.h"', '', 'namespace darker::test_reference {', '',
             'inline std::array<std::array<graphics::pixel_position, 5>, 136> constexpr compass{{']
    assert len(compass) == 136
    for phase, frame in enumerate(compass):
        assert phase == frame['phase']
        lines.append('  {{' + ', '.join(f'{{{p["x"]}, {p["y"]}}}' for p in frame['draw']) + '}},')
    lines += ['}};', '', 'struct radar_sample {', '  std::uint16_t heading;', '  int x;', '  int y;',
              '  graphics::radar_group group;', '  std::optional<graphics::radar_pixel> pixel;', '};', '',
              f'inline std::array<radar_sample, {len(radar)}> const radar{{{{']
    for sample in radar:
        group = 'a' if sample['kind'] == 0 else 'b'
        pixel = '{}'
        if sample['points']:
            assert len(sample['points']) == 1
            x, y, colour = sample['points'][0]
            pixel = f'{{graphics::radar_pixel{{.position{{{x}, {y}}}, .colour{{{colour}}}}}}}'
        lines.append(f'  {{.heading{{{sample["heading"]}}}, .x{{{sample["x"]}}}, .y{{{sample["y"]}}}, .group{{graphics::radar_group::{group}}}, .pixel{pixel}}},')
    lines += ['}};', '', 'struct skimma_sample {', '  bool bearing;', '  unsigned int index;',
              '  std::uint8_t state;', '  std::uint64_t checksum;', '};', '']
    sprite_path = args.workspace / 'analysis/interface/sprites/sprites.json'
    assets = json.loads(sprite_path.read_text())['assets']
    samples = [a for a in assets if a['resource'] == 17 and a['category'] == 'callbacks'
               and (a['descriptor'] == 0x52e0 or a['source_state'] == 0)]
    lines += ['// Sprite geometry SHA-256: ' + hashlib.sha256(sprite_path.read_bytes()).hexdigest(),
              f'inline std::array<skimma_sample, {len(samples)}> constexpr skimma{{{{']
    cache = bytes((i * 17 + 3) % 251 for i in range(320 * 240))
    for asset in samples:
        screen = bytearray(cache)
        sx, sy, width, height = asset['source']
        dx, dy = asset['destination']
        for y in range(height):
            for x in range(width):
                if asset['coverage'][y * width + x]:
                    screen[(dy+y)*320+dx+x] = cache[(sy+y)*320+sx+x]
        checksum = 14695981039346656037
        for byte in screen:
            checksum = ((checksum ^ byte) * 1099511628211) & ((1 << 64) - 1)
        index = int(asset['id'].split('-')[-2])
        bearing = asset['descriptor'] == 0x5227
        state = index + 1 if bearing else asset['source_state']
        lines.append(f'  {{.bearing{{{str(bearing).lower()}}}, .index{{{index}}}, .state{{{state}}}, .checksum{{0x{checksum:016x}ULL}}}},')
    lines += ['}};', '', 'struct ring_sample {', '  std::uint8_t weapon;', '  std::uint8_t radius;',
              '  std::uint8_t remaining;', '  std::uint64_t checksum;', '};', '']
    procedural_path = args.workspace / 'analysis/interface/dynamic/procedural.json'
    procedural = json.loads(procedural_path.read_text())
    rings = procedural['verification']['ring_cases']
    lines += ['// Ring trace SHA-256: ' + hashlib.sha256(procedural_path.read_bytes()).hexdigest(),
              f'inline std::array<ring_sample, {len(rings)}> constexpr rings{{{{']
    for sample in rings:
        screen = bytearray(cache)
        for blit in sample['blits']:
            sx, sy = blit['source']
            dx, dy = blit['destination']
            for y, (skip, width) in enumerate(procedural['ring']['mask_rows']):
                for x in range(skip, skip + width):
                    screen[(dy+y)*320+dx+x] = cache[(sy+y)*320+sx+x]
        checksum = 14695981039346656037
        for byte in screen:
            checksum = ((checksum ^ byte) * 1099511628211) & ((1 << 64) - 1)
        lines.append(f'  {{.weapon{{{sample["weapon"]}}}, .radius{{{sample["radius"]}}}, .remaining{{{sample["count"]}}}, .checksum{{0x{checksum:016x}ULL}}}},')
    lines += ['}};', '']
    radar_graphics_path = args.workspace / 'analysis/interface/dynamic/radar-graphics.json'
    surround = json.loads(radar_graphics_path.read_text())['surround']
    lines += ['// Enlarged surround SHA-256: ' + hashlib.sha256(radar_graphics_path.read_bytes()).hexdigest(),
              'inline std::array<std::uint64_t, 256> constexpr enlarged_surround_checksums{']
    for heading in surround['heading_runs']:
        screen = bytearray(320 * 240)
        for x, y, width, colour in surround['base_runs'] + heading:
            screen[y*320+x:y*320+x+width] = bytes([colour]) * width
        checksum = 14695981039346656037
        for byte in screen:
            checksum = ((checksum ^ byte) * 1099511628211) & ((1 << 64) - 1)
        lines.append(f'  0x{checksum:016x}ULL,')
    enlarged = procedural['verification']['enlarged_radar_cases']
    lines += ['};', '', f'inline std::array<radar_sample, {len(enlarged)}> const enlarged_radar{{{{']
    for heading, x, y, kind, points in enlarged:
        pixel = '{}'
        if points:
            px, py, colour = points[0]
            pixel = f'{{graphics::radar_pixel{{.position{{{px}, {py+8}}}, .colour{{{colour}}}}}}}'
        group = 'a' if kind == 0 else 'b'
        lines.append(f'  {{.heading{{{heading}}}, .x{{{x}}}, .y{{{y}}}, .group{{graphics::radar_group::{group}}}, .pixel{pixel}}},')
    lines += ['}};', '', 'struct height_sample {', '  std::uint8_t height;', '  std::uint8_t reference;',
              '  int alignment;', '  std::uint64_t checksum;', '};', '']
    height_data = json.loads(radar_graphics_path.read_text())['height_contact']
    lines.append(f'inline std::array<height_sample, {len(height_data["checks"])}> constexpr heights' + '{{')
    for sample in height_data['checks']:
        screen = bytearray(cache)
        sx = height_data['source_x'][sample['alignment']]
        dx = 156 + sample['alignment']
        for y, (skip, width) in enumerate(height_data['mask_rows']):
            for x in range(skip, skip + width):
                screen[(81+y)*320+dx+x] = cache[(8+y)*320+sx+x]
        for x, y, _ in procedural['enlarged_symbol']['pixels']:
            screen[(81+y)*320+dx+x] = sample['colour']
        checksum = 14695981039346656037
        for byte in screen:
            checksum = ((checksum ^ byte) * 1099511628211) & ((1 << 64) - 1)
        lines.append(f'  {{.height{{{sample["height"]}}}, .reference{{{sample["reference"]}}}, .alignment{{{sample["alignment"]}}}, .checksum{{0x{checksum:016x}ULL}}}},')
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    args.output.write_text(format_designated_initialisers('\n'.join(lines)))


if __name__ == '__main__':
    main()
