#!/usr/bin/env python3
"""Capture original model disc spans and world-line clipping."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256
from native_flat_model import fingerprint


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    class Disc(Harness):
        def __init__(self, image):
            super().__init__(image)
            self.pixels = bytearray(320*240)
        def hook(self, cpu, address, size, data):
            if address-self.BASE == 0xa71e:
                row, left, count = self.getreg('BP')//256, self.getreg('SI'), self.getreg('CX')
                assert row < 240 and left+count <= 320
                self.pixels[row*320+left:row*320+left+count] = bytes([73])*count
                self.setreg('IP', 0xa731)
                return
            if address-self.BASE == 0xdbea:
                x, y = self.getreg('DX'), self.getreg('DI')
                assert x<320 and y<240
                self.pixels[y*320+x] = 73
                sp = self.getreg('SP')
                ip = int.from_bytes(cpu.mem_read(self.STACK+sp, 2), 'little')
                self.setreg('SP', sp+2); self.setreg('IP', ip)
                return
            super().hook(cpu, address, size, data)
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    random_source = random.Random(0xa5c0)
    discs = []
    for radius in (0, 1, 2, 3, 4, 5, 8, 16, 32, 64, 127, 255, 256, 1024):
        for x, y in ((160, 100), (0, 0), (319, 167), (-10, 50), (320, 100), (100, -10), (100, 200), (-300, 0)):
            for bottom in (168, 240):
                native = Disc(image)
                word = lambda at, value: native.write(at, struct.pack('<H', value & 65535))
                native.write(0, struct.pack('<240H', *[y*256 for y in range(240)]))
                word(0xfdec, 0x1000); word(0xfdf4, 0xa000); word(0xa296, bottom)
                for register, value in [('AX', radius), ('CX', 1), ('BP', x&65535), ('DI', y&65535)]:
                    native.setreg(register, value)
                native.call(0xa5c0)
                discs.append((x, y, radius, bottom, fingerprint(native.pixels)))
    lines = []
    boundaries = [(0, 0, 319, 168), (0, 168, 319, 168), (-1, 168, 319, 167), (160, -1, 160, 240)]
    points = boundaries+[tuple(random_source.randrange(-16000, 16001) for _ in range(4)) for _ in range(508)]
    points += [tuple(random_source.randrange(-320, 640) for _ in range(4)) for _ in range(512)]
    for point in points:
        native = Harness(image)
        native.write(0xa296, struct.pack('<H', 168))
        for register, value in zip(('SI', 'DI', 'AX', 'CX'), point):
            native.setreg(register, value&65535)
        native.call(0xa86d)
        visible = bool(native.getreg('EFLAGS')&64)
        signed = lambda value: (value+32768)%65536-32768
        result = [signed(native.getreg(register)) for register in ('SI', 'DI', 'AX', 'CX')]
        lines.append((point, visible, result))
    output = ['#pragma once', '', '// Generated by tools/generate_screen_primitives_reference.py; original A5C0 / A86D',
              '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
              'struct disc_sample { int x, y, radius, bottom; std::uint64_t fingerprint; };',
              f'inline constexpr std::array<disc_sample, {len(discs)}> disc_samples{{{{']
    output += ['  {'+', '.join(map(str, row[:-1]))+f', 0x{row[-1]:016x}'+'},' for row in discs]
    output += ['}};', '', 'struct line_clip_sample { std::array<int, 4> input; bool visible; std::array<int, 4> result; };',
               f'inline constexpr std::array<line_clip_sample, {len(lines)}> line_clip_samples{{{{']
    output += ['  {{'+', '.join(map(str, point))+'}, '+str(visible).lower()+', {'+', '.join(map(str, result))+'}},' for point, visible, result in lines]
    output += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/screen_primitives_samples.h').write_text('\n'.join(output))
    print(f'Captured {len(discs)} native discs and {len(lines)} line clipping cases.')


if __name__ == '__main__':
    main()
