#!/usr/bin/env python3
"""Capture original timer accumulation and frame consumption, excluding hardware polling."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    image=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest()!=IMAGE_SHA256:raise ValueError('Unsupported unpacked executable')
    rng=random.Random(0xbef);cases=[];h=Harness(image)
    fields=(0xbf0,0xbf8,0xc4e,0xc50)
    for index in range(1024):
        limit=rng.choice((0,1,80,65535));running=rng.randrange(2);interrupts=rng.randrange(201);consume=rng.randrange(2)
        before=[rng.randrange(65536) for _ in range(4)]+[rng.randrange(256)]
        for at,value in zip(fields,before):h.write(at,struct.pack('<H',value))
        h.write(0x3db3,bytes([before[4]]));h.write(0xbfb,struct.pack('<H',limit));h.write(0xbf5,bytes([running]))
        h.setreg('DS',0x1000);h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        for _ in range(interrupts):h.cpu.emu_start(h.BASE+0xbef,h.BASE+0xc0f,count=100)
        step=0
        if consume:
            h.cpu.emu_start(h.BASE+0xb0ce,h.BASE+0xb0ea,count=100)
            step=int.from_bytes(h.read(0x7a2b,2),'little')
        after=[int.from_bytes(h.read(at,2),'little') for at in fields]+[h.read(0x3db3)[0]]
        cases.append(([limit,running,interrupts,consume],before,after,step))
    lines=['#pragma once','','// Generated by tools/generate_game_clock_reference.py; native 0BEF–0C0E and B0CE–B0E9',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           'struct game_clock_sample { std::array<int, 4> input; std::array<int, 5> before, after; int step; };',
           f'inline constexpr std::array<game_clock_sample, {len(cases)}> game_clock_samples{{{{']
    for args,before,after,step in cases:
        lines.append('  {'+', '.join(['{'+', '.join(map(str,part))+'}' for part in (args,before,after)]+[str(step)])+'},')
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/game_clock_samples.h').write_text('\n'.join(lines))
    print('Captured',len(cases),'native clock sequences.')


if __name__=='__main__':main()
