#!/usr/bin/env python3
"""Capture native tunnel entry, flight, collision and portal updates at two frame rates."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def capture(root, step):
    from verify_player_collisions import setup
    from unicorn import UC_HOOK_CODE

    h, bank, _ = setup(32)
    cells = bytearray(32768)
    cells[::2] = (root/'analysis/resources/00_070.bin').read_bytes()
    h.cpu.mem_write(0x60000, bytes(cells))
    word = lambda value: struct.pack('<H', value & 65535)
    get = lambda at: int.from_bytes(h.cpu.mem_read(h.STACK + 0xd986 + at, 2), 'little')
    value = lambda at: int.from_bytes(h.read(at, 2), 'little')
    h.write(0xf003, b'\x04')
    h.write(0x6202, b'\x02')
    h.write(0xc81e, word(0x3064))
    h.write(0xbd56, b'\x80')
    h.write(0x1926 + 28*24, word(bank['special_offsets'][28] + 0x400))
    h.write(0x6fd0, bytes(6))

    def hook(cpu, address, size, data):
        if address == h.BASE + 0xbd98:
            h.setreg('IP', h.RETURN)
    h.cpu.hook_add(UC_HOOK_CODE, hook)
    h.write(0xfdf2, word(0x4000))
    h.cpu.mem_write(0x80000, (root/'analysis/resources/00_078.bin').read_bytes())
    h.setreg('DS', 0x8000)
    h.setreg('SI', 0)
    h.setreg('SP', 0xfefe)
    h.cpu.mem_write(h.STACK + 0xfefe, word(h.RETURN))
    h.cpu.emu_start(h.BASE + 0xd0be, h.BASE + h.RETURN, count=1000000)
    assert h.getreg('IP') == h.RETURN
    h.setreg('DS', 0x1000)
    h.cpu.emu_start(h.BASE + 0x3c17, h.BASE + 0x3c2f, count=1000)
    assert h.getreg('IP') == 0x3c2f
    h.write(0xb91f, b'\x19')
    h.write(0xc610, word(0x3064))
    h.write(0x4552, b'\x01')
    h.write(0x2e10, b'\xc0')
    h.call(0xbd06)
    assert h.getreg('IP') == h.RETURN
    rows = []
    for frame in range(1, 1001):
        clock = frame*step
        h.write(0xbf0, word(clock))
        h.write(0xbf8, word(clock))
        h.write(0x7a2b, word(step))
        for at in (8, 10, 12):
            h.cpu.mem_write(h.STACK + 0xd986 + at + 0x30, word(get(at)))
        h.setreg('BP', 0xd986)
        h.setreg('CX', step)
        h.setreg('DS', 0x1000)
        h.cpu.ctl_remove_cache(h.BASE, h.BASE + 65536)
        h.call(0xd510)
        assert h.getreg('IP') == h.RETURN
        h.call(0x6f0f)
        assert h.getreg('IP') == h.RETURN
        h.setreg('DS', 0x1000)
        h.setreg('BP', 0xd986)
        h.call(0xc582)
        assert h.getreg('IP') == h.RETURN
        state = bytes(h.cpu.mem_read(h.STACK + 0xd986, 112))
        rows.append([
            *[get(at) for at in (8,10,12)], *state[4:7],
            *[get(at) for at in (0x2a,0x2c,0x2e,0x3e,0x42,0x40,0x24,0x26,0x28,0x62,0x60)], state[0x6e],
            *[value(at) for at in (0xd5cd,0xd632,0xd72a,0xd805,0xd27c,0x7f20)], state[7], int(get(0x66) == 0x6ef7),
            value(0x7fa6), value(0x8540), h.read(0x4550)[0], h.read(0x4551)[0]])
        if get(0x66) == 0x6ef7:
            break
    return rows


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    root = parser.parse_args().workspace.resolve()
    assert hashlib.sha256((root/'analysis/unpacked/image.bin').read_bytes()).hexdigest() == IMAGE_SHA256
    sys.path.insert(0, str(root/'tools'))
    lines = ['#pragma once', '',
             '// Generated by generate_tunnel_launch_reference.py; native D510, 6F0F and C582 after original startup.',
             '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '']
    for step in (8, 10):
        rows = capture(root, step)
        lines += [f'inline constexpr std::array<std::array<uint16_t,30>,{len(rows)}> tunnel_launch_{step}_samples{{{{']
        lines += ['  {' + ','.join(map(str, row)) + '},' for row in rows]
        lines += ['}};', '']
        print(f'Captured {len(rows)} native tunnel launch updates with timestep {step}.')
    lines += ['} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/tunnel_launch_samples.h').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
