"""Capture complete native Skimma secondary status, reload and firing dispatch."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    raw = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    rng = random.Random(0xc991)
    rows = []
    for i in range(1536):
        h = Harness(raw)
        count = rng.choice((2,3))
        selected = rng.randrange(count)
        flags = [rng.choice((0,1,2,3,5,129)) for _ in range(3)]
        working = [rng.choice((0,1,8,14)) for _ in range(3)]
        reserve = [rng.choice((0,1,3)) for _ in range(3)]
        clock = rng.randrange(65536)
        deadline = (clock+rng.choice((-1,0,1,1024)))&65535
        spread = rng.randrange(509)
        target = rng.choice((0xffff,0xd9f6,0x1717,0x7fff,0x8000))
        free = rng.randrange(2)
        player_flags = rng.choice((0,0,16,32))
        pressed = rng.randrange(2)
        for p,v in ((0xcf5b,selected),(0xbf8,clock),(0xbf0,clock),(0xc51c,deadline),(0x5e00,spread),(0x5f0f,target),(0x6fbc,0xd200 if free else 0),(0xc9f7,0x8021 if pressed else 0),(0x7a2b,8)):
            h.write(p,struct.pack('<H',v))
        h.write(0xb91f,bytes([24+count]))
        h.write(0x4543,bytes(flags))
        h.write(0x5e10,bytes(working+reserve))
        h.cpu.mem_write(h.STACK+0xd98d,bytes([player_flags]))
        fired = []
        def launch(cpu,address,size,data):
            if address == h.BASE+0xcb01:
                fired.append((h.getreg('BX'),h.getreg('DX'),h.getreg('AX')))
                sp = h.getreg('SP')
                h.setreg('IP',int.from_bytes(cpu.mem_read(h.STACK+sp,2),'little'))
                h.setreg('SP',sp+2)
        h.cpu.hook_add(UC_HOOK_CODE,launch)
        h.call(0xc90a)
        rows.append([count,selected,*flags,*working,*reserve,clock,deadline,spread,target,free,player_flags,pressed,
                     *h.read(0x4543,3),*h.read(0x5e10,6),int.from_bytes(h.read(0xc51c,2),'little'),int.from_bytes(h.read(0x5e00,2),'little'),h.read(0x454e)[0],int(bool(fired))])
        if fired: assert fired == [(0x1a16+24*selected,2560,target)]
    lines = ['#pragma once','','// Generated by tools/generate_skimma_firing_reference.py; native C90A/C991','#include <array>','','namespace darker::test_reference {','',
             f'inline constexpr std::array<std::array<unsigned int,{len(rows[0])}>,{len(rows)}> skimma_firing_samples{{{{']
    lines += ['  {'+','.join(map(str,row))+'},' for row in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/skimma_firing_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} secondary firing cases, {sum(row[-1] for row in rows)} launches.')


if __name__ == '__main__':
    main()
