#!/usr/bin/env python3
"""Execute original underground visibility propagation with controlled model-cull results."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256

    class Probe(Harness):
        def hook(self, cpu, address, size, data):
            if address == self.BASE + 0x2a1a:
                index = self.getreg('BX') // 2
                accepted = (index*13 + self.seed*19 + self.frame*3) % 11 >= self.seed % 7
                self.add(index)
                self.add(int(accepted))
                self.setreg('EFLAGS', (self.getreg('EFLAGS') & ~1) | int(accepted))
                sp = self.getreg('SP')
                self.setreg('IP', int.from_bytes(cpu.mem_read(self.STACK + sp, 2), 'little'))
                self.setreg('SP', sp + 2)
                return
            super().hook(cpu, address, size, data)

        def add(self, word):
            self.fingerprint = ((self.fingerprint ^ word) * 0x100000001b3) & ((1 << 64) - 1)

    samples = []
    for seed in range(128):
        h = Probe(raw)
        h.seed = seed
        h.fingerprint = 0xcbf29ce484222325
        cells = bytearray(65536)
        for i in range(16384):
            cells[i*2] = int(seed % 4 == 0 or ((i*37) ^ (i >> 4) ^ (seed*17)) % 7 != 0)
            cells[i*2+1] = 0xa0 | ((i + seed) % 3 == 0)
        h.cpu.mem_write(0x30000, bytes(cells))
        h.write(0xfdf0, struct.pack('<H', 0x3000))
        for frame in range(3):
            h.frame = frame
            x, y = 10 + (seed*17 + frame*3) % 106, 10 + (seed*23 + frame*2) % 106
            h.setreg('BX', y*256+x)
            h.setreg('CX', 8) # 26EE supplies the underground radius with CH clear.
            h.setreg('DS', 0x1000)
            h.cpu.ctl_remove_cache(h.BASE, h.BASE+65536)
            h.call(0x2778)
            after = bytes(h.cpu.mem_read(0x30000,32768))
            for state in after[1::2]:
                assert state & 0xfe == 0xa0
                h.add(state & 1)
        samples.append(h.fingerprint)
    lines = ['#pragma once', '', '// Generated by generate_tunnel_visibility_reference.py; original 2778–29AA',
             '// Only model culling at 2A1A is substituted; visit order and state propagation execute unchanged.',
             '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             f'inline constexpr std::array<uint64_t,{len(samples)}> tunnel_visibility_samples{{']
    lines += [f'  0x{value:016x}ULL,' for value in samples]
    lines += ['};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/tunnel_visibility_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(samples)*3} native underground visibility frames.')


if __name__ == '__main__':
    main()
