#!/usr/bin/env python3
"""Capture native 8BE6 bomb admission and D089 building-target lookup."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    root = parser.parse_args().workspace.resolve()
    sys.path.insert(0, str(root/'tools'))
    from trace_hidden_commands import Harness
    from verify_player_collisions import setup
    from unicorn import UC_HOOK_CODE
    raw = (root/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    h = Harness(raw)
    launches = []
    word = lambda value: struct.pack('<H', value & 65535)

    def hook(cpu, address, size, data):
        if address == h.BASE + 0xcaf0:
            launches.append([h.getreg(r) for r in ('AX','BX','CX','DX','DI')])
            h.setreg('BP', 0xdb00)
            sp = h.getreg('SP')
            h.setreg('IP', int.from_bytes(cpu.mem_read(h.STACK + sp, 2), 'little'))
            h.setreg('SP', sp + 2)
    h.cpu.hook_add(UC_HOOK_CODE, hook)
    rng = random.Random(0x8be6)
    drops = []
    for i in range(512):
        flags = rng.choice((0,0,2,16,32,255))
        enabled = rng.choice((0,1,18,255))
        target = rng.choice((0x1234,0x7f7f,0xd986,0xda00))
        free = rng.randrange(2)
        last = rng.randrange(65536)
        clock = (last + rng.choice((0,1535,1536,1537,65535))) & 65535
        obj = bytearray(112)
        obj[7] = flags
        struct.pack_into('<H', obj, 0x48, target)
        struct.pack_into('<H', obj, 0x6a, last)
        h.cpu.mem_write(h.STACK + 0xda00, bytes(obj))
        h.cpu.mem_write(h.STACK + 0xdb00, bytes(112))
        h.write(0x8b13, bytes([enabled]))
        h.write(0x6fc5, bytes([free]))
        h.write(0xbf0, word(clock))
        h.setreg('BP', 0xda00)
        h.cpu.ctl_remove_cache(h.BASE, h.BASE + 65536)
        launches.clear()
        h.call(0x8be6)
        assert h.getreg('IP') == h.RETURN
        new_last = int.from_bytes(h.cpu.mem_read(h.STACK + 0xda6a, 2), 'little')
        pitch = int.from_bytes(h.cpu.mem_read(h.STACK + 0xdb2c, 2), 'little')
        if launches:
            assert launches == [[target,0x1a76,clock,28*256,0x6fc0]]
        drops.append([flags,enabled,target,free,last,clock,int(bool(launches)),new_last,pitch])
    targets = []
    for bank_id in (30,31,32):
        h, bank, _ = setup(bank_id)
        mask = 0x20 if bank_id == 30 else 0x60
        h.write(0x2e10, bytes([mask*2]))
        for kind in range(1, len(bank['types']) + 1):
            for state in (0,32,64,128):
                column, row = rng.randrange(128), rng.randrange(128)
                cell = column | row*256
                h.cpu.mem_write(0x60000 + row*256 + column*2, bytes([kind,state]))
                h.setreg('DS',0x1000)
                h.setreg('BX',cell)
                h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
                h.call(0xd089)
                assert h.getreg('IP') == h.RETURN
                targets.append([bank_id,kind,state,cell,h.getreg('AX'),h.getreg('BX'),h.getreg('DI'),h.getreg('DX')])
    lines = ['#pragma once', '', '// Generated by generate_aircraft_bomb_reference.py; native 8BE6 (CAF0 allocation intercepted) and D089.',
             '#include <array>', '', 'namespace darker::test_reference {', '']
    for name, rows in (('aircraft_bomb_samples',drops),('building_guidance_samples',targets)):
        lines += [f'inline constexpr std::array<std::array<unsigned int,{len(rows[0])}>,{len(rows)}> {name}{{{{']
        lines += ['  {' + ','.join(map(str,row)) + '},' for row in rows]
        lines += ['}};', '']
    lines += ['} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/aircraft_bomb_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(drops)} bomb admissions and {len(targets)} building targets.')


if __name__ == '__main__':
    main()
