#!/usr/bin/env python3
"""Execute native 5941–59A2, retaining RNG changes and complete radar snow pixels."""
import argparse
import hashlib
from pathlib import Path
import random
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    workspace = parser.parse_args().workspace.resolve()
    sys.path.insert(0, str(workspace / 'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    image = (workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(image).hexdigest() == IMAGE_SHA256
    native = Harness(image)
    # Startup extends the sine table by a quarter cycle for unmasked cosine lookups.
    native.write(0x9c4a, image[0x944a:0x964a])
    pixels = []
    def hook(cpu, address, size, data):
        if address == native.BASE + 0x53cf:
            pixels.extend((native.getreg('DX'), native.getreg('DI'), native.getreg('AX') >> 8))
            sp = native.getreg('SP')
            native.setreg('IP', int.from_bytes(cpu.mem_read(native.STACK + sp, 2), 'little'))
            native.setreg('SP', sp + 2)
    native.cpu.hook_add(UC_HOOK_CODE, hook)
    rng = random.Random(0x5941)
    rows = []
    for case in range(512):
        x, y, heading, seed = [rng.randrange(65536) for _ in range(4)]
        centre = [(v >> 8) - (((v >> 8) + 77) & 255) % 36 + 18 for v in (x, y)]
        cx, cy = [v & 255 for v in centre]
        mask = (0, 0x777, rng.randrange(0x1000) & 0x777)[case % 3]
        offset = ((54-cx) & 255) | (((54-cy) & 255) << 8)
        native.write(0x59a4, offset.to_bytes(2, 'little'))
        native.write(0x59c5, mask.to_bytes(2, 'little'))
        native.write(0x2701, bytes([x >> 8]))
        native.write(0x271c, bytes([y >> 8]))
        native.write(0x92d3, seed.to_bytes(2, 'little'))
        native.setreg('SI', (heading >> 6)*2)
        native.setreg('DS', 0x1000)
        native.cpu.ctl_remove_cache(native.BASE, native.BASE+65536)
        pixels.clear()
        native.call(0x5941)
        assert int.from_bytes(native.read(0x59a4, 2), 'little') == offset
        end_seed = int.from_bytes(native.read(0x92d3, 2), 'little')
        rows.append([x,y,heading,seed,cx,cy,mask,end_seed,len(pixels)//3] + pixels + [0]*(51-len(pixels)))
    output = Path(__file__).resolve().parents[1] / 'tests/reference/radar_noise_samples.h'
    output.write_text('''#pragma once

// Generated by tools/generate_radar_noise_reference.py; native 5941/59A3/5C04/92D2
#include <array>

namespace darker::test_reference {
inline constexpr std::array<std::array<unsigned int,60>,512> radar_noise_samples{{
''' + '\n'.join('  {' + ','.join(map(str,row)) + '},' for row in rows) + '\n}};\n} // namespace darker::test_reference\n')
    print('Captured 512 native radar snow frames and random-state transitions.')


if __name__ == '__main__':
    main()
