#!/usr/bin/env python3
"""Run native 6D08 city/aircraft acquisition with original Delphi geometry."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from verify_player_collisions import setup
    image=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(image).hexdigest()==IMAGE_SHA256
    rng=random.Random(0x6d08)
    rows=[]
    word=lambda v:struct.pack('<H',v&65535)
    for i in range(512):
        h,bank,tail=setup(30)
        h.cpu.mem_write(0x6a004,b'\xff')
        kind=rng.choice((0,1,17,77,86))
        state=rng.choice((0,32,64))
        h.cpu.mem_write(0x60000+50*256+50*2,bytes([kind,state]));h.write(0x2e10,b'\x40')
        player=(50*256+128,54*256+128,rng.choice((400,1000,3000,6000)))
        angles=(rng.choice((0,0,0,800,64736,32768)),rng.choice((0,0,500,65036)))
        aircraft=[(player[0]+rng.randrange(-200,201),player[1]-rng.choice((300,600,1500)),player[2]+rng.randrange(-200,201)) for _ in range(2)]
        if i >= 256:
            kind=0;angles=(0,0)
            h.cpu.mem_write(0x60000+50*256+50*2,b'\0\0')
            aircraft=[(player[0]+rng.randrange(-8,9),player[1]-distance,player[2]) for distance in ((300,600) if i%2 else (600,300))]
        h.write(0x6fd8,word(0xd9f6))
        for j,position in enumerate(aircraft):
            address=0xd9f6+j*112
            h.cpu.mem_write(h.STACK+address,word(address+112 if j==0 else 0))
            h.cpu.mem_write(h.STACK+address+8,struct.pack('<3H',*position))
            h.cpu.mem_write(h.STACK+address+0x22,word(bank['special_offsets'][19]+0x400))
        h.cpu.mem_write(h.STACK+0xd98e,struct.pack('<3H',*player))
        h.setreg('DI',angles[0]);h.setreg('BX',angles[1]);h.call(0x1e77)
        h.setreg('BP',0xd986);h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);h.call(0x6d08)
        assert h.getreg('IP')==h.RETURN
        token=h.getreg('BX') if h.getreg('EFLAGS')&1 else 65535
        rows.append((kind,state,*player,*angles,*aircraft[0],*aircraft[1],token))
    lines=['#pragma once','','// Generated by tools/generate_target_acquisition_reference.py; original 6D08',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           f'inline constexpr std::array<std::array<int, 14>, {len(rows)}> target_acquisition_samples{{{{']
    lines+=['  {'+', '.join(map(str,row))+'},' for row in rows]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/target_acquisition_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} native acquisition cases: {sum(r[-1] != 65535 for r in rows)} hits.')


if __name__=='__main__':main()
