#!/usr/bin/env python3
"""Capture moving-object placement with the native surface/underground opcode patch."""
from pathlib import Path
import struct
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT.parent / 'tools'))
from inspect_city import geometry_bank
from trace_hidden_commands import Harness

image = (ROOT.parent / 'analysis/unpacked/image.bin').read_bytes()
data = (ROOT.parent / 'analysis/resources/00_032.bin').read_bytes()
bank = geometry_bank(data, 32)
pool = data[bank['pool_start']:bank['tail_start']]
rows = []
for model, offset in enumerate(bank['special_offsets']):
    for underground in (0, 1):
        h = Harness(image)
        word = lambda at, value: h.write(at, struct.pack('<H', value & 65535))
        h.write(0x9c4a, image[0x944a:0x964a])
        for reg in ('DI', 'BX', 'CX'):
            h.setreg(reg, 0)
        h.call(0x1d63)
        for at, value in ((0x2e28, 0), (0x2e2c, 0), (0x2e36, 1800), (0x3142, 0x7000), (0x2b1f, 0), (0x2af5, 0)):
            word(at, value)
        for at in (0x2f3b, 0x2f46):
            h.write(at, b'\x50')
        for at in (0x2f3d, 0x2f48):
            h.write(at, b'\x20')
        h.write(0x2edc, bytes([0x29 if underground else 0x01]))
        h.cpu.mem_write(0x70400, pool)
        obj = bytearray(112)
        struct.pack_into('<3H', obj, 8, 0x4000, 0x3c00, 1600)
        struct.pack_into('<H', obj, 0x22, offset+0x400)
        h.cpu.mem_write(h.STACK+0xd986, bytes(obj))
        h.setreg('BP', 0xd986)
        h.cpu.ctl_remove_cache(h.BASE, h.BASE+65536)
        h.call(0x2ebc)
        assert h.getreg('IP') == h.RETURN
        result = bytes(h.cpu.mem_read(h.STACK+0xd986+14, 24))
        key = struct.unpack_from('<H', result, 14)[0]
        rows.append(f'  {{{model},{underground},{key}}},')
output = '''#pragma once

#include <array>

// Generated by tools/generate_object_sorting_reference.py from 2EBC and the BC94 patch.
namespace darker::test_reference {
struct object_sorting_sample { unsigned int model; bool underground; unsigned int distance; };
inline constexpr auto object_sorting_samples = std::to_array<object_sorting_sample>({
'''+ '\n'.join(rows)+ '\n});\n} // namespace darker::test_reference\n'
(ROOT / 'tests/reference/object_sorting_samples.h').write_text(output)
print(f'Captured {len(rows)} native moving-object sorting keys.')
