"""Capture Skimma primary-gun spread and ray endpoints before native city clipping."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    rng = random.Random(0xcd84)
    rows = []
    for _ in range(2048):
        h = Harness(raw)
        h.write(0x9c4a, raw[0x944a:0x964a])
        position = [rng.randrange(65536) for _ in range(3)]
        heading, pitch, offset, seed = [rng.randrange(65536) for _ in range(4)]
        h.cpu.mem_write(h.STACK + 0xd98e, struct.pack('<3H', *position))
        h.cpu.mem_write(h.STACK + 0xd9b0, struct.pack('<H', heading))
        h.write(0x92d3, struct.pack('<H', seed))
        h.setreg('BP', 0xd986)
        h.setreg('BX', (pitch + offset) & 65535)
        h.call(0xcd84)
        endpoints = []
        def stop(cpu, address, size, data):
            if address == h.BASE + 0x6527:
                endpoints.append([h.getreg('CX'), h.getreg('DX'), (h.getreg('BP') * 2) & 65535])
                h.setreg('IP', h.RETURN)
        h.cpu.hook_add(UC_HOOK_CODE, stop)
        h.call(0x6d08)
        assert len(endpoints) == 1
        rows.append([*position, heading, pitch, offset, seed, *endpoints[0], int.from_bytes(h.read(0x92d3, 2), 'little')])
    lines = ['#pragma once', '', '// Generated by tools/generate_skimma_gun_reference.py; native CD84/6D08',
             '#include <array>', '', 'namespace darker::test_reference {', '',
             f'inline constexpr std::array<std::array<unsigned int,11>,{len(rows)}> skimma_gun_samples{{{{']
    lines += ['  {' + ','.join(map(str,row)) + '},' for row in rows]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/skimma_gun_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} Skimma gun rays.')


if __name__ == '__main__':
    main()
