#!/usr/bin/env python3
"""Capture original 8351 attitude control and 8D75 actor displacement."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    raw=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    h=Harness(raw);h.write(0x9c4a,raw[0x944a:0x964a]);rng=random.Random(0x8351)
    steering=[];motion=[]
    for i in range(1024):
        angles=[rng.randrange(65536) for _ in range(3)]
        rates=[rng.randrange(65536) for _ in range(2)]
        parameters=[rng.randrange(2048),rng.randrange(65536),rng.randrange(65536),rng.randrange(65536)]
        pitch,drive=rng.randrange(65536),rng.randrange(65536)
        step=rng.randrange(81) if i%4 else rng.randrange(65536)
        obj=bytearray(112)
        struct.pack_into('<5H',obj,0x26,*rates,*angles)
        struct.pack_into('<4H',obj,0x30,*parameters)
        h.cpu.mem_write(h.STACK+0xda00,bytes(obj));h.setreg('BP',0xda00)
        h.setreg('DX',pitch);h.setreg('DI',drive);h.setreg('CX',step)
        h.call(0x8351)
        after=bytes(h.cpu.mem_read(h.STACK+0xda00,112))
        steering.append(([*angles,*rates,*parameters,pitch,drive,step],
                         [*struct.unpack_from('<3H',after,0x2a),*struct.unpack_from('<2H',after,0x26),h.getreg('CX')]))
        position=[rng.randrange(65536) for _ in range(3)]
        fractions=[rng.randrange(256) for _ in range(3)]
        speed=rng.randrange(65536)
        target,accel,decel=[rng.randrange(256) for _ in range(3)]
        obj=bytearray(112);obj[4:7]=bytes(fractions)
        struct.pack_into('<3H',obj,8,*position)
        struct.pack_into('<3H',obj,0x2a,*angles)
        struct.pack_into('<H',obj,0x3e,speed)
        struct.pack_into('<H',obj,0x44,0xf000)
        h.cpu.mem_write(h.STACK+0xda00,bytes(obj));h.write(0xf00a,bytes([accel,decel]))
        h.setreg('BP',0xda00);h.setreg('CX',step);h.setreg('DX',target)
        h.call(0x8d75)
        after=bytes(h.cpu.mem_read(h.STACK+0xda00,112))
        motion.append(([*position,*fractions,*angles,speed,target,accel,decel,step],
                       [*struct.unpack_from('<3H',after,8),*after[4:7],int.from_bytes(after[0x3e:0x40],'little')]))
    lines=['#pragma once','','// Generated by tools/generate_actor_motion_reference.py; native 8351 and 8D75',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','']
    for name,rows in [('actor_steering',steering),('actor_motion',motion)]:
        lines += [f'struct {name}_sample '+'{'+f' std::array<int, {len(rows[0][0])}> input; std::array<int, {len(rows[0][1])}> output; '+'};',
                  f'inline constexpr std::array<{name}_sample, {len(rows)}> {name}_samples{{{{']
        lines += ['  {{'+', '.join(map(str,a))+'}, {'+', '.join(map(str,b))+'}},' for a,b in rows]
        lines += ['}};','']
    lines += ['} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/actor_motion_samples.h').write_text('\n'.join(lines))
    print('Captured 1,024 native actor steering and 1,024 motion cases.')


if __name__=='__main__':main()
