#!/usr/bin/env python3
"""Generate original effect recipes and sprite selectors; artwork remains in the packs."""
import argparse
import hashlib
from pathlib import Path
from generate_resource_directory import IMAGE_SHA256

p = argparse.ArgumentParser(description=__doc__)
p.add_argument('image', type=Path)
a = p.parse_args()
b = a.image.read_bytes()
assert hashlib.sha256(b).hexdigest() == IMAGE_SHA256
root = Path(__file__).resolve().parents[1]
word = lambda i: int.from_bytes(b[i:i+2], 'little')
signed = lambda n: n - 256 if n > 127 else n
entries = [0x7014,0x7050,0x70c3,0x70f0,0x716c,0x7199,0x71e8,0x721c,0x7247,0x7296,0x72df,0x7319,0x7386,0x73c6,0x747e,0x7518,0x75a3,0x75d4,0x7749,0x77c5,0x77ff]
lines = ['#pragma once', '', '// Generated by tools/generate_effect_tables.py', '// Image SHA-256: '+IMAGE_SHA256, '#include <array>', '#include "game/effects.h"', '', 'namespace darker::game {']
for entry in entries:
    records = []
    i = entry
    while True:
        records.append('  {.delay{%d}, .offset{%d, %d, %d}, .radius{%d}, .angle{%d}, .sampling{%d}, .radius_rate{%d}, .height_rate{%d}, .angle_rate{%d}, .flags{%d}},' % (word(i),signed(b[i+2]),signed(b[i+3]),int.from_bytes(b[i+4:i+6],'little',signed=True),word(i+6),b[i+8]*256,word(i+9),signed(b[i+11]),signed(b[i+12]),signed(b[i+13]),b[i+14]&~64))
        i += 15
        if b[i-1] & 64: break
    lines += [f'inline std::array<emitter_definition, {len(records)}> constexpr recipe_{entry:04x}{{{{',*records,'}};']
    sounds = []
    while b[i] != 255:
        sounds.append('  {.duration{%d}, .pitch{%d}, .level{%d}, .patch{%d}, .flags{%d}},' % (b[i]*16,word(i+2),b[i+5]*256+255,b[i+1],b[i+4]))
        i += 6
    lines += [f'inline std::array<effect_sound_definition, {len(sounds)}> constexpr sounds_{entry:04x}{{{{',*sounds,'}};']
lines += ['inline std::array<effect_recipe, 21> constexpr original_effect_recipes{{']
lines += [f'  {{.address{{0x{x:04x}}}, .emitters{{recipe_{x:04x}}}, .sounds{{sounds_{x:04x}}}}},' for x in entries]
lines += ['}};', 'inline std::array<uint16_t, 7> constexpr building_effect_recipes{'+', '.join(hex(word(0x783f+i*2)) for i in range(7))+'};', '} // namespace darker::game','']
(root/'src/game/effect_tables.h').write_text('\n'.join(lines))
lines = ['#pragma once','','// Generated by tools/generate_effect_tables.py', '// Image SHA-256: '+IMAGE_SHA256,'#include <array>','','namespace darker::graphics {']
# Keep the compact original selector data, including source offsets and per-row masks.
for name,start,end in [('particle_selectors',0x6b34,0x6bf3),('particle_point_colours',0x6a43,0x6a59)]:
    lines += [f'inline std::array<uint8_t, {end-start}> constexpr {name}{{']
    for i in range(start,end,16): lines.append('  '+', '.join(str(x) for x in b[i:min(i+16,end)])+',')
    lines += ['};']
lines += ['} // namespace darker::graphics','']
(root/'src/graphics/particle_tables.h').write_text('\n'.join(lines))
