#!/usr/bin/env python3
"""Capture native tunnel route preparation, interpolation and direction selection."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    source = bytearray()
    for tile in range(200):
        source.append(tile & 3)
        for edge in range(3):
            first = (tile*17 + edge*29) & 127
            source.extend((first,(first + edge*13 + 17) & 127,(tile*19 + edge*71) & 255))
    h = Harness(raw)
    h.write(0xfdf2,struct.pack('<H',0x3000))
    h.cpu.mem_write(0x70000,bytes(source))
    h.setreg('DS',0x7000)
    h.setreg('SI',0)
    h.setreg('SP',0xfefe)
    h.cpu.mem_write(h.STACK+0xfefe,struct.pack('<H',h.RETURN))
    h.setreg('EFLAGS',2)
    h.cpu.emu_start(h.BASE+0xd0be,h.BASE+h.RETURN,count=1000000)
    assert h.getreg('IP') == h.RETURN
    prepared = bytes(h.cpu.mem_read(0x30000+0xe580,3200))
    samples = []
    for case in range(2048):
        tile = case % 200 + 1
        route = case % 3 | (0x80 if case % 5 < 2 else 0)
        offset = 0xe580 + (tile-1)*16 + 11 - (route & 3)*5
        length = prepared[offset-0xe580+3]
        distance = (case*71) % (length*2+1)
        cell = (10 + case*13 % 106)*256 + 10 + case*7 % 106
        h.setreg('AX',route << 8)
        h.setreg('BX',cell)
        h.setreg('SI',offset)
        h.setreg('DI',distance)
        h.setreg('ES',0x3000)
        h.call(0xd31f)
        point = [h.getreg('SI'),h.getreg('BX'),h.getreg('AX')]
        heading = (case*3571) & 65535
        h.cpu.mem_write(h.STACK+0xd986+0x2a,struct.pack('<H',heading))
        h.setreg('BP',0xd986)
        h.setreg('AX',route << 8)
        h.setreg('SI',offset)
        h.call(0xd894)
        direction = h.cpu.mem_read(h.STACK+0xd986+0x6e,1)[0]
        samples.append([tile,route,cell,distance,heading,*point,direction])
    lines = ['#pragma once','','// Generated by generate_tunnel_network_reference.py; native D0BE, D31F and D894',
             '#include <array>','#include <cstdint>','','namespace darker::test_reference {','',
             'inline constexpr std::array<uint8_t,3200> prepared_tunnel_routes{']
    lines += ['  '+','.join(map(str,prepared[i:i+16]))+',' for i in range(0,3200,16)]
    lines += ['};','','inline constexpr std::array<std::array<uint16_t,9>,2048> tunnel_point_samples{{']
    lines += ['  {'+','.join(map(str,s))+'},' for s in samples]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1] / 'tests/reference/tunnel_network_samples.h').write_text('\n'.join(lines))
    print('Captured 200 prepared records and 2048 tunnel point/direction samples.')


if __name__ == '__main__':
    main()
