#!/usr/bin/env python3
"""Compare complete native beacon-fade map states across clock and direction boundaries."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def fingerprint(data):
    result = 0xcbf29ce484222325
    for byte in data:
        result = ((result ^ byte) * 0x100000001b3) & ((1 << 64) - 1)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    rng = random.Random(0xc510); rows = []
    for case in range(36):
        h = Harness(raw)
        opcode = 0x11 + case % 3
        column, row = rng.randrange(15), rng.randrange(15)
        origin = column*16 + row
        count = 1 if opcode == 0x11 else rng.randrange(1, 16 - (column if opcode == 0x12 else row))
        clock = (0, 65000, 65500)[case % 3]
        dimming = case % 2
        seed = rng.randrange(256)
        grid = bytes(v for i in range(16384) for v in (1, (i*37+seed)&255))
        h.cpu.mem_write(0x60000,grid);h.write(0xfdf0,struct.pack('<H',0x6000))
        h.write(0xc526,bytes([255 if dimming or opcode == 0x11 else 0]))
        h.write(0xc52c,struct.pack('<H',0x900 if opcode == 0x13 else 18))
        h.write(0xbf0,struct.pack('<H',clock));h.setreg('AX',origin | count*256);h.call(0xc54c)
        values = []
        for elapsed in (0,16,128,255,256,257,512):
            h.write(0xbf0,struct.pack('<H',(clock+elapsed)&65535))
            h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
            h.call(0xc510)
            values.append(fingerprint(h.cpu.mem_read(0x60000,32768)))
        rows.append((opcode,origin,count,clock,dimming,seed,values))
    lines = ['#pragma once', '', '// Generated by tools/generate_beacon_changes_reference.py; original C54C/C510',
             '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct beacon_change_sample { unsigned int opcode, origin, count, clock, dimming, seed; std::array<uint64_t,7> frames; };',
             f'inline constexpr std::array<beacon_change_sample,{len(rows)}> beacon_change_samples{{{{']
    lines += ['  {'+','.join(map(str,row[:6]))+', {'+','.join(f'0x{x:016x}ULL' for x in row[6])+'}},' for row in rows]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/beacon_change_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)*7} full-map native fade frames.')


if __name__ == '__main__':
    main()
