#!/usr/bin/env python3
"""Execute the aircraft contact pass, including ordered sweeps and both native damage responses."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args = parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from verify_player_collisions import setup
    from unicorn import UC_HOOK_CODE
    assert hashlib.sha256((args.workspace/'analysis/unpacked/image.bin').read_bytes()).hexdigest() == IMAGE_SHA256
    h,bank,_ = setup(30)
    h.cpu.mem_write(0x6a004,b'\xff')
    effects=[]
    def hook(cpu,address,size,data):
        if address == h.BASE+0x6815:
            effects.append(h.getreg('SI'))
            sp=h.getreg('SP');h.setreg('IP',int.from_bytes(cpu.mem_read(h.STACK+sp,2),'little'));h.setreg('SP',sp+2)
    h.cpu.hook_add(UC_HOOK_CODE,hook)
    rng=random.Random(0x6e6d)
    cases=[]
    def put(bp,offset,value):h.cpu.mem_write(h.STACK+bp+offset,struct.pack('<H',value&65535))
    def get(bp,offset):return int.from_bytes(h.cpu.mem_read(h.STACK+bp+offset,2),'little')
    for case in range(512):
        seed=rng.randrange(65536);clock=rng.randrange(65536)
        start=[16000+rng.randrange(-160,161),16000+rng.randrange(-160,161),2000+rng.randrange(-128,129)]
        end=[16000+rng.randrange(-160,161),16000+rng.randrange(-160,161),2000+rng.randrange(-128,129)]
        initial=[]
        for n in range(3):
            bp=0xd000+n*112
            slot=rng.choice((19,20,21,22,23))
            flags=rng.choice((0,8,16,32,40)) if n==0 else 16
            position=end if n==0 else [16000+rng.randrange(-100,101),16000+rng.randrange(-100,101),2000+rng.randrange(-128,129)]
            pitch,turn,level,damage=[rng.randrange(65536) for _ in range(4)]
            h.cpu.mem_write(h.STACK+bp,bytes(112));put(bp,0,bp+112 if n<2 else 0)
            h.cpu.mem_write(h.STACK+bp+7,bytes([flags]))
            for axis,value in enumerate(position):put(bp,8+axis*2,value);put(bp,0x38+axis*2,start[axis] if n==0 else value)
            for offset,value in ((0x22,bank['special_offsets'][slot]+0x400),(0x44,0x1926+slot*24),(0x66,0x8823),(0x68,0),(0x26,pitch),(0x28,turn),(0x56,level),(0x64,damage)):put(bp,offset,value)
            initial += [slot,flags,*position,pitch,turn,level,damage]
        h.write(0x6fd8,struct.pack('<H',0xd000));h.write(0x6202,bytes([2*(case%2)]));h.write(0xbf8,struct.pack('<H',clock));h.write(0x92d3,struct.pack('<H',seed))
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        effects.clear();h.setreg('DS',0x1000);h.setreg('DI',0x6fd8);h.setreg('SI',0x700c);h.setreg('AX',0x0c10);h.call(0x6df1)
        result=[]
        for n in range(3):
            bp=0xd000+n*112
            result += [get(bp,a) for a in (8,10,12,0x26,0x28,0x56,0x64,0x66,0x68)]
            result += [h.cpu.mem_read(h.STACK+bp+7,1)[0]]
        assert len(effects)<=2
        cases.append([seed,clock,*start,*initial,*result,int.from_bytes(h.read(0x92d3,2),'little'),len(effects),case%2])
    width=len(cases[0]);assert all(len(row)==width for row in cases)
    lines=['#pragma once','','// Generated by tools/generate_aircraft_contact_reference.py; native 6DF1/6E6D/CE26, effects intercepted',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           f'inline constexpr std::array<std::array<unsigned int,{width}>,{len(cases)}> aircraft_contact_samples{{{{']
    lines += ['  {'+','.join(map(str,row))+'},' for row in cases]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/aircraft_contact_samples.h').write_text('\n'.join(lines))
    print('Captured',len(cases),'ordered aircraft contact passes;',sum(row[-2]>0 for row in cases),'with impacts.')


if __name__=='__main__':main()
