#!/usr/bin/env python3
"""Capture complete CBE7 Dual Launch steering, spin and displacement."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args = parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    h = Harness(raw)
    h.write(0x9c4a,raw[0x944a:0x964a])
    rng = random.Random(0xcbe7)
    rows = []
    for i in range(2048):
        position = [rng.randrange(65536) for _ in range(3)]
        fractions = [rng.randrange(256) for _ in range(3)]
        angles = [rng.randrange(65536) for _ in range(3)]
        speed, roll = rng.randrange(65536), rng.randrange(65536)
        rates = [rng.randrange(65536) for _ in range(2)]
        target = [rng.randrange(65536) for _ in range(3)]
        remaining = rng.randrange(4096) if i%2 else rng.randrange(65536)
        step = rng.randrange(81) if i%4 else rng.randrange(65536)
        self_target = int(i%5 == 0)
        obj = bytearray(112)
        obj[4:7] = bytes(fractions)
        struct.pack_into('<3H',obj,8,*position)
        struct.pack_into('<3H',obj,0x2a,*angles)
        struct.pack_into('<2H',obj,0x26,*rates)
        struct.pack_into('<H',obj,0x30,512)
        struct.pack_into('<H',obj,0x3e,speed)
        struct.pack_into('<H',obj,0x44,0x19b6)
        struct.pack_into('<H',obj,0x56,roll)
        struct.pack_into('<H',obj,0x6c,0xda00 if self_target else 0xdb00)
        h.cpu.mem_write(h.STACK+0xda00,bytes(obj))
        h.cpu.mem_write(h.STACK+0xdb08,struct.pack('<3H',*target))
        h.write(0x19cc,struct.pack('<H',614))
        h.setreg('BP',0xda00); h.setreg('DX',remaining); h.setreg('CX',step)
        h.call(0xcbe7)
        assert h.getreg('IP') == h.RETURN
        after = bytes(h.cpu.mem_read(h.STACK+0xda00,112))
        result = [*struct.unpack_from('<3H',after,8),*after[4:7],*struct.unpack_from('<5H',after,0x26),
                  int.from_bytes(after[0x3e:0x40],'little'),int.from_bytes(h.read(0x19cc,2),'little')]
        rows.append([*position,*fractions,*angles,speed,roll,*rates,*target,remaining,step,self_target,*result])
    lines = ['#pragma once','','// Generated by tools/generate_dual_motion_reference.py; native CBE7',
             '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
             f'inline constexpr std::array<std::array<unsigned int,32>,{len(rows)}> dual_motion_samples{{{{']
    lines += ['  {'+','.join(map(str,row))+'},' for row in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/dual_motion_samples.h').write_text('\n'.join(lines))
    print('Captured',len(rows),'native Dual Launch movement updates.')


if __name__ == '__main__':
    main()
