#!/usr/bin/env python3
"""Capture supply-related script effects through the original scheduler."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from verify_mission_scheduler import Probe, IMAGE
    assert hashlib.sha256(IMAGE).hexdigest()==IMAGE_SHA256
    rng=random.Random(0xc7b3)
    rows=[]
    for i in range(512):
        message,progress,previous,mask_range=[rng.randrange(256) for _ in range(4)]
        hud,output,mask,shield=[rng.randrange(65536) for _ in range(4)]
        selected=rng.randrange(3)
        working,reserve=rng.randrange(256),rng.randrange(256)
        program=bytes([15,message,22,hud&255,hud>>8,23,output&255,output>>8,45,progress,48,mask_range,24,25,35])
        h=Probe(program,0)
        h.write(0x3e9a,bytes([previous]));h.write(0xc88c,struct.pack('<H',mask));h.write(0x8109,struct.pack('<H',shield))
        h.write(0xcf5b,struct.pack('<H',selected));h.write(0x5e10+selected,bytes([working]));h.write(0x5e13+selected,bytes([reserve]))
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        h.update(0)
        result=[h.read(0xb13c)[0],int.from_bytes(h.read(0x576f,2),'little'),int.from_bytes(h.read(0x7e4a,2),'little'),
          h.read(0x3e9a)[0],int.from_bytes(h.read(0xc88c,2),'little'),int.from_bytes(h.read(0x8109,2),'little'),
          h.read(0x5e10+selected)[0],h.read(0x5e13+selected)[0]]
        rows.append((list(program),[previous,mask,shield,selected,working,reserve],result))
    lines=['#pragma once','','// Generated by tools/generate_supply_script_reference.py; native scheduler and supply handlers',
      '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
      'struct supply_script_sample { std::array<int,15> program; std::array<int,6> input; std::array<int,8> output; };',
      f'inline constexpr std::array<supply_script_sample,{len(rows)}> supply_script_samples{{{{']
    lines += ['  {{'+', '.join(map(str,p))+'}, {'+', '.join(map(str,a))+'}, {'+', '.join(map(str,b))+'}},' for p,a,b in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/supply_script_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} supply script sequences.')


if __name__ == '__main__': main()
