#!/usr/bin/env python3
"""Capture sequential native horizontal/vertical flight integration and integer speed."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    native = Harness(raw)
    native.write(0x9c4a, raw[0x944a:0x964a])
    bp = 0xd986
    word = lambda value: struct.pack('<H', value & 65535)
    def put(offset, value):
        native.cpu.mem_write(native.STACK+bp+offset, word(value))
    def get(offset):
        return int.from_bytes(native.cpu.mem_read(native.STACK+bp+offset, 2), 'little')
    def state():
        return [get(a) for a in (8, 10, 12)] + list(native.cpu.mem_read(native.STACK+bp+4, 3)) + [get(a) for a in (0x42, 0x40, 0x3e)]
    rng = random.Random(0x8208)
    cases = []
    for run in range(32):
        for offset in (8, 10, 12, 0x40, 0x42):
            put(offset, 0 if run == 0 else rng.randrange(65536))
        put(0x3e, 0)
        native.cpu.mem_write(native.STACK+bp+4, bytes(rng.randrange(256) for _ in range(3)))
        for frame in range(16):
            before = state()
            target_h = 0 if run == 0 else rng.randrange(65536)
            target_v = target_h if frame == 0 else rng.randrange(65536)
            time_h = rng.choice((0, 1, 128, 1028, 32767, 32768, 65535))
            time_v = rng.choice((0, 1, 257, 2056, 32767, 32768, 65535))
            heading, pitch = [rng.randrange(65536) for _ in range(2)]
            native.setreg('BP', bp)
            for register, value in [('AX', target_h), ('CX', time_h), ('SI', (heading >> 6)*2), ('DI', (pitch >> 6)*2)]:
                native.setreg(register, value)
            native.call(0x8208)
            native.setreg('AX', target_v)
            native.setreg('CX', time_v)
            native.call(0x826e)
            native.call(0x8254)
            cases.append([frame, target_h, target_v, time_h, time_v, heading, pitch, before, state()])
    lines = ['#pragma once', '', '// Generated by tools/generate_flight_motion_reference.py; native 8208, 826E, 8254 and 92E6',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct flight_motion_sample {', '  int frame, target_h, target_v, time_h, time_v, heading, pitch;',
             '  std::array<int, 9> before, after;', '};', f'inline constexpr std::array<flight_motion_sample, {len(cases)}> flight_motion_samples{{{{']
    for row in cases:
        lines.append('  {' + ', '.join(map(str, row[:7])) + ', {' + ', '.join(map(str, row[7])) + '}, {' + ', '.join(map(str, row[8])) + '}},')
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/flight_motion_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} native flight movement frames in 32 uninterrupted state sequences.')


if __name__ == '__main__':
    main()
