#!/usr/bin/env python3
"""Capture the original Caero Nayas receiver indicator at 567D."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    root=parser.parse_args().workspace.resolve()
    sys.path.insert(0,str(root/'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    raw=(root/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    rng=random.Random(0x567d)
    rows=[]
    for i in range(512):
        h=Harness(raw)
        clock=rng.randrange(65536);message=rng.randrange(2);stopped=rng.randrange(2);complete=rng.randrange(2);flags=rng.randrange(256)
        word=lambda v:struct.pack('<H',v&65535)
        h.setreg('BP',0xd986)
        h.cpu.mem_write(h.STACK+0xd986+0x58,word(0xc50f if stopped else 0x1234))
        h.cpu.mem_write(h.STACK+0xd986+0x3e,word(500));h.cpu.mem_write(h.STACK+0xd986+7,bytes([flags]))
        h.write(0xbf8,word(clock));h.write(0x306,bytes([message]));h.write(0x4552,b'\x01')
        h.write(0xc84f,word(0xe800));h.write(0xe800,b'\xff');h.write(0xc16f,bytes([0 if complete else 1]));h.write(0x6202,b'\0')
        def hook(cpu,address,size,data):
            if address==h.BASE+0x56c7:h.setreg('IP',h.RETURN)
        h.cpu.hook_add(UC_HOOK_CODE,hook);h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);h.call(0x567d)
        assert h.getreg('IP')==h.RETURN
        rows.append([clock,message,stopped,complete,flags,h.read(0x4553,1)[0]])
    lines=['#pragma once','','// Generated by tools/generate_receiver_indicator_reference.py; native 567D–56C7',
      '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
      f'inline constexpr std::array<std::array<int,6>,{len(rows)}> receiver_indicator_samples{{{{']
    lines += ['  {'+', '.join(map(str,r))+'},' for r in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/receiver_indicator_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} original receiver indicators.')


if __name__ == '__main__': main()
