#!/usr/bin/env python3
"""Capture native distance-shade generation and model light selection."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256
from native_flat_model import fingerprint


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    cases = []
    tables = []
    for count in (28, 60):
        native = Harness(image)
        native.setreg('CX', count); native.setreg('SI', 28); native.setreg('BX', 1)
        native.call(0xb73c)
        first = int.from_bytes(native.cpu.mem_read(native.STACK+0x820, 2), 'little')
        tables.append((count, fingerprint(native.cpu.mem_read(native.STACK+first, count*28))))
        for depth in (0, 1, 255, 256, 257, 4095, 4096, 8192, 15000, 15359, 15360, 32767, 32768, 65535):
            for light in (0, 1, 15, 16, 127, 128, 254, 255):
                for near in (False, True):
                    native.cpu.mem_write(native.STACK+0x800a, struct.pack('<H', depth))
                    native.setreg('BP', 0x8000); native.setreg('BX', light<<8); native.setreg('DS', 0x1000)
                    native.setreg('EFLAGS', 2)
                    native.cpu.ctl_remove_cache(native.BASE, native.BASE+65536)
                    native.cpu.emu_start(native.BASE+(0x2c8e if near else 0x2cde), native.BASE+0x2d07, count=1000)
                    assert native.getreg('IP') == 0x2d07
                    table = int.from_bytes(native.read(0x3385, 2), 'little')
                    values = native.cpu.mem_read(native.STACK+table, 28)+native.read(0x339a, 1)
                    cases.append((count, depth, light, near, fingerprint(values)))
    lines = ['#pragma once', '', '// Generated by tools/generate_model_lighting_reference.py; original B73C and 2CE4',
             '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct model_lighting_sample { unsigned int count, depth, light; bool near; std::uint64_t fingerprint; };',
             f'inline constexpr std::array<model_lighting_sample, {len(cases)}> model_lighting_samples{{{{']
    lines += ['  {'+', '.join(map(str, row[:3]))+', '+str(row[3]).lower()+f', 0x{row[4]:016x}'+'},' for row in cases]
    lines += ['}};', '', 'struct shade_table_sample { unsigned int count; std::uint64_t fingerprint; };',
              'inline constexpr std::array<shade_table_sample, 2> shade_table_samples{{']
    lines += ['  {'+str(count)+f', 0x{value:016x}'+'},' for count, value in tables]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/model_lighting_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} native light selections.')


if __name__ == '__main__':
    main()
