#!/usr/bin/env python3
"""Execute the original full projectile constructor on controlled launch fixtures."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    native = Harness(raw)
    native.write(0x9c4a, raw[0x944a:0x964a])
    word = lambda value: struct.pack('<H', value & 65535)
    def ss(offset, data):
        native.cpu.mem_write(native.STACK+offset, data)
    cases = []
    for strength in (0, 1):
        for heading in (0, 8191, 8192, 16384, 24576, 32768, 49152, 65535):
            for pitch, roll in ((0, 0), (8192, 0), (0, 8192), (65535, 16384), (32768, 49152)):
                for edge in (0, 1):
                    position = (1000, 2000, 3000) if not edge else (0, 65535, 0)
                    fractions = (0, 127, 255) if not edge else (255, 1, 128)
                    side = 0x80 if edge else 0
                    ss(0x6000, bytes([0xa5])*112)
                    ss(0x6000, word(0))
                    ss(0x6200, bytes(112))
                    ss(0x6204, bytes(fractions))
                    ss(0x6208, struct.pack('<3H', *position))
                    ss(0x622a, struct.pack('<3H', heading, pitch, roll))
                    ss(0x623e, word(0x9876))
                    ss(0x6244, word(0x5000))
                    ss(0x6250, bytes([side]))
                    native.write(0x5000, bytes(24))
                    native.write(0x5008, bytes([strength]))
                    native.write(0x5100, raw[0x1a16:0x1a2e])
                    native.write(0x6fb8, struct.pack('<3H', 0, 0, 0x6000))
                    for register, value in [('BP', 0x6200), ('AX', 0xffff), ('DI', 0x6fb8), ('BX', 0x5100), ('CX', 65530), ('DX', 0x0a00)]:
                        native.setreg(register, value)
                    native.call(0xcb01)
                    result = bytes(native.cpu.mem_read(native.STACK+0x6000, 112))
                    out = [*struct.unpack('<3H', result[8:14]), *result[4:7], *struct.unpack('<3H', result[0x2a:0x30]), int.from_bytes(result[0x3e:0x40], 'little')]
                    assert result[7] == 0x20 and result[0x46] == 0xfe
                    assert result[0x26:0x2a] == bytes(4)
                    assert result[0x56:0x58] == word(roll)
                    assert result[0x68:0x6a] == word(65530+0x0a00)
                    assert result[0x6c:0x6e] == word(0xffff)
                    cases.append([strength, heading, pitch, roll, edge, *out])
    lines = ['#pragma once', '', '// Generated by tools/generate_placement_reference.py via native CB01',
             '// Source image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct placement_sample { int strength, heading, pitch, roll, edge; std::array<int, 10> result; };',
             f'inline constexpr std::array<placement_sample, {len(cases)}> placement_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row[:5])) + ', {' + ', '.join(map(str, row[5:])) + '}},' for row in cases]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/placement_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} complete native launches across both placement branches.')


if __name__ == '__main__':
    main()
