#!/usr/bin/env python3
"""Capture native stateful coordinate projection, including shared fractional storage."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    rng = random.Random(0xfc97)
    sets, zeroes, negatives = (0x88, 0x94, 0x7f), (0x61, 0x64, 0x5e), (0x76, 0x79, 0x73)
    cases = []
    for sequence in range(24):
        native = Harness(raw)
        axes = [rng.randrange(-32768, 32768) for _ in range(9)]
        base = [rng.randrange(-10, 11), rng.randrange(256), rng.randrange(-10, 11), rng.randrange(256), 2048, rng.randrange(256)]
        origin = [rng.randrange(-100, 321), rng.randrange(-100, 241)]
        word = lambda value: struct.pack('<H', value & 65535)
        for offset, value in zip((0xfd05, 0xfd12, 0xfd1f, 0xfd31, 0xfd3e, 0xfd4b, 0xfd5d, 0xfd6a, 0xfd77), axes):
            native.write(offset, word(value))
        for offset, value in ((0xfcb0, base[0]), (0xfcd5, base[2]), (0xfc9b, base[4]), (0xfccd, origin[0]), (0xfcf1, origin[1])):
            native.write(offset, word(value))
        for offset, value in ((0xfcbf, base[1]), (0xfce4, base[3]), (0xfca8, base[5])):
            native.write(offset, bytes([value]))
        operations = []
        code = bytearray((0x52, 0x56, 0x5a))
        for step in range(32):
            axis = rng.randrange(3)
            operation = 0 if step < 3 else rng.randrange(3)
            value = rng.randrange(-1024, 1025)
            operations.append((operation, axis, value))
            code.append((sets, zeroes, negatives)[operation][axis])
            if operation == 0:
                code += word(value)
        code.append(0x0d)
        native.cpu.mem_write(0x20400, bytes(code))
        native.cpu.mem_write(0x8fffc, word(0x4400))
        for register, value in [('CS', 0x1000), ('DS', 0x1fc0), ('ES', 0x1fc0), ('SS', 0x8000),
                                ('SP', 0xfffc), ('SI', 0x801), ('DI', 0xfc00), ('AX', 0xfc00 | code[0])]:
            native.setreg(register, value)
        results = []
        def hook(cpu, address, size, data):
            if address == native.BASE+0xfcf6:
                x, y = struct.unpack('<hh', cpu.mem_read(0x1fc00+native.getreg('DI'), 4))
                depth = native.getreg('CX')
                results.append((x, y, depth))
        native.cpu.hook_add(UC_HOOK_CODE, hook)
        native.cpu.emu_start(native.BASE+0xfc00+code[0], native.BASE+0x4400, count=20000)
        assert native.getreg('IP') == 0x4400 and len(results) == len(operations)
        cases.append((axes, base, origin, operations, results))
    lines = ['#pragma once', '', '// Generated by tools/generate_model_projection_reference.py; original FCxx/FDxx/FFxx coordinate interpreter',
             '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct projection_step { int operation, axis, value, x, y, depth; };', 'struct projection_sequence {',
             '  std::array<int, 9> axes;', '  std::array<int, 6> base;', '  std::array<int, 2> origin;', '  std::array<projection_step, 32> steps;', '};',
             f'inline constexpr std::array<projection_sequence, {len(cases)}> projection_sequences{{{{']
    for axes, base, origin, operations, results in cases:
        lines.append('  {{'+', '.join(map(str, axes))+'}, {'+', '.join(map(str, base))+'}, {'+', '.join(map(str, origin))+'}, {{')
        for operation, result in zip(operations, results):
            lines.append('    {'+', '.join(map(str, (*operation, *result)))+'},')
        lines.append('  }}},')
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/model_projection_samples.h').write_text('\n'.join(lines))
    print('Captured 768 native projected vertices in 24 uninterrupted coordinate-update sequences.')


if __name__ == '__main__':
    main()
