#!/usr/bin/env python3
"""Build compact C++ test fixtures from existing native HUD traces (development only)."""
import argparse
import hashlib
import json
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1] / 'tests/reference/navigation_samples.h')
    args = parser.parse_args()
    compass_path = args.workspace / 'analysis/interface/sprites/procedural-hud.json'
    radar_path = args.workspace / 'analysis/interface/dynamic/verification.json'
    compass = json.loads(compass_path.read_text())['compass']['phases']
    radar = json.loads(radar_path.read_text())['radar_checks']
    lines = ['#pragma once', '', '// Generated by tools/generate_navigation_reference.py from original-code captures',
             '// Compass trace SHA-256: ' + hashlib.sha256(compass_path.read_bytes()).hexdigest(),
             '// Radar trace SHA-256: ' + hashlib.sha256(radar_path.read_bytes()).hexdigest(), '', '#include <array>',
             '#include "graphics/navigation_hud.h"', '', 'namespace darker::test_reference {', '',
             'inline std::array<std::array<graphics::pixel_position, 5>, 136> constexpr compass{{']
    assert len(compass) == 136
    for phase, frame in enumerate(compass):
        assert phase == frame['phase']
        lines.append('  {{' + ', '.join(f'{{.x{{{p["x"]}}}, .y{{{p["y"]}}}}}' for p in frame['draw']) + '}},')
    lines += ['}};', '', 'struct radar_sample {', '  std::uint16_t heading;', '  int x;', '  int y;',
              '  graphics::radar_group group;', '  std::optional<graphics::radar_pixel> pixel;', '};', '',
              f'inline std::array<radar_sample, {len(radar)}> const radar{{{{']
    for sample in radar:
        group = 'a' if sample['kind'] == 0 else 'b'
        pixel = '{}'
        if sample['points']:
            assert len(sample['points']) == 1
            x, y, colour = sample['points'][0]
            pixel = f'{{graphics::radar_pixel{{.position{{.x{{{x}}}, .y{{{y}}}}}, .colour{{{colour}}}}}}}'
        lines.append(f'  {{.heading{{{sample["heading"]}}}, .x{{{sample["x"]}}}, .y{{{sample["y"]}}}, .group{{graphics::radar_group::{group}}}, .pixel{pixel}}},')
    lines += ['}};', '', 'struct skimma_sample {', '  bool bearing;', '  unsigned int index;',
              '  std::uint8_t state;', '  std::uint64_t checksum;', '};', '']
    sprite_path = args.workspace / 'analysis/interface/sprites/sprites.json'
    assets = json.loads(sprite_path.read_text())['assets']
    samples = [a for a in assets if a['resource'] == 17 and a['category'] == 'callbacks'
               and (a['descriptor'] == 0x52e0 or a['source_state'] == 0)]
    lines += ['// Sprite geometry SHA-256: ' + hashlib.sha256(sprite_path.read_bytes()).hexdigest(),
              f'inline std::array<skimma_sample, {len(samples)}> constexpr skimma{{{{']
    cache = bytes((i * 17 + 3) % 251 for i in range(320 * 240))
    for asset in samples:
        screen = bytearray(cache)
        sx, sy, width, height = asset['source']
        dx, dy = asset['destination']
        for y in range(height):
            for x in range(width):
                if asset['coverage'][y * width + x]:
                    screen[(dy+y)*320+dx+x] = cache[(sy+y)*320+sx+x]
        checksum = 14695981039346656037
        for byte in screen:
            checksum = ((checksum ^ byte) * 1099511628211) & ((1 << 64) - 1)
        index = int(asset['id'].split('-')[-2])
        bearing = asset['descriptor'] == 0x5227
        state = index + 1 if bearing else asset['source_state']
        lines.append(f'  {{.bearing{{{str(bearing).lower()}}}, .index{{{index}}}, .state{{{state}}}, .checksum{{0x{checksum:016x}ULL}}}},')
    lines += ['}};', '', 'struct ring_sample {', '  std::uint8_t weapon;', '  std::uint8_t radius;',
              '  std::uint8_t remaining;', '  std::uint64_t checksum;', '};', '']
    procedural_path = args.workspace / 'analysis/interface/dynamic/procedural.json'
    procedural = json.loads(procedural_path.read_text())
    rings = procedural['verification']['ring_cases']
    lines += ['// Ring trace SHA-256: ' + hashlib.sha256(procedural_path.read_bytes()).hexdigest(),
              f'inline std::array<ring_sample, {len(rings)}> constexpr rings{{{{']
    for sample in rings:
        screen = bytearray(cache)
        for blit in sample['blits']:
            sx, sy = blit['source']
            dx, dy = blit['destination']
            for y, (skip, width) in enumerate(procedural['ring']['mask_rows']):
                for x in range(skip, skip + width):
                    screen[(dy+y)*320+dx+x] = cache[(sy+y)*320+sx+x]
        checksum = 14695981039346656037
        for byte in screen:
            checksum = ((checksum ^ byte) * 1099511628211) & ((1 << 64) - 1)
        lines.append(f'  {{.weapon{{{sample["weapon"]}}}, .radius{{{sample["radius"]}}}, .remaining{{{sample["count"]}}}, .checksum{{0x{checksum:016x}ULL}}}},')
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    args.output.write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
