#!/usr/bin/env python3
"""Capture native E1FE glyph coverage, two-colour plane selections and advances."""
import argparse
import hashlib
from pathlib import Path
import struct
from unicorn import Uc, UC_ARCH_X86, UC_MODE_16, UC_HOOK_MEM_WRITE, UC_HOOK_INSN
from unicorn.x86_const import *
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(image).hexdigest() == IMAGE_SHA256
    fonts = (args.workspace/'analysis/resources/00_029.bin').read_bytes()
    cpu = Uc(UC_ARCH_X86, UC_MODE_16)
    cpu.mem_map(0, 0x100000)
    cpu.mem_write(0x10000, image)
    cpu.mem_write(0x62978, fonts)
    cpu.mem_write(0x10000, struct.pack('<256H', *(i*256 for i in range(256))))
    current = [0]
    pixels = {}

    def output(cpu, port, size, value, _):
        if port == 0x3c5:
            current[0] = value

    def write(cpu, access, address, size, value, _):
        if 0x50000 <= address < 0x60000:
            off = address - 0x50000
            for plane in range(4):
                if current[0] & (1 << plane):
                    x, y = (off % 256)*4 + plane, off//256
                    assert 0 <= x < 320 and 0 <= y < 240
                    pixels[y*320+x] = 2 if current[0] & (16 << plane) else 1

    cpu.hook_add(UC_HOOK_INSN, output, None, 1, 0, UC_X86_INS_OUT)
    cpu.hook_add(UC_HOOK_MEM_WRITE, write)

    def call(entry, registers):
        for reg, value in {UC_X86_REG_CS:0x1000, UC_X86_REG_DS:0x1000, UC_X86_REG_SS:0x6000,
                           UC_X86_REG_SP:0xfffc, UC_X86_REG_EFLAGS:2, **registers}.items():
            cpu.reg_write(reg, value)
        cpu.mem_write(0x6fffc, b'\x00\xf0')
        cpu.emu_start(0x10000+entry, 0x1f000, count=100000)
        assert cpu.reg_read(UC_X86_REG_IP) == 0xf000

    rows = []
    for face, (offset, count, spacing) in enumerate([(0,107,0x90),(0x226a,97,0x42),(0x3758,96,0x42)]):
        call(0xe29c, {UC_X86_REG_AX:0x2978+offset, UC_X86_REG_DX:spacing*256+count, UC_X86_REG_DI:0x6000})
        cpu.ctl_remove_cache(0x1e1fe,0x1e29c)
        for phase in range(4):
            fingerprint = 0xcbf29ce484222325
            for code in range(32,33+count):
                pixels.clear()
                call(0xe1fe,{UC_X86_REG_AX:code,UC_X86_REG_DX:8+phase,UC_X86_REG_DI:9,UC_X86_REG_ES:0x5000})
                values = [cpu.reg_read(UC_X86_REG_DX),len(pixels)]
                for offset,value in sorted(pixels.items()): values += [offset,value]
                for value in values:
                    for byte in value.to_bytes(4,'little'):
                        fingerprint = ((fingerprint ^ byte)*0x100000001b3)&((1<<64)-1)
            rows.append((face,phase,count,fingerprint))
    lines = ['#pragma once','','// Generated by tools/generate_font_reference.py; native E29C/E1FE coverage and plane patterns',
             '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','#include <cstdint>','','namespace darker::test_reference {','',
             'struct font_sample { unsigned int face, phase, count; std::uint64_t fingerprint; };',
             'inline constexpr std::array<font_sample, 12> font_samples{{']
    lines += [f'  {{{face}, {phase}, {count}, 0x{fingerprint:016x}}},' for face,phase,count,fingerprint in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/font_samples.h').write_text('\n'.join(lines))
    print('Captured 1,200 glyphs and 12 spaces from the native drawing routine.')


if __name__ == '__main__':
    main()
