#!/usr/bin/env python3
"""Capture camera coefficients and cell-origin transforms from original instructions."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256
from native_flat_model import render, fingerprint


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    random_source = random.Random(0x1d632e21)
    boundary = (0, 1, 48, 49, 63, 64, 16383, 16384, 32767, 32768, 49152, 65520, 65521, 65535)
    angles = [(h, p, r) for h in (0, 16384, 32768, 49152) for p in (0, 8192, 49152) for r in (0, 16384, 32768)]
    angles += [(v, v, v) for v in boundary]
    angles += [tuple(random_source.randrange(65536) for _ in range(3)) for _ in range(206)]
    cases = []
    word = lambda value: struct.pack('<H', value & 65535)
    for rotation in angles:
        native = Harness(image)
        native.write(0x9c4a, image[0x944a:0x964a])  # Runtime cosine extension of the sine table.
        for register, angle in zip(('DI', 'BX', 'CX'), rotation):
            native.setreg(register, (((angle+15)&65535)>>6)*2)
        native.call(0x1d63)
        coefficients = [struct.unpack('<h', native.read(at, 2))[0] for at in
                        (0xfd05, 0xfd12, 0xfd1f, 0xfd31, 0xfd3e, 0xfd4b, 0xfd5d, 0xfd6a, 0xfd77)]
        camera = [random_source.randrange(65536) for _ in range(3)]
        origin = [random_source.randrange(65536) for _ in range(3)]
        for address, value in zip((0x2e28, 0x2e2c, 0x2e36), camera):
            native.write(address, word(value))
        native.cpu.ctl_remove_cache(native.BASE+0x2e21, native.BASE+0x2eab)
        for register, value in zip(('AX', 'BX', 'DI'), origin):
            native.setreg(register, value)
        native.setreg('BP', 0xe000)
        native.call(0x2e21)
        result = [native.getreg('DX'), native.read(0x2b12)[0], native.getreg('SI'), native.getreg('CX')>>8,
                  native.getreg('BX'), native.getreg('CX')&255, struct.unpack('<H', native.cpu.mem_read(native.STACK+0xe00e, 2))[0]]
        cases.append((rotation, camera, origin, coefficients, result))
    lines = ['#pragma once', '', '// Generated by tools/generate_camera_reference.py; original 1D63 and 2E21',
             '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct camera_sample {', '  std::array<std::uint16_t, 3> angles, camera, origin;',
             '  std::array<std::int16_t, 9> coefficients;', '  std::array<std::uint16_t, 7> result;', '};',
             f'inline constexpr std::array<camera_sample, {len(cases)}> camera_samples{{{{']
    lines += ['  {'+', '.join('{'+', '.join(map(str, values))+'}' for values in row)+'},' for row in cases]
    lines += ['}};', '', 'struct camera_model_sample { unsigned int slot, heading, pitch; std::uint64_t fingerprint; };']
    from inspect_city import geometry_bank
    frames = []
    for slot in (30, 31):
        data = (args.workspace/f'analysis/resources/00_{slot:03}.bin').read_bytes()
        bank = geometry_bank(data, slot)
        pool = data[bank['pool_start']:bank['tail_start']]
        for heading in range(0, 65536, 4096):
            for pitch in (0, 12000, 53536):
                native = Harness(image)
                native.write(0x9c4a, image[0x944a:0x964a])
                for register, angle in zip(('DI', 'BX', 'CX'), (heading, pitch, 0)):
                    native.setreg(register, (((angle+15)&65535)>>6)*2)
                native.call(0x1d63)
                coefficients = [struct.unpack('<h', native.read(at, 2))[0] for at in
                                (0xfd05, 0xfd12, 0xfd1f, 0xfd31, 0xfd3e, 0xfd4b, 0xfd5d, 0xfd6a, 0xfd77)]
                pixels = render(Harness, image, pool, bank['types'][29]['geometry_pool_offset'], coefficients,
                                [0, 0, 0, 0, 2048, 0], [160, 110], list(range(28)), 17, 168 if slot == 30 else 180)
                frames.append((slot, heading, pitch, fingerprint(pixels)))
        print(f'Bank {slot}: camera render comparisons captured', flush=True)
    lines += [f'inline constexpr std::array<camera_model_sample, {len(frames)}> camera_model_samples{{{{']
    lines += ['  {'+f'{slot}, {heading}, {pitch}, 0x{value:016x}'+'},' for slot, heading, pitch, value in frames]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/camera_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} camera setups and cell placements.')


if __name__ == '__main__':
    main()
