#!/usr/bin/env python3
"""Capture native actor manoeuvre decisions after target and obstacle resolution."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    h = Harness(raw)
    rng = random.Random(0x89a3)
    rows = []
    captured = {}

    def hook(cpu, address, size, data):
        if address == h.BASE + 0x8afd:
            captured['fire'] = h.getreg('DX') >> 8
            sp = h.getreg('SP')
            ip = int.from_bytes(cpu.mem_read(h.STACK + sp, 2), 'little')
            h.setreg('SP', sp + 2)
            h.setreg('IP', ip)
        elif address == h.BASE + 0x8351:
            # The decision has finished; preserve its inputs, then return directly to the harness.
            sp = h.getreg('SP')
            captured['output'] = [h.getreg('DX'), h.getreg('DI'),
                                  int.from_bytes(cpu.mem_read(h.STACK + sp + 2, 2), 'little') & 255,
                                  captured.get('fire', -1)]
            h.setreg('IP', h.RETURN)

    h.cpu.hook_add(UC_HOOK_CODE, hook)
    for i in range(2048):
        captured.clear()
        heading, height, awareness, target_heading, target_pitch = [rng.randrange(65536) for _ in range(5)]
        distance = rng.choice([0, 100, 512, 768, 1024, 32767, 32768, rng.randrange(65536)])
        climb = rng.randrange(256) if i % 4 == 0 else 0
        if i % 4 == 1:
            target_heading = (heading + rng.randrange(-2048, 2048)) & 65535
        behaviour = [rng.randrange(256), rng.randrange(256)]
        definition = [rng.randrange(256) for _ in range(4)]  # base speed, nominal height, E and F
        obj = bytearray(112)
        struct.pack_into('<H', obj, 0x2a, heading)
        struct.pack_into('<H', obj, 0x0c, height)
        struct.pack_into('<H', obj, 0x56, awareness)
        struct.pack_into('<H', obj, 0x44, 0xf000)
        obj[0x50], obj[0x55] = behaviour
        h.cpu.mem_write(h.STACK + 0xda00, bytes(obj))
        h.write(0xf009, bytes([definition[0]]))
        h.write(0xf00c, bytes([definition[1], 0, definition[2], definition[3]]))
        h.write(0x89a4, struct.pack('<H', target_heading))
        h.write(0x88ad, struct.pack('<H', target_pitch))
        h.write(0x89ae, bytes([climb]))
        h.write(0x89b4, struct.pack('<H', distance))
        h.cpu.ctl_remove_cache(h.BASE, h.BASE + 65536)
        h.setreg('BP', 0xda00)
        h.call(0x89a3)
        rows.append(([heading, height, awareness, target_heading, target_pitch, distance, climb, *behaviour, *definition], captured['output']))
    lines = ['#pragma once', '', '// Generated by tools/generate_actor_navigation_reference.py; native 89A3–8A51',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct actor_navigation_sample { std::array<int, 13> input; std::array<int, 4> output; };',
             'inline constexpr std::array<actor_navigation_sample, 2048> actor_navigation_samples{{']
    lines += ['  {{' + ', '.join(map(str, a)) + '}, {' + ', '.join(map(str, b)) + '}},' for a, b in rows]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/actor_navigation_samples.h').write_text('\n'.join(lines))
    print('Captured 2,048 native manoeuvre decisions, including', sum(b[3] >= 0 for a, b in rows), 'firing checks.')


if __name__ == '__main__':
    main()
