#!/usr/bin/env python3
"""Capture original script-33 byte arithmetic, including signed-clamp and wrap boundaries."""
import argparse
import hashlib
from pathlib import Path
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from verify_mission_scheduler import Probe,IMAGE
    assert hashlib.sha256(IMAGE).hexdigest()==IMAGE_SHA256
    rows=[]
    for count in range(256):
        for operand in (0,1,127,206,255):
            h=Probe(bytes([0x33,operand,0x23]),1000)
            h.write(0xc16f,bytes([count]));result=h.update(1000)
            assert result['resume']==0xc50f
            rows.append((count,operand,h.read(0xc16f)[0]))
    lines=['#pragma once','','// Generated by tools/generate_objective_counter_reference.py; original C16D',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           f'inline constexpr std::array<std::array<int, 3>, {len(rows)}> objective_counter_samples{{{{']
    lines+=['  {'+', '.join(map(str,row))+'},' for row in rows]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/objective_counter_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} native objective counter adjustments.')


if __name__=='__main__':main()
