#!/usr/bin/env python3
"""Execute player collision admission and both sides of original 6ED4 ramming damage."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('workspace',type=Path)
    root=p.parse_args().workspace.resolve();sys.path.insert(0,str(root/'tools'))
    from verify_player_collisions import setup
    from unicorn import UC_HOOK_CODE
    assert hashlib.sha256((root/'analysis/unpacked/image.bin').read_bytes()).hexdigest()==IMAGE_SHA256
    h,bank,_=setup(30);h.cpu.mem_write(0x6a004,b'\xff');effects=[]
    def hook(cpu,address,size,data):
        if address-h.BASE in (0x680c,0x6815):
            effects.append(h.getreg('SI'));sp=h.getreg('SP')
            h.setreg('IP',int.from_bytes(cpu.mem_read(h.STACK+sp,2),'little'));h.setreg('SP',sp+2)
    h.cpu.hook_add(UC_HOOK_CODE,hook);rng=random.Random(0x6ed4);rows=[]
    def put(bp,at,value):h.cpu.mem_write(h.STACK+bp+at,struct.pack('<H',value&65535))
    def get(bp,at):return int.from_bytes(h.cpu.mem_read(h.STACK+bp+at,2),'little')
    def data(at):return int.from_bytes(h.read(at,2),'little')
    for case in range(512):
        craft=rng.choice([25,26,27]);seed=rng.randrange(65536);clock=rng.randrange(65536);flags=rng.choice([0,0,8,16,32,40])
        enabled=rng.randrange(2);charge=rng.randrange(65536);damage=rng.choice([0,67,0x343]);rotation=[rng.randrange(65536) for _ in range(2)]
        start=[16000+rng.randrange(-120,121),16000+rng.randrange(-120,121),3000+rng.randrange(-200,201)]
        end=[16000+rng.randrange(-120,121),16000+rng.randrange(-120,121),3000+rng.randrange(-200,201)]
        slot=rng.choice([19,20,21,22,23,29,31]);vflags=rng.choice([0,8,16,32,40]);position=[16000,16000,3000]
        vr=[rng.randrange(65536) for _ in range(2)];awareness=[rng.randrange(65536) for _ in range(2)];category=rng.randrange(3);underground=rng.randrange(2)
        for bp,pose,rates,objflags,definition in [(0xd986,end,rotation,flags,craft),(0xdb00,position,vr,vflags,slot)]:
            h.cpu.mem_write(h.STACK+bp,bytes(112));h.cpu.mem_write(h.STACK+bp+7,bytes([objflags]))
            for axis,value in enumerate(pose):put(bp,8+axis*2,value)
            for axis,value in enumerate(rates):put(bp,0x26+axis*2,value)
            put(bp,0x44,0x1926+definition*24);put(bp,0x22,bank['special_offsets'][definition]+0x400);put(bp,0x66,0x8823)
        for axis,value in enumerate(start):put(0xd986,0x38+axis*2,value)
        put(0xdb00,0x56,awareness[0]);put(0xdb00,0x64,awareness[1])
        h.write(0x6fd0,struct.pack('<H',0xd986))
        for n,address in enumerate([0x6fd8,0x6fc8,0x6fb0]):h.write(address,struct.pack('<H',0xdb00 if n==category else 0))
        for at,value in [(0xbf8,clock),(0x92d3,seed),(0x8109,charge),(0x8509,damage)]:h.write(at,struct.pack('<H',value))
        h.write(0xb91f,bytes([craft]));h.write(0x4552,bytes([enabled]));h.write(0x84de,b'\x3c');h.write(0x6202,bytes([2*underground]))
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);effects.clear();h.setreg('DS',0x1000)
        h.setreg('DI',0x6fd0);h.setreg('SI',0x7008);h.setreg('AX',0x0c20);h.call(0x6df1)
        result=[get(0xd986,a) for a in (8,10,12,0x26,0x28)]+[data(a) for a in (0x8509,0x8109,0x92d3)]
        result += [get(0xdb00,a) for a in (0x26,0x28,0x56,0x64,0x66,0x68)]+[h.cpu.mem_read(h.STACK+0xdb07,1)[0],int(0x70f0 in effects)]
        rows.append([craft,seed,clock,flags,enabled,charge,damage,*rotation,*start,*end,slot,vflags,*position,*vr,*awareness,category,underground,*result])
    width=len(rows[0]);lines=['#pragma once','','// Generated by tools/generate_player_ramming_reference.py; native 6DF1/6ED4, visual effect spawning intercepted',
      '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',f'inline constexpr std::array<std::array<int,{width}>,{len(rows)}> player_ramming_samples{{{{']
    lines+=['  {'+','.join(map(str,r))+'},' for r in rows];lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/player_ramming_samples.h').write_text('\n'.join(lines))
    print('Captured',len(rows),'player collision passes;',sum(r[-1] for r in rows),'ramming responses.')


if __name__=='__main__':main()
