"""Capture Caero Weapon beacon-dependent strength from native CF21."""
import argparse,sys,struct,hashlib,random
from pathlib import Path
def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    root=parser.parse_args().workspace.resolve()
    sys.path[:0]=[str(root/'tools'),str(root/'darker-cpp/tools')]
    from trace_hidden_commands import Harness
    from generate_resource_directory import IMAGE_SHA256
    from unicorn import UC_HOOK_CODE
    raw=(root/'analysis/unpacked/image.bin').read_bytes();assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    h=Harness(raw);h.setreg('ES',0x6000);h.cpu.emu_start(h.BASE+0x396,h.BASE+0x3ab,count=5000);lut=bytes(h.cpu.mem_read(0x6a800,256))
    rng=random.Random(0xcf21);rows=[]
    for i in range(2048):
     h=Harness(raw);h.write(0xfdf0,struct.pack('<H',0x6000));h.cpu.mem_write(0x6a800,lut)
     x=rng.randrange(8192,10240);y=rng.randrange(8192,10240);z=rng.choice((0,2400,11616,65535,rng.randrange(16000)));state=rng.randrange(256);kind=rng.choice((1,1,1,0,11));victim=(0xd986+112*rng.randrange(1,70))&65535
     h.cpu.mem_write(0x60000+36*256+36*2,bytes([kind,state]));result=[]
     def stop(cpu,a,s,d):
      if a==h.BASE+0xce26:result.append(h.getreg('AX')>>8);h.setreg('IP',h.RETURN)
     h.cpu.hook_add(UC_HOOK_CODE,stop)
     for k,v in [('AX',victim),('DX',x),('BX',y),('CX',z)]:h.setreg(k,v)
     h.call(0xcf21);assert len(result)==1
     rows.append([x,y,z,kind,state,victim,result[0]])
    lines=['#pragma once','','// Generated by tools/generate_caero_impact_reference.py; native CF21 and 8450','#include <array>','','namespace darker::test_reference {','',f'inline constexpr std::array<std::array<unsigned int,7>,{len(rows)}> caero_impact_samples{{{{']
    lines+=['  {'+','.join(map(str,r))+'},' for r in rows];lines+=['}};','','} // namespace darker::test_reference','']
    (root/'darker-cpp/tests/reference/caero_impact_samples.h').write_text('\n'.join(lines));print('Captured',len(rows),'Caero Weapon impacts')


if __name__ == "__main__":
    main()
