#!/usr/bin/env python3
"""Capture the native mode-one starting placement and shield restoration."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    root=parser.parse_args().workspace.resolve()
    sys.path.insert(0,str(root/'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    raw=(root/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    rng=random.Random(0xbd34)
    rows=[]
    for i in range(256):
        h=Harness(raw)
        site=rng.randrange(128)*256+rng.randrange(128)*2
        heading=rng.randrange(256);height=rng.randrange(65536);shield=rng.randrange(65536)
        word=lambda v:struct.pack('<H',v&65535)
        h.cpu.mem_write(h.STACK+0xd986,bytes(112));h.cpu.mem_write(h.STACK+0xd9a8,word(0x1200))
        h.write(0xfdf0,word(0x6000));h.write(0x3142,word(0x7000));h.cpu.mem_write(0x71207,word(height))
        h.cpu.mem_write(0x60000+site,b'\x03\0');h.write(0xc81e,word(site));h.write(0xbd56,bytes([heading]))
        h.write(0x6202,b'\x01');h.write(0xf003,b'\x03');h.write(0x8109,word(shield));h.setreg('BP',0xd986)
        def hook(cpu,address,size,data):
            if address==h.BASE+0xbd98:h.setreg('IP',h.RETURN)
        h.cpu.hook_add(UC_HOOK_CODE,hook);h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);h.call(0xbd34)
        assert h.getreg('IP')==h.RETURN
        values=[int.from_bytes(h.cpu.mem_read(h.STACK+0xd986+p,2),'little') for p in (8,10,12,0x2a,0x2c)]
        values += [h.cpu.mem_read(h.STACK+0xd98d,1)[0],int.from_bytes(h.read(0x8109,2),'little')]
        rows.append([site,heading,height,shield,*values])
    lines=['#pragma once','','// Generated by tools/generate_skimma_start_reference.py; native BD34–BD98',
      '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
      f'inline constexpr std::array<std::array<int,11>,{len(rows)}> skimma_start_samples{{{{']
    lines += ['  {'+', '.join(map(str,r))+'},' for r in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/skimma_start_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} original Skimma starting placements.')


if __name__ == '__main__': main()
