#!/usr/bin/env python3
"""Capture the native supply-pad entry predicates and projected target writes."""
import argparse
import hashlib
from pathlib import Path
import random
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from verify_mission_context_entry import fixture
    from unicorn import UC_HOOK_CODE
    raw=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    rng=random.Random(0xc6fb)
    rows=[]
    for i in range(1024):
        h=fixture();h.write(0x9c4a,raw[0x944a:0x964a])
        heading=rng.randrange(65536)
        subx,suby=[rng.choice((0,35,36,128,219,220,255)) for _ in range(2)]
        signed=lambda v:v-256 if v>=128 else v
        x=(0x1000+subx+signed(h.read(0x944b+(heading>>6)*2)[0]))&65535
        y=(0x2000+suby+signed(h.read(0x964b+(heading>>6)*2)[0]))&65535
        height=rng.choice((263,264,512,1023,1024))
        horizontal=rng.choice((0,100,319,320,65535))
        vertical=rng.choice((0,0xfeff,0xff00,0xffff))
        flags=rng.choice((0,0,16,32))
        engine=rng.choice((0,0,1))
        kind=rng.choice((0,3,3,4))
        h.cpu.mem_write(0x60000,bytes(32768));h.cpu.mem_write(0x62020,bytes([kind,rng.randrange(256)]))
        for field,value in [(8,x),(10,y),(12,height),(0x2a,heading),(0x42,horizontal),(0x40,vertical)]:h.word(h.BP+field,value,True)
        h.cpu.mem_write(h.STACK+h.BP+7,bytes([flags]));h.write(0x4552,bytes([engine]))
        h.word(0xc81e,0x1234);h.word(0x7da9,0x5678)
        entered=[]
        def hook(cpu,address,size,data):
            if address == h.BASE+0xc776: entered.append(True);h.setreg('IP',h.RETURN)
        h.cpu.hook_add(UC_HOOK_CODE,hook);h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);h.call(0xc6fb)
        assert h.getreg('IP') == h.RETURN
        rows.append([x,y,height,heading,horizontal,vertical,flags,engine,kind,int(bool(entered)),
          h.word(0xc81e),h.word(0x7da9),h.cpu.mem_read(h.STACK+h.BP+7,1)[0]])
    lines=['#pragma once','','// Generated by tools/generate_supply_entry_reference.py; native C6FB',
      '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
      f'inline constexpr std::array<std::array<int,13>,{len(rows)}> supply_entry_samples{{{{']
    lines += ['  {'+', '.join(map(str,r))+'},' for r in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/supply_entry_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} supply-entry cases; {sum(r[9] for r in rows)} accepted.')


if __name__ == '__main__': main()
