#!/usr/bin/env python3
"""Capture ordered native map cells visited by collision sweeps."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    image=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest()!=IMAGE_SHA256:raise ValueError('Unsupported unpacked executable')
    h=Harness(image);h.write(0x652d,struct.pack('<H',10))
    cells=[]
    def capture(cpu,address,size,data):
        if address-h.BASE==0x6018:
            cells.append(h.getreg('BX'))
            # Supply an empty cell without disturbing traversal registers.
            sp=h.getreg('SP');target=int.from_bytes(cpu.mem_read(h.STACK+sp,2),'little')
            h.setreg('SP',sp+2);h.setreg('IP',target);h.setreg('AX',0);h.setreg('EFLAGS',2)
    h.cpu.hook_add(UC_HOOK_CODE,capture)
    rng=random.Random(0x6527);cases=[]
    for index in range(4096):
        x=rng.randrange(65536);y=rng.randrange(65536)
        dx=rng.randrange(-1500,1501);dy=rng.randrange(-1500,1501)
        if index%4==0:dy=dx
        if index%4==1:dy=-dx
        if index%8==2:dx=0
        if index%8==3:dy=0
        values=[x,y,(x+dx)&65535,(y+dy)&65535]
        for reg,value in zip(('AX','BX','CX','DX'),values):h.setreg(reg,value)
        h.setreg('BP',200);h.setreg('DI',200);h.setreg('DS',0x1000)
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        cells.clear();h.call(0x6527)
        fingerprint=0xcbf29ce484222325
        for cell in cells:
            for byte in (cell&255,cell>>8):fingerprint=((fingerprint^byte)*0x100000001b3)&0xffffffffffffffff
        cases.append(values+[len(cells),fingerprint])
    lines=['#pragma once','','// Generated by tools/generate_collision_cells_reference.py; original 6527–662A',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','#include <cstdint>','','namespace darker::test_reference {','',
           'struct collision_cells_sample { unsigned int x, y, end_x, end_y, count; std::uint64_t fingerprint; };',
           f'inline constexpr std::array<collision_cells_sample, {len(cases)}> collision_cells_samples{{{{']
    lines+=['  {'+', '.join(map(str,case[:-1]))+f', 0x{case[-1]:016x}'+'},' for case in cases]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/collision_cells_samples.h').write_text('\n'.join(lines))
    print('Captured',len(cases),'native cell traversals.')


if __name__=='__main__':main()
