#!/usr/bin/env python3
"""Capture persistent native candidate admission and physical OPL voice ownership."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('workspace', type=Path)
args = parser.parse_args()
sys.path.insert(0, str(args.workspace / 'tools'))
from trace_hidden_commands import Harness
image = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
assert hashlib.sha256(image).hexdigest() == IMAGE_SHA256

class Probe(Harness):
    def hook(self, cpu, address, size, data):
        offset = address - self.BASE
        if offset == 0x33ee:
            self.setreg('IP', self.RETURN)
            return
        if offset in (0xf0a, 0x39a9):
            sp = self.getreg('SP')
            self.setreg('IP', int.from_bytes(cpu.mem_read(self.STACK + sp, 2), 'little'))
            self.setreg('SP', sp + 2)
            return
        super().hook(cpu, address, size, data)

h = Probe(image)
h.write(0xe81, b'\x01')
h.call(0xedb)
rng = random.Random(0x33d8)
frames = []
for frame in range(256):
    h.call(0x33d8)
    h.write(0x3497, b'\x02')
    ids = rng.sample(range(1,33), rng.randrange(25))
    sources = [(identity, rng.choice([100,200,300,400,500,65535])) for identity in ids]
    for identity, level in sources:
        h.cpu.ctl_remove_cache(h.BASE, h.BASE + 65536)
        for reg, value in [('AX',0),('BX',0),('CX',0),('DX',identity),('SI',level),('DI',400),('BP',0)]:
            h.setreg(reg,value)
        h.call(0x3488)
    h.cpu.ctl_remove_cache(h.BASE, h.BASE + 65536)
    h.call(0x33f1)
    owners = [0]*9
    at = int.from_bytes(h.read(0xf06,2),'little')
    while at:
        channel = (at-0x10ac)//8
        assert 0 <= channel < 9 and owners[channel] == 0
        owners[channel] = h.read(at+4)[0]
        at = int.from_bytes(h.read(at,2),'little')
    frames.append([len(sources), *[v for pair in sources for v in pair], *([0]*(48-2*len(sources))), *owners])
lines = ['#pragma once','','// Generated by tools/generate_voice_allocation_reference.py; native 3488/33F1',
         '// Image SHA-256: '+IMAGE_SHA256,'#include <array>','namespace darker::test_reference {',
         'inline std::array<std::array<unsigned int,58>,256> constexpr voice_allocation{{']
lines += ['  {'+', '.join(map(str,row))+'},' for row in frames]
lines += ['}};','} // namespace darker::test_reference','']
(Path(__file__).resolve().parents[1]/'tests/reference/voice_allocation_samples.h').write_text('\n'.join(lines))
print('Captured 256 consecutive native allocation frames, including ties, saturation and released voices.')
