#!/usr/bin/env python3
"""Capture player damage/kick, fractional shield recharge and peripheral repair."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    native = Harness(raw)
    word = lambda value: struct.pack('<H', value & 65535)
    def put(offset, value):
        native.cpu.mem_write(native.STACK+0xd986+offset, word(value))
    def get(offset):
        return int.from_bytes(native.cpu.mem_read(native.STACK+0xd986+offset, 2), 'little')
    def dsword(offset):
        return int.from_bytes(native.read(offset, 2), 'little')
    def patch(offset, data):
        native.write(offset, data)
        native.cpu.ctl_remove_cache(native.BASE+offset-8, native.BASE+offset+8)
    rng = random.Random(0x84d0)
    cases = []
    for craft in (25, 26, 27):
        for cheat in (0, 1):
            for amount in range(256):
                pitch, heading, seed, charge = [rng.randrange(65536) for _ in range(4)]
                damage = rng.choice((0, 67, 0x343, 0xffff))
                enabled = rng.randrange(2)
                amplitude = rng.randrange(256)
                put(0x26, pitch)
                put(0x28, heading)
                native.write(0xb91f, bytes([craft]))
                patch(0x84de, b'\xb0' if cheat else b'\x3c')
                native.write(0x4552, bytes([enabled]))
                patch(0x8109, word(charge))
                patch(0x8509, word(damage))
                patch(0x92d3, word(seed))
                native.setreg('AX', amount | amplitude << 8)
                native.call(0x84d0)
                result = [get(0x26), get(0x28), dsword(0x8509), dsword(0x8109), dsword(0x92d3)]
                cases.append([craft, cheat, amount, amplitude, pitch, heading, seed, charge, damage, enabled, *result])
    recharge = []
    for charge in (0, 1, 0xbeff, 0xbf00, 0xbfff, 0xc000, 0xffff):
        for step in (0, 1, 8, 127, 128, 255, 511, 32768, 65535):
            patch(0x8109, word(charge))
            native.setreg('CX', step)
            native.cpu.emu_start(native.BASE+0x8108, native.BASE+0x8118, count=20)
            assert native.getreg('IP') == 0x8118
            recharge.append([charge, step, dsword(0x8109)])
    repair = []
    # Separate DS from CS for this probe: Unicorn loses carry when 851F writes
    # its own translated block. MOV must preserve it for the following SBB.
    # Mirror the operands before each call, then read the results from DS.
    native.cpu.mem_write(0x20000, raw)
    native.setreg('DS', 0x2000)
    for damage in (0, 1, 67, 0x300, 0x343, 0xffff):
        for phase in (0, 511, 65535):
            for step in (0, 1, 8, 511, 65535):
                patch(0x8509, word(damage))
                patch(0x8518, word(phase))
                assert raw[0x8523] == 0
                native.cpu.mem_write(0x20000+0x8509, word(damage))
                native.cpu.mem_write(0x20000+0x8518, word(phase))
                native.setreg('CX', step)
                native.call(0x8514)
                result_damage = int.from_bytes(native.cpu.mem_read(0x20000+0x8509, 2), 'little')
                result_phase = int.from_bytes(native.cpu.mem_read(0x20000+0x8518, 2), 'little')
                repair.append([damage, phase, step, result_damage, result_phase])
    lines = ['#pragma once', '', '// Generated by tools/generate_player_damage_reference.py; native 84D0, 8108 and 8514',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct player_damage_sample {', '  int craft, cheat, amount, amplitude, pitch, heading, seed, charge, damage, enabled;',
             '  std::array<int, 5> result;', '};', f'inline constexpr std::array<player_damage_sample, {len(cases)}> player_damage_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row[:10])) + ', {' + ', '.join(map(str, row[10:])) + '}},' for row in cases]
    lines += ['}};', '', 'struct recharge_sample { int charge, step, result; };', f'inline constexpr std::array<recharge_sample, {len(recharge)}> recharge_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row)) + '},' for row in recharge]
    lines += ['}};', '', 'struct repair_sample { int damage, phase, step, result_damage, result_phase; };', f'inline constexpr std::array<repair_sample, {len(repair)}> repair_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row)) + '},' for row in repair]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/player_damage_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} player hits, {len(recharge)} shield updates and {len(repair)} repair updates.')


if __name__ == '__main__':
    main()
