#!/usr/bin/env python3
"""Execute fixed ambient callbacks and 3599 timer/voice feedback; intercept only spatial admission."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    root=parser.parse_args().workspace.resolve()
    sys.path.insert(0,str(root/'tools'))
    from trace_hidden_commands import Harness
    raw=(root/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    class Probe(Harness):
        emitted=False
        def hook(self,cpu,address,size,data):
            offset=address-self.BASE
            if offset==0x3488:
                self.emitted=True
                sp=self.getreg('SP')
                self.setreg('IP',int.from_bytes(cpu.mem_read(self.STACK+sp,2),'little'))
                self.setreg('SP',sp+2)
                return
            if offset==0x35f0:
                self.setreg('IP',self.RETURN)
                return
            super().hook(cpu,address,size,data)
    lookup=bytearray(256);index=0xbd;value=0xb8
    while True:
        value=(value+9)&255
        for _ in range(9):lookup[index]=value;index=(index+1)&255
        if value==0xbd:break
    addresses=[0x37a6,0x37ba,0x380a,0x381e,0x3832,0x3846,0x385a,0x386e,0x3882,0x3896]
    rng=random.Random(0x3599);rows=[]
    for i in range(1024):
        slot=i%10;address=addresses[slot];h=Probe(raw)
        x=rng.randrange(128);y=rng.randrange(128);clock=rng.randrange(65536)
        deadline=(clock+rng.choice([-4096,-16,0,16,4096]))&65535
        changes=rng.choice([0,512]);supplementary=rng.randrange(2);gate=rng.randrange(2)
        site=rng.randrange(128)*256+rng.randrange(128)*2
        state=rng.randrange(256);kind=rng.choice([0,1,1,12]);playing=rng.randrange(2)
        flags=raw[address+7] | rng.choice([0,8,40])
        record=bytearray(raw[address:address+20]);struct.pack_into('<H',record,0,deadline);record[7]=flags
        h.write(address,bytes(record));h.setreg('SI',address)
        h.write(0x2701,bytes([x]));h.write(0x271c,bytes([y]));h.write(0xbf0,struct.pack('<H',clock))
        h.write(0xc50,struct.pack('<H',changes));h.write(0x7e61,bytes([supplementary]))
        h.write(0xc81e,struct.pack('<H',site));h.write(0x3708,bytes([gate]))
        h.write(0xfdf0,struct.pack('<H',0x6000))
        h.cpu.mem_write(0x60000,bytes([kind,state])*16384);h.cpu.mem_write(0x6a800,bytes(lookup))
        h.cpu.mem_write(h.STACK+0x800,bytes([255 if playing else 0])*32)
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);h.call(0x3599)
        result=h.read(address,20)
        rows.append([slot,x,y,clock,deadline,changes,supplementary,gate,site,state,kind,playing,flags,
          int(h.emitted),struct.unpack_from('<H',result)[0],result[7],struct.unpack_from('<H',result,4)[0],
          *struct.unpack_from('<3H',result,8),struct.unpack_from('<H',result,14)[0]])
    lines=['#pragma once','','// Generated by tools/generate_ambient_sound_reference.py; native 3599 and fixed callbacks',
      '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
      f'inline constexpr std::array<std::array<int,21>,{len(rows)}> ambient_sound_samples{{{{']
    lines+=['  {'+', '.join(map(str,row))+'},' for row in rows]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/ambient_sound_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} native fixed-source updates.')


if __name__=='__main__':main()
