#!/usr/bin/env python3
"""Capture original non-player object sound callbacks, including damage and fading."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('workspace',type=Path)
    root=parser.parse_args().workspace.resolve();sys.path.insert(0,str(root/'tools'))
    from trace_hidden_commands import Harness
    raw=(root/'analysis/unpacked/image.bin').read_bytes();assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    rng=random.Random(0x3556);rows=[]
    slots=list(range(24))+list(range(29,33))
    for i in range(1024):
        h=Harness(raw);slot=rng.choice(slots);address=0x1926+slot*24
        callback=struct.unpack_from('<H',raw,address+18)[0]
        identity=rng.randrange(0xc000,0xe000);speed=rng.randrange(65536);pitch=rng.randrange(65536)
        clock=rng.randrange(65536);flags=rng.randrange(256);damage=rng.randrange(65536);fade=rng.randrange(256);deadline=rng.randrange(65536)
        obj=bytearray(112);obj[7]=flags;obj[0x6f]=fade
        for offset,value in [(0x2c,pitch),(0x3e,speed),(0x64,damage),(0x68,deadline)]:struct.pack_into('<H',obj,offset,value)
        h.cpu.mem_write(h.STACK+identity,bytes(obj));h.write(0xbf0,struct.pack('<H',clock))
        h.setreg('BP',identity);h.setreg('BX',address);h.setreg('SI',raw[address+21]*256+255);h.setreg('DI',struct.unpack_from('<H',raw,address+22)[0])
        h.call(callback);assert h.getreg('IP')==h.RETURN
        rows.append([slot,identity,speed,pitch,clock,flags,damage,fade,deadline,h.getreg('DI'),h.getreg('SI'),int(bool(h.getreg('EFLAGS')&64))])
    lines=['#pragma once','','// Generated by tools/generate_object_sound_reference.py; native 391D/393D/3942/3957/3969',
      '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
      f'inline constexpr std::array<std::array<int,12>,{len(rows)}> object_sound_samples{{{{']
    lines += ['  {'+', '.join(map(str,r))+'},' for r in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/object_sound_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} original object sound callbacks.')


if __name__=='__main__':main()
