#!/usr/bin/env python3
"""Execute native special object impacts, stopping at effect creation and list removal."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256

    class Impact(Harness):
        def hook(self, cpu, address, size, data):
            at = address - self.BASE
            if at in (0x680c, 0x6815):
                self.effect = self.getreg('SI')
                self.at_actor = int(at == 0x680c)
                sp = self.getreg('SP')
                self.setreg('IP', int.from_bytes(cpu.mem_read(self.STACK + sp, 2), 'little'))
                self.setreg('SP', sp + 2)
                return
            if at == 0x7a5d:
                self.remove = 1
                self.setreg('IP', self.RETURN)
                return
            super().hook(cpu, address, size, data)

    h = Impact(raw)
    rng = random.Random(0xce1e)
    rows = []
    for callback in (0, 0x8f3b):
        for role in (0, 2):
            for clock in (0, 255, 32767, 65279, 65280, 65535):
                for flags in (0, 2, 0x20):
                    expiry = rng.randrange(65536)
                    h.cpu.mem_write(h.STACK + 0xd000, bytes(112))
                    for offset, value in ((0x44, 0xf000), (0x66, callback), (0x68, expiry)):
                        h.cpu.mem_write(h.STACK + 0xd000 + offset, struct.pack('<H', value))
                    h.cpu.mem_write(h.STACK + 0xd007, bytes([flags]))
                    h.write(0xf008, b'\0'); h.write(0xf011, bytes([role]))
                    h.write(0xbf8, struct.pack('<H', clock))
                    h.setreg('BP', 0xd000); h.setreg('AX', 52 << 8)
                    h.effect = h.at_actor = h.remove = 0
                    h.call(0xce26)
                    rows.append([callback, role, clock, flags, expiry, h.effect, h.at_actor, h.remove,
                                 h.cpu.mem_read(h.STACK + 0xd007, 1)[0],
                                 int.from_bytes(h.cpu.mem_read(h.STACK + 0xd068, 2), 'little')])
    lines = ['#pragma once', '', '// Generated by tools/generate_actor_impact_reference.py; original CE26/CDFB/6EC7',
             '#include <array>', '', 'namespace darker::test_reference {', '',
             f'inline constexpr std::array<std::array<unsigned int,10>,{len(rows)}> actor_impact_samples{{{{']
    lines += ['  {' + ','.join(map(str, row)) + '},' for row in rows]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/actor_impact_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} special object impacts.')


if __name__ == '__main__':
    main()
