#!/usr/bin/env python3
"""Capture native callback scheduling when an actor or the player activates reserves."""
import argparse
import hashlib
from pathlib import Path
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from verify_mission_update_order import Frame
    assert hashlib.sha256((args.workspace/'analysis/unpacked/image.bin').read_bytes()).hexdigest()==IMAGE_SHA256
    rows=[]
    for player in (0,1):
        for ground in (0,1):
            h=Frame();opcode=10 if ground else 9
            if player:h.obj(h.BP,0xf100,bytes([opcode,1,0x23]),0xc002)
            else:
                h.obj(0x2000,0xf200,bytes([opcode,1,0x23]));h.word(0x6fd8,0x2000);h.word(0x6fda,0x2000)
            h.obj(0x3000,0xf300,b'\x23');header=0x6fc8 if ground else 0x6fd8;h.word(header+6,0x3000)
            results=[]
            for frame in range(2):results.append(int(any(event.get('object')==0x3000 for event in h.frame())))
            rows.append([player,ground,*results])
    lines=['#pragma once','','// Generated by tools/generate_actor_admission_reference.py; native 797B/79BB and script admission',
           '// Physics, firing and HUD work intercepted by the native Frame harness.','#include <array>','',
           'namespace darker::test_reference {','',f'inline constexpr std::array<std::array<unsigned int,4>,{len(rows)}> actor_admission_samples{{{{']
    lines+=['  {'+','.join(map(str,row))+'},' for row in rows]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/actor_admission_samples.h').write_text('\n'.join(lines))
    print('Captured four native two-frame reserve-admission traces.')


if __name__=='__main__':main()
