#!/usr/bin/env python3
"""Capture native 2D32 point projection and viewport acceptance."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    image = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(image).hexdigest() == IMAGE_SHA256
    h = Harness(image)
    hit = []

    def capture(cpu, address, size, data):
        if address == h.BASE + 0x2d82:
            hit.append((h.getreg('DX'), h.getreg('DI')))
            h.setreg('IP', 0x2d31)  # Return before the VGA pixel writer.

    h.cpu.hook_add(UC_HOOK_CODE, capture)
    word = lambda value: struct.pack('<H', value & 65535)
    h.write(0xfdec, word(0x1000))
    h.write(0x3142, word(0x7000))
    h.write(0x3385, word(0xe000))
    h.write(0xe000, bytes(range(28)))
    h.cpu.mem_write(0x70405, b'\x15')
    rng = random.Random(0x2d32)
    rows = []
    for n in range(512):
        depth = rng.randrange(512, 24000)
        limit = min(depth * 2, 32767)
        horizontal, vertical = rng.randrange(-limit, limit), rng.randrange(-limit, limit)
        bottom = (168, 240)[n % 2]
        origin = (160, bottom // 2)
        h.setreg('BP', 0x8000)
        h.setreg('DS', 0x1000)
        h.setreg('AX', 0)  # Supply initial AL; caller-dependent residue is outside this isolated fixture.
        for offset, value in ((8, horizontal), (10, depth), (12, vertical), (20, 0x400)):
            h.cpu.mem_write(h.STACK + 0x8000 + offset, word(value))
        for address, value in ((0xfccd, origin[0]), (0xfcf1, origin[1]), (0xa296, bottom), (0xa320, 320)):
            h.write(address, word(value))
        hit.clear()
        h.call(0x2d32)
        rows.append((horizontal, vertical, depth, bottom, *(hit[0] if hit else (-1, -1))))
    output = Path(__file__).resolve().parents[1] / 'tests/reference/distant_points_samples.h'
    output.write_text('#pragma once\n\n// Native 2D32; generated by generate_distant_points_reference.py\n'
                      '// Image SHA-256: ' + IMAGE_SHA256 + '\n#include <array>\n\nnamespace darker::test_reference {\n'
                      'inline constexpr std::array<std::array<int,6>,512> distant_points_samples{{\n'
                      + ''.join('  {' + ', '.join(map(str, row)) + '},\n' for row in rows)
                      + '}};\n}\n')
    print('Captured 512 distant-object projections;', sum(row[-1] >= 0 for row in rows), 'visible')


if __name__ == '__main__':
    main()
