#!/usr/bin/env python3
"""Capture native Chargeable firing, held charging and release through C9C2."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    rng = random.Random(0xca7d)
    rows = []
    for i in range(2048):
        reserve = rng.choice((0,6398,6399,6400,33022,33023,65535,rng.randrange(65536)))
        charge = rng.choice((0,1,15,16,65500,65535,rng.randrange(65536)))
        flags = rng.choice((0,0,0,16,32))
        free = int(i % 11 != 0)
        pressed, held = rng.randrange(2), rng.randrange(2)
        target = rng.choice((0xffff,0xd986,0xec00,0x1234,0x7fff))
        mode = rng.choice((0,2))
        step = rng.choice((0,1,8,80,1024,32768,65535,rng.randrange(65536)))
        h = Harness(raw)
        for address,value in ((0x7fa6,reserve),(0xca80,charge),(0x6fbc,0xd000 if free else 0),
                              (0xc9f7,0x40 if pressed else 0),(0xb9f4,0x40 if held else 0),
                              (0x5f0f,target),(0x7a2b,step)):
            h.write(address,struct.pack('<H',value))
        h.write(0x6202,bytes([mode]))
        h.cpu.mem_write(h.STACK+0xd98d,bytes([flags]))
        h.setreg('AL',9); h.setreg('SI',0x4545); h.setreg('DX',0x40)
        fired = []
        def hook(cpu,address,size,data):
            if address == h.BASE+0xcb01:
                fired.append(h.getreg('DX'))
                h.setreg('IP',h.RETURN)
        h.cpu.hook_add(UC_HOOK_CODE,hook)
        h.call(0xc9c2)
        assert h.getreg('IP') == h.RETURN
        rows.append([reserve,charge,flags,free,pressed,held,target,mode,step,
                     int.from_bytes(h.read(0x7fa6,2),'little'),int.from_bytes(h.read(0xca80,2),'little'),
                     int(h.read(0x4545)[0] == 0),int(bool(fired)),fired[0] if fired else 0])
    lines = ['#pragma once','','// Generated by tools/generate_chargeable_reference.py; native C9C2/CA7D',
             '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
             f'inline constexpr std::array<std::array<unsigned int,14>,{len(rows)}> chargeable_samples{{{{']
    lines += ['  {'+','.join(map(str,row))+'},' for row in rows]
    lines += ['}};','']
    impacts = []
    h = Harness(raw)
    hit = []
    def impact_hook(cpu,address,size,data):
        if address == h.BASE+0xce26:
            hit.append(h.getreg('AX') >> 8)
            h.setreg('IP',h.RETURN)
    h.cpu.hook_add(UC_HOOK_CODE,impact_hook)
    for remaining in range(65536):
        if remaining & 255 not in (0,1,127,255):
            continue
        clock = 65000
        deadline = (clock+remaining)&65535
        h.write(0xbf0,struct.pack('<H',clock))
        h.cpu.mem_write(h.STACK+0xd068,struct.pack('<H',deadline))
        h.setreg('BP',0xd000); h.setreg('AX',0xd100); h.setreg('DI',6)
        hit.clear()
        h.call(0xcf0e)
        assert h.getreg('IP') == h.RETURN
        impacts.append([deadline,clock,int(bool(hit)),hit[0] if hit else 0])
    lines += [f'inline constexpr std::array<std::array<unsigned int,4>,{len(impacts)}> chargeable_impact_samples{{{{']
    lines += ['  {'+','.join(map(str,row))+'},' for row in impacts]
    lines += ['}};','']
    tones = []
    for charge in (0,1,31,32,6399,16384,32768,65535):
        for clock in range(0,256,4):
            h.write(0xca80,struct.pack('<H',charge))
            h.write(0xbf0,struct.pack('<H',clock))
            h.write(0x5004,struct.pack('<H',433))
            h.setreg('SI',0x5000)
            h.call(0x370f)
            assert h.getreg('IP') == h.RETURN
            tones.append([charge,clock,int(not(h.getreg('FLAGS')&1)),int.from_bytes(h.read(0x5004,2),'little')])
    lines += [f'inline constexpr std::array<std::array<unsigned int,4>,{len(tones)}> chargeable_tone_samples{{{{']
    lines += ['  {'+','.join(map(str,row))+'},' for row in tones]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/chargeable_samples.h').write_text('\n'.join(lines))
    print('Captured',len(rows),'native Chargeable firing updates.')


if __name__ == '__main__':
    main()
