#!/usr/bin/env python3
"""Capture original C39E air-reserve placement including its real C313 neighbour scan."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    raw=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()==IMAGE_SHA256
    h=Harness(raw);rng=random.Random(0xc39e);rows=[]
    for i in range(1024):
        position=[rng.randrange(65536) for _ in range(3)]
        player=[(v+rng.randrange(-12000,12001))&65535 for v in position]
        neighbours=[]
        for n in range(3):
            neighbours.append([(position[0]+rng.choice((-256,-255,0,254,255,256)))&65535,
                               (position[1]+rng.choice((-256,-255,0,254,255,256)))&65535,
                               (position[2]+rng.choice((-513,-512,-1,0,511,512,513)))&65535])
        for at,pos,next_record in [(0xda00,position,0),(0xd986,player,0),
            *[(0xdb00+n*112,p,0xdb00+(n+1)*112 if n<2 else 0) for n,p in enumerate(neighbours)]]:
            obj=bytearray(112);struct.pack_into('<H',obj,0,next_record);struct.pack_into('<3H',obj,8,*pos)
            h.cpu.mem_write(h.STACK+at,bytes(obj))
        h.write(0x6fd8,struct.pack('<H',0xdb00));h.setreg('BP',0xda00);h.setreg('DI',0x6fd8)
        h.call(0xc39e)
        result=struct.unpack('<3H',bytes(h.cpu.mem_read(h.STACK+0xda08,6)))
        rows.append(position+player+[v for p in neighbours for v in p]+list(result))
    lines=['#pragma once','','// Generated by tools/generate_actor_activation_reference.py; native C39E/C313/6DB5',
           '#include <array>','','namespace darker::test_reference {','',
           f'inline constexpr std::array<std::array<unsigned int,18>,{len(rows)}> air_placement_samples{{{{']
    lines+=['  {'+','.join(map(str,row))+'},' for row in rows]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/actor_activation_samples.h').write_text('\n'.join(lines))
    print('Captured',len(rows),'full native air-reserve placements.')


if __name__=='__main__':main()
