#!/usr/bin/env python3
"""Capture the original straight-projectile update including speed smoothing."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    native = Harness(raw)
    native.write(0x9c4a, raw[0x944a:0x964a])
    native.write(0x5000, bytes(24))
    cases = []
    for heading, pitch in ((0, 0), (8192, 8192), (32768, 49152), (65535, 65535)):
        for step in (0, 1, 32, 127, 128, 255, 256, 65535):
            for speed in (0, 1000, 32767, 32768, 65535):
                for base in (0, 137, 255):
                    state = bytearray(112)
                    state[4:7] = bytes([255, 127, 1])
                    state[8:14] = struct.pack('<3H', 0, 65535, 0)
                    state[0x2a:0x30] = struct.pack('<3H', heading, pitch, 1234)
                    state[0x3e:0x40] = struct.pack('<H', speed)
                    state[0x44:0x46] = struct.pack('<H', 0x5000)
                    native.cpu.mem_write(native.STACK+0x6000, bytes(state))
                    native.write(0x5009, bytes([base]))
                    native.setreg('BP', 0x6000)
                    native.setreg('CX', step)
                    native.call(0xcc64)
                    output = bytes(native.cpu.mem_read(native.STACK+0x6000, 112))
                    allowed = {*range(4, 7), *range(8, 14), 0x3e, 0x3f}
                    assert all(output[i] == state[i] for i in range(112) if i not in allowed)
                    result = [*struct.unpack('<3H', output[8:14]), *output[4:7], int.from_bytes(output[0x3e:0x40], 'little')]
                    cases.append([heading, pitch, step, speed, base, *result])
    class Deadline(Harness):
        expired = False

        def hook(self, cpu, address, size, data):
            offset = address-self.BASE
            if offset in (0x7a18, 0x7a52):
                self.expired = offset == 0x7a52
                self.setreg('IP', self.RETURN)
                return
            super().hook(cpu, address, size, data)

    native = Deadline(raw)
    deadlines = []
    for flags in (0, 0x20, 0x40, 0x60, 0x28, 0x80):
        for delta in (-32768, -1, 0, 1, 255, 256, 32767):
            for altitude in (0, 0x4fff, 0x5000, 0x8000, 0xffff):
                state = bytearray(112)
                state[7] = flags
                state[12:14] = struct.pack('<H', altitude)
                state[0x68:0x6a] = struct.pack('<H', (65000+delta) & 65535)
                state[0x6f] = 123
                native.cpu.mem_write(native.STACK+0x6000, bytes(state))
                native.write(0xbf0, struct.pack('<H', 65000))
                native.setreg('BP', 0x6000)
                native.call(0x79e5)
                output = bytes(native.cpu.mem_read(native.STACK+0x6000, 112))
                deadlines.append([flags, delta, altitude, output[7], int.from_bytes(output[0x68:0x6a], 'little'), output[0x6f], int(native.expired)])
    lines = ['#pragma once', '', '// Generated by tools/generate_motion_reference.py via native CC64',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct motion_sample { int heading, pitch, step, speed, base; std::array<int, 7> result; };',
             f'inline constexpr std::array<motion_sample, {len(cases)}> motion_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row[:5])) + ', {' + ', '.join(map(str, row[5:])) + '}},' for row in cases]
    lines += ['}};', '', 'struct deadline_sample { int flags, delta, altitude, next_flags, deadline, fade, expired; };',
              f'inline constexpr std::array<deadline_sample, {len(deadlines)}> deadline_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row)) + '},' for row in deadlines]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/motion_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} movement updates and {len(deadlines)} deadline updates.')


if __name__ == '__main__':
    main()
