#!/usr/bin/env python3
"""Capture original Gouraud polygons with synthetic screen-space geometry."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256
from native_flat_model import render, fingerprint


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    shapes = [[(20,20),(100,20),(100,80),(20,80)], [(150,50),(151,50),(151,70),(150,70)],
              [(20,20),(25,20),(25,50),(20,50)], [(-50,-50),(400,-50),(400,300),(-50,300)],
              [(150,-40),(400,100),(100,300),(-60,100)], [(40,20),(280,30),(220,180),(30,160)],
              [(20,80),(100,80),(100,20),(20,20)], [(50,30),(250,60),(150,170)]]
    rng = random.Random(0xa99d)
    for i in range(24):
        left, top = rng.randrange(-100,260), rng.randrange(-100,180)
        width, height = rng.randrange(1,220), rng.randrange(1,180)
        shapes.append([(left,top),(left+width,top),(left+width,top+height),(left,top+height)])
    cases = []
    for points in shapes:
        for shades in ((0,27,27,0),(27,0,0,27),(0,9,27,18),(13,13,13,13)):
            for base in (0,128):
                vertices = [(x,y,shades[i]) for i,(x,y) in enumerate(points)]
                code = bytes(11)+b''.join(b'\x8e'+struct.pack('<hhh',y,x,0) for x,y,_ in vertices)
                code += bytes([0x11,len(vertices)-1,base])+b''.join(bytes([i,s]) for i,(_,_,s) in enumerate(vertices))+b'\x0d'
                pixels = render(Harness,image,code,0,[16384,0,0,0,0,0,0,16384,0], [0,0,0,0,64,0], [0,0],list(range(28)),0,bottom=168,flat=False)
                cases.append((vertices,base,fingerprint(pixels)))
    lines = ['#pragma once','','// Generated by tools/generate_gouraud_reference.py; original shaded model interpreter and VGA writes',
             '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','#include <cstdint>','','namespace darker::test_reference {','',
             'struct gouraud_sample { unsigned int count, base; std::array<std::array<int, 3>, 4> vertices; std::uint64_t fingerprint; };',
             f'inline constexpr std::array<gouraud_sample, {len(cases)}> gouraud_samples{{{{']
    for vertices,base,value in cases:
        values=', '.join('{'+', '.join(map(str,p))+'}' for p in vertices)
        lines.append('  {'+f'{len(vertices)}, {base}, '+'{{'+values+'}}, '+f'0x{value:016x}'+'},')
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/gouraud_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} native Gouraud polygons.')


if __name__ == '__main__':
    main()
