#!/usr/bin/env python3
"""Capture gate interpolation rounding and a complete native fountain cycle."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256
from native_flat_model import render, fingerprint


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    vertex = lambda a, b, c: b'\x8e'+struct.pack('<hhh', c, a, b)
    code = bytes(11)
    for a, c in ((-12, -7), (12, -7), (0, 7)):
        code += vertex(a, 0, c)+b'\x32\x00'+vertex(a+3, 8, c+3)+b'\x38'
    code += bytes([2, 76, 2, 5, 8, 2, 76, 8, 5, 2, 13])
    cases = []
    for near in (False, True):
        for depth in (32, 33, 64, 128):
            for fraction in (19, 127, 255):
                for gate in (0, 32768, 59392, 65535):
                    parameters = [gate]+[0]*255
                    pixels = render(Harness, image, code, 0, [16384, 4096, 0, 0, 0, 16384, 0, 16384, 0],
                                    [0, 11, 0, fraction, depth, 83], [160, 84], list(range(28)), 0,
                                    bottom=168, near=near, parameters=parameters)
                    cases.append((near, depth, fraction, gate, fingerprint(pixels)))
    native = Harness(image)
    cycle = bytearray()
    for clock in range(2048):
        native.write(0xbf8, struct.pack('<H', clock))
        native.call(0xdb1a)
        cycle += native.cpu.mem_read(native.STACK+0x7947, 12)
    lines = ['#pragma once', '', '// Generated by tools/generate_model_animation_reference.py; original gate paths and DB1A',
             '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             f'inline constexpr std::uint64_t fountain_cycle_fingerprint{{0x{fingerprint(cycle):016x}}};',
             f'inline constexpr std::array<std::uint8_t, {len(code)}> gate_code{{'+', '.join(map(str, code))+'};',
             'struct gate_sample { bool near; unsigned int depth, fraction, gate; std::uint64_t fingerprint; };',
             f'inline constexpr std::array<gate_sample, {len(cases)}> gate_samples{{{{']
    lines += ['  {'+str(near).lower()+', '+', '.join(map(str, (depth, fraction, gate)))+f', 0x{value:016x}'+'},' for near, depth, fraction, gate, value in cases]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/model_animation_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(cases)} gate frames and all 2048 fountain steps.')


if __name__ == '__main__':
    main()
