#!/usr/bin/env python3
"""Capture native Skimma target retention and projection with resolved target bounds."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(image).hexdigest() == IMAGE_SHA256
    rng = random.Random(0xcf94)
    rows = []
    word = lambda v: struct.pack('<H',v & 65535)
    for i in range(2048):
        h = Harness(image)
        h.write(0x9c4a,image[0x944a:0x964a])
        angles = (rng.choice((0,0x4000,0x8000,0xc000)),rng.choice((0,0,0,2000,64000)),rng.choice((0,0,4000,61000)))
        for reg, angle in zip(('DI','BX','CX'),angles): h.setreg(reg,(((angle+15)&65535)>>6)*2)
        h.call(0x1d63)
        player = (32000,32000,4000)
        # Narrow-cone and boundary samples mixed with out-of-range world positions.
        forward = rng.choice((15,16,17,64,256,1000,2000,4095,4096))
        side = rng.randrange(-forward//3,forward//3+1)
        delta = ((side,-forward),(-forward,-side),(-side,forward),(forward,side))[angles[0]>>14]
        target = ((player[0]+delta[0])&65535,(player[1]+delta[1])&65535,player[2]+rng.randrange(-300,301))
        extent = rng.randrange(0,1024)
        selection = rng.randrange(3)
        enabled = rng.choice((0,1,1,3))
        reloading = rng.choice((0,0,0,1))
        damage_link = rng.choice((0,1,1,1))
        token = 0xec00 if i & 1 else 0x1234
        cell_type,cell_state = rng.choice((1,77)),rng.choice((0,0x40,0x60))
        h.write(0xb91f,b'\x1b');h.write(0xcf5b,word(selection));h.write(0x4543+selection,bytes([enabled]));h.write(0xbf8,word(100));h.write(0xc51c,word(101 if reloading else 100));h.write(0x5f0f,word(token))
        h.write(0x5e03,word(508));h.write(0x5f20,b'\x00');h.write(0x5f22,word(0));h.write(0x5f25,word(0))
        h.write(0xfdf0,word(0x6000));h.cpu.mem_write(0x60000+0x1268,bytes([cell_type,cell_state]));h.cpu.mem_write(0x6a000,word(0x1000))
        h.cpu.mem_write(h.STACK+0xd98e,struct.pack('<3H',*player))
        h.cpu.mem_write(h.STACK+0xd9b0,struct.pack('<2H',angles[0],angles[1]));h.setreg('BP',0xd986)
        def hook(cpu,address,size,data):
            if address == h.BASE+0xd089:
                for reg,value in zip(('AX','BX','DI','DX'),(*target,extent)): h.setreg(reg,value)
                h.setreg('ES',0x6000);h.setreg('SI',0);h.cpu.mem_write(0x60000,word(damage_link))
                sp=h.getreg('SP');ip=int.from_bytes(cpu.mem_read(h.STACK+sp,2),'little')
                h.setreg('SP',sp+2);h.setreg('IP',ip)
        h.cpu.hook_add(UC_HOOK_CODE,hook);h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        h.call(0xcf4a)
        assert h.getreg('IP') == h.RETURN
        result = [int.from_bytes(h.read(a,2),'little') for a in (0x5f0f,0x5e03,0x5f22,0x5f25)] + [h.read(0x5f20)[0]]
        rows.append((*angles,*player,*target,extent,selection,token,cell_type,cell_state,enabled,reloading,damage_link,*result))
    lines=['#pragma once','','// Generated by tools/generate_skimma_target_reference.py; original CF4A–D088',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           f'inline constexpr std::array<std::array<int, 22>, {len(rows)}> skimma_target_samples{{{{']
    lines += ['  {'+', '.join(map(str,row))+'},' for row in rows]
    lines += ['}};','']
    lines += ['} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/skimma_target_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} native Skimma target projection cases; {sum(r[17] != 65535 for r in rows)} retained.')


if __name__ == '__main__':
    main()
