#!/usr/bin/env python3
"""Capture original tunnel projection and lookahead across the shipped actor starts."""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    root = parser.parse_args().workspace.resolve()
    sys.path.insert(0,str(root / 'tools'))
    from trace_hidden_commands import Harness
    raw = (root / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    h = Harness(raw)
    h.write(0xfdf2,struct.pack('<H',0x4000))
    h.write(0xfdf0,struct.pack('<H',0x3000))
    h.cpu.mem_write(0x70000,(root / 'analysis/resources/00_078.bin').read_bytes())
    h.setreg('DS',0x7000)
    h.setreg('SI',0)
    h.setreg('SP',0xfefe)
    h.cpu.mem_write(h.STACK+0xfefe,struct.pack('<H',h.RETURN))
    h.setreg('EFLAGS',2)
    h.cpu.emu_start(h.BASE+0xd0be,h.BASE+h.RETURN,count=1000000)
    assert h.getreg('IP') == h.RETURN
    samples = []
    records = json.loads((root / 'analysis/missions/scenarios.json').read_text())['records']
    for record in records:
        if record.get('craft_configuration') != 4:
            continue
        map_slot = record['map_resource']
        cells = bytearray(32768)
        cells[::2] = (root / f'analysis/resources/00_{map_slot:03}.bin').read_bytes()
        h.cpu.mem_write(0x30000,bytes(cells))
        for obj in record.get('objects',[]):
            if obj['format'] != 'moving':
                continue
            x,y = obj['position_words']
            h.cpu.mem_write(h.STACK+0xd986,bytes(112))
            h.setreg('BP',0xd986)
            h.setreg('DX',x)
            h.setreg('BX',y)
            h.setreg('DI',obj['heading_word'])
            h.setreg('SI',0xf000)
            h.call(0xbee7)
            cell = (h.getreg('DX') >> 8) | (h.getreg('BX') & 0xff00)
            route = h.cpu.mem_read(h.STACK+0xd986+0x6e,1)[0]
            initial_x,initial_y = h.getreg('DX'),h.getreg('BX')
            for orientation in (route,route ^ 128):
                for lookahead in (0,64,152,400):
                    heading = (len(samples)*37) & 255
                    x = (initial_x + (len(samples) % 3 - 1)*8) & 65535
                    y = (initial_y + (len(samples) % 5 - 2)*8) & 65535
                    h.write(0xd1c0,bytes([heading]))
                    h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
                    h.cpu.mem_write(h.STACK+0xd986+0x60,struct.pack('<HH',1234,cell))
                    h.cpu.mem_write(h.STACK+0xd986+0x6e,bytes([orientation]))
                    h.setreg('BP',0xd986)
                    h.setreg('DX',x)
                    h.setreg('CX',y)
                    h.setreg('DI',lookahead)
                    h.call(0xd284)
                    assert h.getreg('EFLAGS') & 1
                    state = bytes(h.cpu.mem_read(h.STACK+0xd986,112))
                    samples.append([map_slot,cell,orientation,heading,x,y,lookahead,
                                    *struct.unpack_from('<HH',state,0x60),state[0x6e],
                                    h.getreg('SI'),h.getreg('BX'),h.getreg('AX')])
    lines = ['#pragma once','','// Generated by generate_tunnel_trace_reference.py; native D284 with original maps and routes.',
             '#include <array>','#include <cstdint>','','namespace darker::test_reference {','',
             f'inline constexpr std::array<std::array<uint16_t,13>,{len(samples)}> tunnel_trace_samples{{{{']
    lines += ['  {'+','.join(map(str,s))+'},' for s in samples]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1] / 'tests/reference/tunnel_trace_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(samples)} native tunnel lookahead samples.')


if __name__ == '__main__':
    main()
