#!/usr/bin/env python3
"""Fingerprint the independently analysed archive-04 record and setup fields."""
import argparse
import hashlib
import json
from pathlib import Path
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    source = args.workspace/'analysis/missions/scenarios.json'
    document = json.loads(source.read_text())
    assert document['image_sha256'] == IMAGE_SHA256
    rows = []
    for record in document['records']:
        raw = (args.workspace/f'analysis/resources/{record["resource"]}.bin').read_bytes()
        start = record['record_offset']
        shared = record['shared_offset']
        end = shared + record['shared_length']
        assert raw[shared:end] == bytes.fromhex(record['shared_hex'])
        values = [start, record['record_size'], shared, record['shared_length'], record['entry_offset'],
                  record['time_multiplier'], record['configuration_raw']]
        boundaries = [start + 2 + int.from_bytes(raw[start+i:start+i+2], 'little') for i in (2, 4, 6)]
        boundaries.append(start+record['record_size'])
        for i in range(3):
            values += [boundaries[i], boundaries[i+1]-boundaries[i], *raw[boundaries[i]:boundaries[i+1]]]
        if record['kind'] == 'world_setup':
            beacon = record['initial_beacon_sequence']
            sequence = bytes.fromhex(beacon['raw_hex'])
            values += [beacon['offset'], len(sequence), *sequence, record['objective_cell_list'], record['player_script_offset']]
            for cells in record['cell_lists']:
                values += [len(cells['cells']), cells['terminator']]
                for cell in cells['cells']:
                    values += cell
            for group in record['groups']:
                objects = [o for o in record['objects'] if o['group'] == group['index']]
                blocks = [b for b in record['native_setup'] if b['group'] == group['index']]
                values += [len(objects), len(blocks)]
                for obj in objects:
                    source_bytes = bytes.fromhex(obj['raw_hex'])
                    assert raw[obj['offset']:obj['offset']+len(source_bytes)] == source_bytes
                    values += [obj['offset'], len(source_bytes), ['moving', 'compact_special', 'absolute_static'].index(obj['format']),
                               obj['definition_slot'], int(obj['counts_toward_objective_counter']), obj.get('attribute_byte', 0), obj['heading_word'],
                               *obj['position_words'], *bytes.fromhex(obj.get('runtime_50_55_hex', '00 00 00 00 00 00')),
                               obj.get('script_or_target_word', 0xffffffff), obj.get('script_offset', obj.get('route_offset', 0xffffffff))]
                for block in blocks:
                    current = sum(o['offset'] < block['offset'] for o in record['objects'])
                    values += [block['offset'], block['length'], current, *bytes.fromhex(block['raw_hex'])]
        fingerprint = 0xcbf29ce484222325
        for value in values:
            for byte in value.to_bytes(4, 'little'):
                fingerprint = ((fingerprint ^ byte)*0x100000001b3) & ((1<<64)-1)
        rows.append((int(record['resource'][3:]), record['record'], fingerprint))
    lines = ['#pragma once', '', '// Generated by tools/generate_scenario_reference.py from the independently checked scenario export',
             '// Scenario JSON SHA-256: '+hashlib.sha256(source.read_bytes()).hexdigest(), '// Image SHA-256: '+IMAGE_SHA256,
             '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct scenario_sample { unsigned int resource, record; std::uint64_t fingerprint; };',
             f'inline constexpr std::array<scenario_sample, {len(rows)}> scenario_samples{{{{']
    lines += [f'  {{{slot}, {record}, 0x{fingerprint:016x}}},' for slot, record, fingerprint in rows]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/scenario_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} scenario records, including exact formatted language sections.')


if __name__ == '__main__':
    main()
