#!/usr/bin/env python3
"""Capture live Caero gauges and Skimma speed strips from native producers."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('workspace',type=Path);args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    image=(args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(image).hexdigest()!=IMAGE_SHA256:raise ValueError('Unsupported unpacked executable')
    h=Harness(image);rng=random.Random(0x56d3);cases=[]
    def skip_sound(cpu,address,size,data):
        if address-h.BASE==0x36a6:
            sp=h.getreg('SP');target=int.from_bytes(cpu.mem_read(h.STACK+sp,2),'little');h.setreg('SP',sp+2);h.setreg('IP',target)
    h.cpu.hook_add(UC_HOOK_CODE,skip_sound)
    h.setreg('BP',0xd986);h.write(0xf003,b'\x01')
    for index in range(1024):
        damage=rng.randrange(5)*256+rng.randrange(68);boost=rng.randrange(0xc000);altitude=rng.randrange(65536);clock=rng.randrange(65536)
        speed=rng.randrange(65536);upgraded=rng.randrange(2)
        for at,value in ((0x8509,damage),(0x8540,boost),(0xbf8,clock)):h.write(at,struct.pack('<H',value))
        h.cpu.mem_write(h.STACK+0xd992,struct.pack('<H',altitude));h.cpu.mem_write(h.STACK+0xd9c4,struct.pack('<H',speed))
        h.write(0xb91f,bytes([27 if upgraded else 26]));h.setreg('DS',0x1000)
        h.cpu.emu_start(h.BASE+0x56d3,h.BASE+0x573c,count=1000)
        values=list(h.read(0x454b,5));h.call(0x582b);values.append(h.read(0x454d)[0])
        cases.append(([damage,boost,altitude,clock,speed,upgraded],values))
    lines=['#pragma once','','// Generated by tools/generate_flight_instruments_reference.py; native 56D3/582B',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           'struct flight_instruments_sample { std::array<int, 6> input, output; };',
           f'inline constexpr std::array<flight_instruments_sample, {len(cases)}> flight_instruments_samples{{{{']
    lines+=['  {'+', '.join('{'+', '.join(map(str,part))+'}' for part in case)+'},' for case in cases]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/flight_instruments_samples.h').write_text('\n'.join(lines))


if __name__=='__main__':main()
