#!/usr/bin/env python3
"""Capture Skimma number-key selection, enable flags and shared reload state."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    image = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(image).hexdigest() == IMAGE_SHA256
    rng = random.Random(0xc8a7)
    rows = []
    for i in range(1024):
        h = Harness(image)
        selection = rng.randrange(4)
        selected = rng.randrange(3)
        flags = [rng.randrange(256) for _ in range(3)]
        available = rng.randrange(8)
        clock,deadline,spread,target = [rng.randrange(65536) for _ in range(4)]
        word = lambda value: struct.pack('<H',value)
        h.write(0xb91f,b'\x1b');h.write(0xcf5b,word(selected));h.write(0x4543,bytes(flags))
        h.write(0xc88c,word(available));h.write(0xbf8,word(clock));h.write(0xc51c,word(deadline))
        h.write(0x5e00,word(spread));h.write(0x5f0f,word(target));h.setreg('AX',selection)
        def hook(cpu,address,size,data):
            if address == h.BASE+0xb903:
                sp=h.getreg('SP');h.setreg('IP',int.from_bytes(cpu.mem_read(h.STACK+sp,2),'little'));h.setreg('SP',sp+2)
        h.cpu.hook_add(UC_HOOK_CODE,hook);h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        h.call(0xc8a7)
        assert h.getreg('IP') == h.RETURN
        result = [int.from_bytes(h.read(p,2),'little') for p in (0xcf5b,0xc51c,0x5e00,0x5f0f)] + list(h.read(0x4543,3))
        rows.append([selection,selected,*flags,available,clock,deadline,spread,target,*result])
    lines=['#pragma once','','// Generated by tools/generate_skimma_selection_reference.py; original C8A7',
      '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
      f'inline constexpr std::array<std::array<int,17>,{len(rows)}> skimma_selection_samples{{{{']
    lines += ['  {'+', '.join(map(str,row))+'},' for row in rows]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/skimma_selection_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} native selection cases.')


if __name__ == '__main__':
    main()
