#!/usr/bin/env python3
"""Capture retail type-17 approach capture and automatic return on the original Delphi map."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args = parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from verify_player_collisions import setup
    raw = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    h,bank,_ = setup(30)
    cells = bytearray()
    for kind in (args.workspace/'analysis/resources/00_068.bin').read_bytes(): cells.extend((kind,0))
    h.cpu.mem_write(0x60000,bytes(cells))
    for at,value in ((0xc81e,0x7162),(0xc610,0x7162),(0xc84f,0xe000),(0x7a2b,8)):h.write(at,struct.pack('<H',value))
    h.write(0xe000,b'\xff');h.write(0xc16f,b'\0');h.write(0xf003,b'\1');h.write(0xb91f,b'\x19')
    bp=0xd986
    h.cpu.mem_write(h.STACK+bp,bytes(112))
    h.setreg('BP',bp);h.setreg('BX',0x1926+25*24);h.call(0xbf41)
    h.cpu.mem_write(h.STACK+bp+8,struct.pack('<3H',12672,28380,500))
    h.cpu.mem_write(h.STACK+bp+0x2a,struct.pack('<H',0x8000))
    h.cpu.mem_write(h.STACK+bp+0x66,struct.pack('<H',0x7eb6))
    h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
    h.call(0xc670)
    assert int.from_bytes(h.cpu.mem_read(h.STACK+bp+0x66,2),'little') == 0x7cef
    rows=[]
    for clock in range(8,16001,8):
        h.write(0xbf0,struct.pack('<H',clock));h.setreg('DS',0x1000);h.setreg('BP',bp);h.setreg('CX',8)
        callback=int.from_bytes(h.cpu.mem_read(h.STACK+bp+0x66,2),'little')
        h.call(callback)
        h.setreg('DS',0x1000);h.setreg('BP',bp);h.call(0xc582)
        state=bytes(h.cpu.mem_read(h.STACK+bp,112))
        callback=struct.unpack_from('<H',state,0x66)[0]
        complete=h.read(0x3e9a)[0] == 1
        rows.append([clock,*struct.unpack_from('<3H',state,8),*state[4:7],*struct.unpack_from('<5H',state,0x26),
                     struct.unpack_from('<H',state,0x3e)[0],int.from_bytes(h.cpu.mem_read(h.STACK+0x7935,2),'little'),
                     3 if complete else 2 if callback==0x7d32 else 1])
        if complete:break
    assert complete
    lines=['#pragma once','','// Generated by tools/generate_hangar_return_reference.py; original C670/7CEF/7D32/C582',
           '// Image SHA-256: '+IMAGE_SHA256,'','#include <array>','','namespace darker::test_reference {','',
           f'inline constexpr std::array<std::array<int, 15>, {len(rows)}> hangar_return_samples{{{{']
    lines+=['  {'+', '.join(map(str,row))+'},' for row in rows]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/hangar_return_samples.h').write_text('\n'.join(lines))
    print('Captured',len(rows),'return frames; completion at',clock,'ticks.')


if __name__ == '__main__':main()
