#!/usr/bin/env python3
"""Regenerate the supported directory from verified original executable metadata.

Development-only: the C++ application does not require Python or analysis files.
"""
import argparse
import hashlib
from pathlib import Path
from format_cpp_initialisers import format_designated_initialisers

IMAGE_SHA256 = '7599201a01aa24b7e6ad1ae4295d493821cde7c3a43b247c464522626c0380a4'
ARCHIVE_SIZES = (1195478, 1337498, 1453028, 1402901, 134178)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('image', type=Path)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1] / 'src/resources/directory.h')
    args = parser.parse_args()
    image = args.image.read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    entries = []
    for archive, size in enumerate(ARCHIVE_SIZES):
        at = 0x4534 + archive * 2
        table = int.from_bytes(image[at:at + 2], 'little')
        previous = 0
        for slot in range(513):
            offset = int.from_bytes(image[table + slot * 3:table + slot * 3 + 3], 'little')
            if slot == 0:
                assert offset == 0
                continue
            assert previous < offset <= size
            entries.append((archive, slot - 1, previous, offset - previous))
            previous = offset
            if offset == size:
                break
        else:
            raise ValueError('Missing final boundary')
    assert len(entries) == 164
    text = ['#pragma once', '', '// Generated by tools/generate_resource_directory.py; do not edit by hand',
            '// Source image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '#include "archive_set.h"', '',
            'namespace darker::resources {', '',
            'inline std::array<std::size_t, 5> constexpr supported_archive_sizes{' + ', '.join(map(str, ARCHIVE_SIZES)) + '};', '',
            'inline std::array<directory_entry, 164> constexpr supported_directory{{']
    for archive, slot, offset, length in entries:
        text.append(f'  {{.id{{.archive{{{archive}}}, .slot{{{slot}}}}}, .offset{{{offset}}}, .compressed_size{{{length}}}}},')
    text += ['}};', '', '} // namespace darker::resources', '']
    args.output.write_text(format_designated_initialisers('\n'.join(text)))


if __name__ == '__main__':
    main()
