#!/usr/bin/env python3
"""Capture native object-target missile eligibility at 8AFD through 8B5E."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    from unicorn import UC_HOOK_CODE
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    h = Harness(raw)
    fired = -1

    def hook(cpu, address, size, data):
        nonlocal fired
        p = address - h.BASE
        if p == 0x3dcb:
            h.setreg('IP', h.RETURN)
            return
        if p == 0x8b91:
            # Ray geometry/randomness has independent comparisons; resume its common continuation.
            h.setreg('IP', 0x8bda)
        if p == 0xcaf0:
            fired = (h.getreg('BX') - 0x1926) // 24
            sp = h.getreg('SP')
            h.setreg('IP', int.from_bytes(cpu.mem_read(h.STACK + sp, 2), 'little'))
            h.setreg('SP', sp + 2)
    h.cpu.hook_add(UC_HOOK_CODE, hook)
    rng = random.Random(0x8b28)
    rows = []
    for i in range(2048):
        slot = rng.choice((19,20,24))
        behaviour = rng.choice((0,9,15,127,128,255))
        difficulty = rng.choice((2,4,6,128,255))
        distance = rng.randrange(14)
        heading, pitch = rng.randrange(65536),rng.randrange(65536)
        desired = [(a + rng.randrange(-800,801)) & 65535 for a in (heading,pitch)]
        target = rng.choice((0xd986,0xd986,0xd986,0xda00,0x1234))
        flags = rng.choice((0,2))
        target_flags = rng.choice((0,0,0,16,32))
        last = rng.randrange(65536)
        weapon = raw[0x1926 + slot*24 + 16]
        total = ((difficulty >> 1) | 128) + behaviour
        delay = ((raw[0x1926 + weapon*24 + 10]*4 - ((0xfd00 if total>255 else 0xfc00) | (total&255)))*4)&65535
        clock = (last + rng.choice((delay-1,delay,delay+1,rng.randrange(65536))))&65535
        obj = bytearray(112)
        obj[7]=flags;obj[0x21]=slot;obj[0x50]=behaviour
        struct.pack_into('<2H',obj,0x2a,heading,pitch)
        struct.pack_into('<H',obj,0x44,0x1926+slot*24)
        struct.pack_into('<H',obj,0x48,target)
        struct.pack_into('<H',obj,0x6a,last)
        h.cpu.mem_write(h.STACK+0xda70,bytes(obj))
        h.cpu.mem_write(h.STACK+target+7,bytes([target_flags]))
        for at,value in ((0x8c29,desired[1]),(0x8c37,desired[0]),(0xbf0,clock)):
            h.write(at,struct.pack('<H',value))
        h.write(0x3dc5,bytes([difficulty]));h.write(0xc50,b'\x80')
        h.setreg('BP',0xda70);h.setreg('DX',(distance<<8)|raw[0x1926+slot*24+9])
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
        fired=-1;h.call(0x8afd)
        rows.append([slot,behaviour,difficulty,distance,heading,pitch,*desired,target,flags,target_flags,last,clock,fired])
    pressure=[]
    for wraps in (0,3,4,5,7,8,9,255):
        for high in (0,1,127,255):
            for current in (2,100,255):
                h.write(0x3db3,bytes([wraps]));h.write(0xbf9,bytes([high]));h.write(0x3dc5,bytes([current]))
                h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);h.call(0x3db1)
                pressure.append([(wraps<<16)|(high<<8),current,h.read(0x3dc5)[0]])
    lines=['#pragma once','','// Generated by tools/generate_aircraft_fire_reference.py; original 8AFD/8B28',
           '// Ray geometry and projectile allocation intercepted; eligibility and definition selection retained.',
           '#include <array>','','namespace darker::test_reference {','',
           f'inline constexpr std::array<std::array<int,14>,{len(rows)}> aircraft_fire_samples{{{{']
    lines+=['  {'+','.join(map(str,row))+'},' for row in rows]
    lines+=['}};','',f'inline constexpr std::array<std::array<unsigned int,3>,{len(pressure)}> difficulty_samples{{{{']
    lines+=['  {'+','.join(map(str,row))+'},' for row in pressure]
    lines+=['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/aircraft_fire_samples.h').write_text('\n'.join(lines))
    print('Captured',len(rows),'missile eligibility cases;',sum(r[-1]>=0 for r in rows),'launches admitted.')


if __name__=='__main__':main()
