#!/usr/bin/env python3
"""Capture the native beacon lookup, distance attenuation and Caero energy accounting."""
import argparse
import hashlib
from pathlib import Path
import random
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    raw = (args.workspace / 'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    native = Harness(raw)
    word = lambda value: struct.pack('<H', value & 65535)
    native.setreg('ES', 0x6000)
    native.cpu.emu_start(native.BASE+0x396, native.BASE+0x3ab, count=5000)
    assert native.getreg('IP') == 0x3ab
    lookup = bytes(native.cpu.mem_read(0x6a800, 256))
    native.write(0xfdf0, word(0x6000))
    rng = random.Random(0x8450)
    lighting = []
    for index in range(768):
        # Every coordinate high byte, plus a denser sample of playable map cells.
        x = ((index % 256) << 8) | rng.randrange(256)
        y = rng.randrange(65536 if index < 256 else 32768)
        if index >= 512:
            x = rng.randrange(32768)
        z = rng.choice((0, 2400, 11615, 11616, 32767, 32768, 65535, rng.randrange(12000)))
        fx, fy, strength = [rng.randrange(256) for _ in range(3)]
        kind = rng.choice((1, 1, 1, 0, 11, 12))
        cell_x, cell_y = lookup[x >> 8], lookup[y >> 8]
        if cell_x < 128 and cell_y < 128:
            native.cpu.mem_write(0x60000+cell_y*256+cell_x*2, bytes([kind, strength]))
        for register, value in [('DX', x), ('BX', y), ('SI', z), ('AX', fx | fy << 8)]:
            native.setreg(register, value)
        native.call(0x8450)
        lighting.append([x, y, z, fx, fy, kind, strength, cell_x, cell_y, native.getreg('AX')])
    charging = []
    for source in (0, 249, 250, 251, 255, 256, 771, 3276, 13107, 65535):
        for flags in (0, 1, 3, 128):
            for cheat in (0, 1):
                for step in (0, 128, 1028, 16448, 65535):
                    buffer = rng.choice((0, 65535, rng.randrange(65536)))
                    reserve = rng.choice((0, 0xcfff, rng.randrange(65536)))
                    boost = rng.choice((0, 0xbfff, rng.randrange(65536)))
                    for offset, value in ((0x7f8f, buffer), (0x7fa6, reserve), (0x8540, boost)):
                        native.write(offset, word(value))
                    native.write(0x7f7b, b'\x89\xca' if cheat else b'\xf7\xe1')
                    native.cpu.ctl_remove_cache(native.BASE+0x7f38, native.BASE+0x7fc5)
                    native.cpu.ctl_remove_cache(native.BASE+0x8529, native.BASE+0x854e)
                    native.write(0x4552, bytes([flags]))
                    native.setreg('AX', source)
                    native.cpu.emu_start(native.BASE+0x7f38, native.BASE+0x7f50, count=100)
                    assert native.getreg('IP') == 0x7f50
                    native.setreg('CX', step)
                    native.cpu.emu_start(native.BASE+0x7f6c, native.BASE+0x7fc5, count=200)
                    assert native.getreg('IP') == 0x7fc5
                    result = [int.from_bytes(native.read(a, 2), 'little') for a in (0x7f8f, 0x7fa6, 0x8540)]
                    result += [native.read(a)[0] for a in (0x4550, 0x4551)]
                    charging.append([source, flags, cheat, step, buffer, reserve, boost, *result])
    lines = ['#pragma once', '', '// Generated by tools/generate_beacon_energy_reference.py; native 0396, 8450, 7F38, 7F6C and 8529',
             '// Image SHA-256: ' + IMAGE_SHA256, '', '#include <array>', '', 'namespace darker::test_reference {', '',
             'struct beacon_sample { int x, y, z, fx, fy, kind, strength, cell_x, cell_y, result; };',
             f'inline constexpr std::array<beacon_sample, {len(lighting)}> beacon_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row)) + '},' for row in lighting]
    lines += ['}};', '', 'struct energy_sample {', '  int source, flags, cheat, step, buffer, reserve, boost;', '  std::array<int, 5> result;', '};',
              f'inline constexpr std::array<energy_sample, {len(charging)}> energy_samples{{{{']
    lines += ['  {' + ', '.join(map(str, row[:7])) + ', {' + ', '.join(map(str, row[7:])) + '}},' for row in charging]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1] / 'tests/reference/beacon_energy_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(lighting)} beacon samples and {len(charging)} energy accounting updates.')


if __name__ == '__main__':
    main()
