#!/usr/bin/env python3
"""Capture original underground heading selection and junction/door state changes."""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    root = parser.parse_args().workspace.resolve()
    sys.path.insert(0,str(root / 'tools'))
    from trace_hidden_commands import Harness
    raw = (root / 'analysis/unpacked/image.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest() == IMAGE_SHA256
    class Probe(Harness):
        def hook(self,cpu,address,size,data):
            if address == self.BASE + 0x8750:
                self.setreg('IP',self.RETURN)
                return
            super().hook(cpu,address,size,data)
    h = Probe(raw)
    h.write(0xfdf2,struct.pack('<H',0x4000))
    h.write(0xfdf0,struct.pack('<H',0x3000))
    h.cpu.mem_write(0x70000,(root / 'analysis/resources/00_078.bin').read_bytes())
    h.setreg('DS',0x7000)
    h.setreg('SI',0)
    h.setreg('SP',0xfefe)
    h.cpu.mem_write(h.STACK+0xfefe,struct.pack('<H',h.RETURN))
    h.setreg('EFLAGS',2)
    h.cpu.emu_start(h.BASE+0xd0be,h.BASE+h.RETURN,count=1000000)
    assert h.getreg('IP') == h.RETURN
    samples = []
    records = json.loads((root / 'analysis/missions/scenarios.json').read_text())['records']
    for record in records:
        if record.get('craft_configuration') != 4:
            continue
        map_slot = record['map_resource']
        cells = bytearray(32768)
        cells[::2] = (root / f'analysis/resources/00_{map_slot:03}.bin').read_bytes()
        h.cpu.mem_write(0x30000,bytes(cells))
        for obj in record.get('objects',[]):
            if obj['format'] != 'moving':
                continue
            x,y = obj['position_words']
            h.cpu.mem_write(h.STACK+0xd986,bytes(112))
            h.setreg('BP',0xd986)
            h.setreg('DX',x)
            h.setreg('BX',y)
            h.setreg('DI',obj['heading_word'])
            h.setreg('SI',0xf000)
            h.call(0xbee7)
            cell = (h.getreg('DX') >> 8) | (h.getreg('BX') & 0xff00)
            route = h.cpu.mem_read(h.STACK+0xd986+0x6e,1)[0]
            initial_heading = h.getreg('DI')
            for orientation in (route,route ^ 128):
                h.setreg('AX',orientation << 8)
                h.setreg('BX',cell)
                h.call(0xd24b)
                h.setreg('BX',cell)
                h.call(0xd219)
                exit_cell = h.getreg('DX')
                for dx,dy in ((0,0),(3,0),(-3,0),(0,3),(0,-3),(3,2),(-2,3),(-3,-2)):
                    target = ((exit_cell+dx) & 255) | ((((exit_cell >> 8)+dy) & 255) << 8)
                    heading = (initial_heading + len(samples)*1237) & 65535
                    oscillation = (len(samples)*29) & 255
                    progress = (len(samples)*137) & 65535
                    h.cpu.mem_write(h.STACK+0xd986+0x2a,struct.pack('<H',heading))
                    h.cpu.mem_write(h.STACK+0xd986+0x47,bytes([oscillation]))
                    h.cpu.mem_write(h.STACK+0xd986+0x4a,struct.pack('<H',target))
                    h.cpu.mem_write(h.STACK+0xd986+0x60,struct.pack('<HH',progress,cell))
                    h.cpu.mem_write(h.STACK+0xd986+0x6e,bytes([orientation]))
                    h.setreg('BP',0xd986)
                    h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536)
                    h.call(0x860d)
                    after = bytes(h.cpu.mem_read(h.STACK+0xd986,112))
                    samples.append([map_slot,cell,orientation,target,heading,oscillation,progress,
                                    int.from_bytes(after[0x62:0x64],'little'),after[0x6e],after[0x47],
                                    int.from_bytes(after[0x60:0x62],'little'),h.read(0xd1c0)[0]])
    lines = ['#pragma once','','// Generated by generate_tunnel_navigation_reference.py; native 860D–874D with original maps and routes.',
             '#include <array>','#include <cstdint>','','namespace darker::test_reference {','',
             f'inline constexpr std::array<std::array<uint16_t,12>,{len(samples)}> tunnel_navigation_samples{{{{']
    lines += ['  {'+','.join(map(str,s))+'},' for s in samples]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1] / 'tests/reference/tunnel_navigation_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(samples)} native underground heading choices.')


if __name__ == '__main__':
    main()
