#!/usr/bin/env python3
"""Fingerprint native city state selection for each original geometry bank."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace', type=Path)
    args = parser.parse_args()
    sys.path.insert(0, str(args.workspace.resolve() / 'tools'))
    from trace_hidden_commands import Harness
    from inspect_city import geometry_bank
    raw = (args.workspace/'analysis/unpacked/image.bin').read_bytes()
    if hashlib.sha256(raw).hexdigest() != IMAGE_SHA256:
        raise ValueError('Unsupported unpacked executable')
    native = Harness(raw)
    word = lambda value: struct.pack('<H', value & 65535)
    rows = []
    for slot in (30, 31, 32):
        data = (args.workspace/f'analysis/resources/00_{slot:03}.bin').read_bytes()
        bank = geometry_bank(data, slot)
        native.cpu.mem_write(0x70400, data[bank['pool_start']:bank['tail_start']])
        mask = raw[0xbdec+9*(slot-30)+4]
        native.write(0x2e10, bytes([mask*2]))
        native.cpu.ctl_remove_cache(native.BASE+0x2de1, native.BASE+0x2e21)
        native.write(0x3142, word(0x7000))
        native.write(0xfdf0, word(0x3000))
        fingerprint = 0xcbf29ce484222325
        for entry in bank['types']:
            native.cpu.mem_write(0x3a000+entry['type']*8, word(entry['geometry_pool_offset']+0x400)+bytes.fromhex(entry['record_hex'])[2:])
            for state in range(256):
                native.cpu.mem_write(0x30000, bytes([entry['type'], state]))
                native.setreg('DS', 0x1000)
                native.setreg('BX', 0)
                native.call(0x2de1)
                offset = native.getreg('SI')-0x400
                assert 0 <= offset <= bank['pool_size']-11
                for byte in (offset & 255, offset >> 8):
                    fingerprint = ((fingerprint ^ byte)*0x100000001b3)&((1<<64)-1)
        rows.append((slot, bank['type_count'], bank['special_count'], bank['pool_size'], bank['tail_size'], mask, fingerprint))
    lines = ['#pragma once', '', '// Generated by tools/generate_geometry_bank_reference.py; native 2DE1 with original bank data',
             '// Image SHA-256: '+IMAGE_SHA256, '', '#include <array>', '#include <cstdint>', '', 'namespace darker::test_reference {', '',
             'struct geometry_bank_sample { unsigned int slot, types, specials, pool_size, tail_size, mask; std::uint64_t fingerprint; };',
             'inline constexpr std::array<geometry_bank_sample, 3> geometry_bank_samples{{']
    lines += ['  {'+', '.join(map(str, row[:-1]))+', 0x'+f'{row[-1]:016x}'+'},' for row in rows]
    lines += ['}};', '', '} // namespace darker::test_reference', '']
    (Path(__file__).resolve().parents[1]/'tests/reference/geometry_bank_samples.h').write_text('\n'.join(lines))
    print('Captured native state selection for all 256 states of all 391 city types.')


if __name__ == '__main__':
    main()
