#!/usr/bin/env python3
"""Capture supply approach, centring and departure updates from original motion callbacks."""
import argparse
import hashlib
from pathlib import Path
import random
import sys
from generate_resource_directory import IMAGE_SHA256


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('workspace',type=Path)
    args=parser.parse_args()
    sys.path.insert(0,str(args.workspace.resolve()/'tools'))
    from verify_supply_motion import fresh
    assert hashlib.sha256((args.workspace/'analysis/unpacked/image.bin').read_bytes()).hexdigest()==IMAGE_SHA256
    rng=random.Random(0x7d9a)
    rows=[]
    for i in range(512):
        h=fresh()
        phase=rng.choice((1,1,2))
        x,y=rng.choice((0x1000,0x1080,0x10c0)),rng.choice((0x2000,0x2010,0x2080))
        height=rng.choice((264,328,400,1023))
        heading=rng.choice((0,0x4000,0x8000,0xc000,rng.randrange(65536)))
        output=rng.choice((0,511,512,700,1100))
        vertical=rng.randrange(65536)
        target=rng.choice((0,511,512,600,700,1100))
        active=rng.randrange(2)
        control=rng.choice((0,0xbff,0xc00,0x7fff,0x8000))
        step=rng.choice((8,16,32,255))
        offset=rng.choice((0x1080,0x8080))
        fraction=rng.randrange(256)
        for off,value in [(8,x),(10,y),(12,height),(0x2a,heading),(0x42,output),(0x40,vertical),(0x66,0x7d9a if phase==1 else 0x7e49)]:
            h.word(h.BP+off,value,True)
        h.word(0x7e4a,target);h.word(0x7da9,offset);h.write(0x7d70,bytes([fraction]))
        h.write(0x7e61,bytes([active]));h.word(0xd5ca,control)
        h.cpu.ctl_remove_cache(h.BASE,h.BASE+65536);h.step(step)
        callback=h.word(h.BP+0x66,stack=True)
        result=[h.word(h.BP+p,stack=True) for p in (8,10,12,0x2a,0x42,0x40,0x3e)]
        result += [h.cpu.mem_read(h.STACK+h.BP+7,1)[0],{0x8108:0,0x7d9a:1,0x7e49:2}[callback],h.word(0x7da9),h.read(0x7d70)[0]]
        rows.append([phase,x,y,height,heading,output,vertical,target,active,control,step,offset,fraction]+result)
    trajectories=[]
    for step in (8,16,32):
        h=fresh()
        for frame in range(6000):
            h.step(step)
            if h.word(h.BP+0x66,stack=True)==0x7e49:
                trajectories.append([step,frame+1,h.word(h.BP+0x2a,stack=True)]);break
        else:raise AssertionError('Original approach did not finish')
    lines=['#pragma once','','// Generated by tools/generate_supply_motion_reference.py; native 7D9A/7E49',
      '// Attitude is level and stationary; the native attitude helper is isolated.','#include <array>','',
      'namespace darker::test_reference {','',f'inline constexpr std::array<std::array<int,24>,{len(rows)}> supply_motion_samples{{{{']
    lines += ['  {'+', '.join(map(str,row))+'},' for row in rows]
    lines += ['}};','',f'inline constexpr std::array<std::array<int,3>,{len(trajectories)}> supply_approaches{{{{']
    lines += ['  {'+', '.join(map(str,row))+'},' for row in trajectories]
    lines += ['}};','','} // namespace darker::test_reference','']
    (Path(__file__).resolve().parents[1]/'tests/reference/supply_motion_samples.h').write_text('\n'.join(lines))
    print(f'Captured {len(rows)} supply updates and {len(trajectories)} complete approaches.')


if __name__ == '__main__': main()
