# Isolate the pinned DOSBox chip core from its DOSBox mixer adapter. The original
# synthesis code and licence headers are preserved in the generated build files.
set(dbopl_directory "${CMAKE_CURRENT_BINARY_DIR}/dbopl")
file(MAKE_DIRECTORY "${dbopl_directory}")
foreach(extension cpp h)
  file(READ "${dosbox_opl_SOURCE_DIR}/src/hardware/dbopl.${extension}" core)
  if(extension STREQUAL "cpp")
    set(boundary "Bit32u Handler::WriteAddr")
    set(ending "\n}\n")
  else()
    set(boundary "struct Handler")
    set(ending "\nvoid InitTables();\n}\n")
  endif()
  string(FIND "${core}" "${boundary}" position)
  if(position LESS 0)
    message(FATAL_ERROR "Pinned DBOPL adapter boundary was not found")
  endif()
  string(SUBSTRING "${core}" 0 ${position} core)
  string(REPLACE "#include \"adlib.h\"" "" core "${core}")
  file(WRITE "${dbopl_directory}/dbopl.${extension}" "${core}${ending}")
endforeach()
add_library(dosbox_opl_core STATIC "${dbopl_directory}/dbopl.cpp")
target_include_directories(dosbox_opl_core SYSTEM PUBLIC "${dbopl_directory}")
target_include_directories(dosbox_opl_core SYSTEM PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/src/platform/dbopl")
target_compile_features(dosbox_opl_core PRIVATE cxx_std_23)
